if (self.CavalryLogger) { CavalryLogger.start_js(["LZ3DYEq"]); }

__d("RoomsCreatePCIDialogQuery$Parameters",[],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:"3337005606358188",metadata:{},name:"RoomsCreatePCIDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("updatePageFavIcon",["ErrorGuard","recoverableViolation"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){a!=null&&a instanceof HTMLLinkElement&&c("ErrorGuard").applyWithGuard(function(){var d=a.href,e=a.dataset,f=e.badgedIcon;e=e.defaultIcon;e!=null&&f!=null?!b&&d===f?a.href=e:b&&d===e&&(a.href=f):c("recoverableViolation")("Unable to update favicon. icon href was not found on the favicon element, please set data-default-icon and data-badged-icon attributes.","comet_ui")},null,[])}g["default"]=a}),98);
__d("RoomsCreatePCIDialog.entrypoint",["JSResourceForInteraction","RoomsCreatePCIDialogQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(){return{queries:{queryReference:{parameters:c("RoomsCreatePCIDialogQuery$Parameters"),variables:{scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("RoomsCreatePCIDialog.react").__setRef("RoomsCreatePCIDialog.entrypoint")};g["default"]=a}),98);
__d("useRoomsCreateDialog",["RoomsCreatePCIDialog.entrypoint","useCometEntryPointDialog"],(function(a,b,c,d,e,f,g){"use strict";function a(){var a=c("useCometEntryPointDialog")(c("RoomsCreatePCIDialog.entrypoint"),{routeParams:{},routeProps:{}},"button"),b=a[0],d=a[1],e=a[2],f=a[3];a=a[4];return{dialogTriggerRef:d,onHoverInPrerenderer:e,onHoverOutPrerenderer:f,onPressInPrerenderer:a,showDialog:function(a){var c=a.initialInvitedFriends,d=a.loggingData,e=a.onClose;a=a.onSave;b({initialInvitedFriends:c,loggingData:d,onSave:a},e,"comet.rooms.create")}}}g["default"]=a}),98);
__d("logCometWatchTabSelectedEvent",["VideoHomeTypedLoggerLite"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b,d){c("VideoHomeTypedLoggerLite").log({click_point:a,entry_point_type:d,event:"video_tab_selected",tab_selection_type:"user_initiated_click",was_badged:b})}g["default"]=a}),98);
__d("CometAccessibilitySettingsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1808128");c=b("FalcoLoggerInternal").create("comet_accessibility_settings",a);e.exports=c}),null);
__d("NotifClickEventsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1835463");c=b("FalcoLoggerInternal").create("notif_click_events",a);e.exports=c}),null);
__d("NotifImpressionEventsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1835750");c=b("FalcoLoggerInternal").create("notif_impression_events",a);e.exports=c}),null);
__d("OpenOptionsMenuFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1836366");c=b("FalcoLoggerInternal").create("open_options_menu",a);e.exports=c}),null);
__d("RoomCreationFlowStartFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f){"use strict";a=b("getFalcoLogPolicy_DO_NOT_USE")("1744286");c=b("FalcoLoggerInternal").create("room_creation_flow_start",a);e.exports=c}),null);
__d("DisplayGenderConst",[],(function(a,b,c,d,e,f){a=Object.freeze({UNKNOWN:"UNKNOWN",FEMALE:"FEMALE",MALE:"MALE",NEUTER:"NEUTER"});f["default"]=a}),66);
__d("XCometSettingsControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/settings/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("mergeHelpers",["invariant","FbtResultBase"],(function(a,b,c,d,e,f,g,h){"use strict";var i=36,j=function(a){return typeof a!=="object"||a instanceof Date||a===null||a instanceof c("FbtResultBase")},k={MAX_MERGE_DEPTH:i,isTerminal:j,normalizeMergeArg:function(a){return a==null?{}:a},checkMergeArrayArgs:function(a,b){Array.isArray(a)&&Array.isArray(b)||h(0,3714,a,b)},checkMergeObjectArgs:function(a,b){k.checkMergeObjectArg(a),k.checkMergeObjectArg(b)},checkMergeObjectArg:function(a){!j(a)&&!Array.isArray(a)||h(0,3715,a)},checkMergeIntoObjectArg:function(a){(!j(a)||typeof a==="function")&&!Array.isArray(a)||h(0,3716,a)},checkMergeLevel:function(a){a<i||h(0,3717)},checkArrayStrategy:function(a){a==null||a in k.ArrayStrategies||h(0,3718)},ArrayStrategies:{Clobber:"Clobber",Concat:"Concat",IndexByIndex:"IndexByIndex"}};a=k;g["default"]=a}),98);
__d("ClientServiceWorkerMessage",[],(function(a,b,c,d,e,f){a=function(){function a(a,b,c){this.$1=a,this.$2=b,this.$3=c}var b=a.prototype;b.sendViaController=function(){if(!navigator.serviceWorker||!navigator.serviceWorker.controller)return;var a=new self.MessageChannel();this.$3&&(a.port1.onmessage=this.$3);navigator.serviceWorker.controller.postMessage({command:this.$1,data:this.$2},[a.port2])};return a}();f["default"]=a}),66);
__d("ServiceWorkerLoginAndLogout",["ClientServiceWorkerMessage"],(function(a,b,c,d,e,f){function g(a){new(b("ClientServiceWorkerMessage"))(a,null).sendViaController()}a={login:function(){g("login")},logout:function(){g("logout")}};c=a;f["default"]=c}),66);