// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define(["exports","../../../../../chunks/mat4","../../../../../geometry/support/buffer/BufferView","../../lib/Util"],function(u,I,D,E){function J(m,c,a,d){const b=a.typedBuffer;a=a.typedBufferStride;const f=m.length;d*=a;for(let e=0;e<f;++e){const h=2*m[e];b[d]=c[h];b[d+1]=c[h+1];d+=a}}function F(m,c,a,d,b){const f=a.typedBuffer;a=a.typedBufferStride;const e=m.length;d*=a;if(null==b||1===b)for(b=0;b<e;++b){var h=3*m[b];f[d]=c[h];f[d+1]=c[h+1];f[d+2]=c[h+2];d+=a}else for(h=0;h<e;++h){const l=3*m[h];
for(let r=0;r<b;++r)f[d]=c[l],f[d+1]=c[l+1],f[d+2]=c[l+2],d+=a}}function K(m,c,a,d,b=1){const f=a.typedBuffer;a=a.typedBufferStride;const e=m.length;d*=a;if(1===b)for(b=0;b<e;++b){var h=4*m[b];f[d]=c[h];f[d+1]=c[h+1];f[d+2]=c[h+2];f[d+3]=c[h+3];d+=a}else for(h=0;h<e;++h){const l=4*m[h];for(let r=0;r<b;++r)f[d]=c[l],f[d+1]=c[l+1],f[d+2]=c[l+2],f[d+3]=c[l+3],d+=a}}function L(m,c,a,d,b,f=1){if(a){var e=d.typedBuffer;d=d.typedBufferStride;var h=m.length,l=a[0],r=a[1],w=a[2],x=a[4],y=a[5],z=a[6],A=a[8],
B=a[9],C=a[10],q=a[12],p=a[13];a=a[14];b*=d;if(1===f)for(f=0;f<h;++f){var g=3*m[f],k=c[g],n=c[g+1];g=c[g+2];e[b]=l*k+x*n+A*g+q;e[b+1]=r*k+y*n+B*g+p;e[b+2]=w*k+z*n+C*g+a;b+=d}else for(k=0;k<h;++k){n=3*m[k];var t=c[n],v=c[n+1];const G=c[n+2];n=l*t+x*v+A*G+q;g=r*t+y*v+B*G+p;t=w*t+z*v+C*G+a;for(v=0;v<f;++v)e[b]=n,e[b+1]=g,e[b+2]=t,b+=d}}else F(m,c,d,b,f)}function M(m,c,a,d,b,f=1){if(a){var e=d.typedBuffer;d=d.typedBufferStride;var h=m.length,l=a[0],r=a[1],w=a[2],x=a[4],y=a[5],z=a[6],A=a[8],B=a[9],C=a[10];
a=!I.isOrthoNormal(a);b*=d;if(1===f)for(f=0;f<h;++f){var q=3*m[f],p=c[q],g=c[q+1],k=c[q+2];q=l*p+x*g+A*k;var n=r*p+y*g+B*k;p=w*p+z*g+C*k;a&&(g=q*q+n*n+p*p,.999999>g&&1E-6<g&&(g=1/Math.sqrt(g),q*=g,n*=g,p*=g));e[b+0]=q;e[b+1]=n;e[b+2]=p;b+=d}else for(q=0;q<h;++q){n=3*m[q];g=c[n];k=c[n+1];const t=c[n+2];n=l*g+x*k+A*t;p=r*g+y*k+B*t;g=w*g+z*k+C*t;a&&(k=n*n+p*p+g*g,.999999>k&&1E-6<k&&(k=1/Math.sqrt(k),n*=k,p*=k,g*=k));for(k=0;k<f;++k)e[b+0]=n,e[b+1]=p,e[b+2]=g,b+=d}}else F(m,c,d,b,f)}function N(m,c,a,
d,b,f=1){if(a){var e=d.typedBuffer;d=d.typedBufferStride;var h=m.length,l=a[0],r=a[1],w=a[2],x=a[4],y=a[5],z=a[6],A=a[8],B=a[9],C=a[10];a=!I.isOrthoNormal(a);b*=d;if(1===f)for(f=0;f<h;++f){var q=4*m[f],p=c[q],g=c[q+1],k=c[q+2];q=c[q+3];var n=l*p+x*g+A*k,t=r*p+y*g+B*k;p=w*p+z*g+C*k;a&&(g=n*n+t*t+p*p,.999999>g&&1E-6<g&&(g=1/Math.sqrt(g),n*=g,t*=g,p*=g));e[b+0]=n;e[b+1]=t;e[b+2]=p;e[b+3]=q;b+=d}else for(q=0;q<h;++q){n=4*m[q];g=c[n];k=c[n+1];const v=c[n+2];n=c[n+3];t=l*g+x*k+A*v;p=r*g+y*k+B*v;g=w*g+z*
k+C*v;a&&(k=t*t+p*p+g*g,.999999>k&&1E-6<k&&(k=1/Math.sqrt(k),t*=k,p*=k,g*=k));for(k=0;k<f;++k)e[b+0]=t,e[b+1]=p,e[b+2]=g,e[b+3]=n,b+=d}}else K(m,c,d,b,f)}function H(m,c,a,d,b,f=1){const e=d.typedBuffer;d=d.typedBufferStride;const h=m.length;b*=d;if(1===f)if(4===a)for(f=0;f<h;++f)a=4*m[f],e[b]=c[a],e[b+1]=c[a+1],e[b+2]=c[a+2],e[b+3]=c[a+3],b+=d;else{if(3===a)for(f=0;f<h;++f)a=3*m[f],e[b]=c[a],e[b+1]=c[a+1],e[b+2]=c[a+2],e[b+3]=255,b+=d}else if(4===a)for(a=0;a<h;++a){var l=4*m[a];for(var r=0;r<f;++r)e[b]=
c[l],e[b+1]=c[l+1],e[b+2]=c[l+2],e[b+3]=c[l+3],b+=d}else if(3===a)for(a=0;a<h;++a)for(l=3*m[a],r=0;r<f;++r)e[b]=c[l],e[b+1]=c[l+1],e[b+2]=c[l+2],e[b+3]=255,b+=d}u.writeBufferMat3f=function(m,c,a,d){const b=a.typedBuffer;a=a.typedBufferStride;const f=m.length;d*=a;for(let e=0;e<f;++e){const h=9*m[e];for(let l=0;9>l;++l)b[d+l]=c[h+l];d+=a}};u.writeBufferMat4f=function(m,c,a,d){const b=a.typedBuffer;a=a.typedBufferStride;const f=m.length;d*=a;for(let e=0;e<f;++e){const h=16*m[e];for(let l=0;16>l;++l)b[d+
l]=c[h+l];d+=a}};u.writeBufferVec2=J;u.writeBufferVec3=F;u.writeBufferVec4=K;u.writeColor=H;u.writeDefaultAttributes=function(m,c,a,d,b,f){for(const h of c.fieldNames){c=m.vertexAttributes.get(h);const l=m.indices.get(h);if(c&&l)switch(h){case "position":E.assert(3===c.size);var e=b.getField(h,D.BufferViewVec3f);e&&L(l,c.data,a,e,f);break;case "normal":E.assert(3===c.size);(e=b.getField(h,D.BufferViewVec3f))&&M(l,c.data,d,e,f);break;case "uv0":E.assert(2===c.size);(e=b.getField(h,D.BufferViewVec2f))&&
J(l,c.data,e,f);break;case "color":E.assert(3===c.size||4===c.size);(e=b.getField(h,D.BufferViewVec4u8))&&H(l,c.data,c.size,e,f);break;case "symbolColor":E.assert(3===c.size||4===c.size);(e=b.getField(h,D.BufferViewVec4u8))&&H(l,c.data,c.size,e,f);break;case "tangent":E.assert(4===c.size),(e=b.getField(h,D.BufferViewVec4f))&&N(l,c.data,d,e,f)}}};u.writeNormal=M;u.writePosition=L;u.writeTangent=N;Object.defineProperty(u,"__esModule",{value:!0})});