// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("require exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../core/shaderLibrary/Slice.glsl ../core/shaderLibrary/output/OutputHighlight.glsl ../core/shaderLibrary/shading/MultipassTerrainTest.glsl ../core/shaderLibrary/util/View.glsl ../core/shaderTechnique/ReloadableShaderModule ../core/shaderTechnique/ShaderTechnique ../core/shaderTechnique/ShaderTechniqueConfiguration ../lib/DefaultVertexAttributeLocations ../lib/OrderIndependentTransparency ../lib/Program ../lib/StencilUtils ../../../../chunks/ColorMaterial.glsl ../../../webgl/renderState".split(" "),
function(w,p,t,g,x,y,z,u,c,l,d,A,m,B,q,C,n){l=function(k){function h(){return k.apply(this,arguments)||this}t._inheritsLoose(h,k);var a=h.prototype;a.initializeProgram=function(e){var f=h.shader.get();const b=this.configuration;f=f.build({output:b.output,OITEnabled:0===b.transparencyPassType,attributeColor:b.vertexColors,slicePlaneEnabled:b.slicePlaneEnabled,sliceHighlightDisabled:!1,sliceEnabledForVertexPrograms:!1,multipassTerrainEnabled:b.multipassTerrainEnabled,cullAboveGround:b.cullAboveGround});
return new B.Program(e.rctx,f,A.Default3D)};a.bindPass=function(e,f){u.bindProjectionMatrix(this.program,f.camera.projectionMatrix);this.program.setUniform4fv("eColor",e.color);4===this.configuration.output&&y.bindOutputHighlight(this.program,f);(1===this.configuration.output||f.multipassTerrainEnabled)&&this.program.setUniform2fv("cameraNearFar",f.camera.nearFar);f.multipassTerrainEnabled&&(this.program.setUniform2fv("inverseViewport",f.inverseViewport),z.bindMultipassTerrainTexture(this.program,
f))};a.bindDraw=function(e){u.bindView(this.program,e);this.program.rebindTextures();x.bindSliceUniformsWithOrigin(this.program,this.configuration,e)};a.setPipelineState=function(e,f){const b=this.configuration,r=3===e,v=2===e;return n.makePipelineState({blending:0!==b.output&&7!==b.output||!b.transparent?null:r?m.blendingDefault:m.OITBlending(e),culling:n.cullingParams(b.cullFace),depthTest:{func:m.OITDepthTest(e)},depthWrite:r||v?b.writeDepth&&n.defaultDepthWriteParams:null,colorWrite:n.defaultColorWriteParams,
stencilWrite:b.sceneHasOcludees?q.stencilWriteMaskOn:null,stencilTest:b.sceneHasOcludees?f?q.stencilToolMaskBaseParams:q.stencilBaseAllZerosParams:null,polygonOffset:r||v?b.polygonOffset&&D:m.getOITPolygonOffset(b.enableOffset)})};a.initializePipeline=function(){this._occludeePipelineState=this.setPipelineState(this.configuration.transparencyPassType,!0);return this.setPipelineState(this.configuration.transparencyPassType,!1)};a.getPipelineState=function(e){return e?this._occludeePipelineState:this.pipeline};
return h}(l.ShaderTechnique);l.shader=new c.ReloadableShaderModule(C.ColorMaterialShader,()=>new Promise(function(k,h){w(["./ColorMaterial.glsl"],k,h)}));const D={factor:1,units:1};c=function(k){function h(){var a=k.apply(this,arguments)||this;a.output=0;a.cullFace=0;a.slicePlaneEnabled=!1;a.vertexColors=!1;a.transparent=!1;a.polygonOffset=!1;a.enableOffset=!0;a.writeDepth=!0;a.sceneHasOcludees=!1;a.transparencyPassType=3;a.multipassTerrainEnabled=!1;a.cullAboveGround=!1;return a}t._inheritsLoose(h,
k);return h}(d.ShaderTechniqueConfiguration);g.__decorate([d.parameter({count:8})],c.prototype,"output",void 0);g.__decorate([d.parameter({count:3})],c.prototype,"cullFace",void 0);g.__decorate([d.parameter()],c.prototype,"slicePlaneEnabled",void 0);g.__decorate([d.parameter()],c.prototype,"vertexColors",void 0);g.__decorate([d.parameter()],c.prototype,"transparent",void 0);g.__decorate([d.parameter()],c.prototype,"polygonOffset",void 0);g.__decorate([d.parameter()],c.prototype,"enableOffset",void 0);
g.__decorate([d.parameter()],c.prototype,"writeDepth",void 0);g.__decorate([d.parameter()],c.prototype,"sceneHasOcludees",void 0);g.__decorate([d.parameter({count:4})],c.prototype,"transparencyPassType",void 0);g.__decorate([d.parameter()],c.prototype,"multipassTerrainEnabled",void 0);g.__decorate([d.parameter()],c.prototype,"cullAboveGround",void 0);p.ColorMaterialTechnique=l;p.ColorMaterialTechniqueConfiguration=c;Object.defineProperty(p,"__esModule",{value:!0})});