// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../core/handleUtils ../../core/lang ../../core/mathUtils ../../core/maybe ../../core/screenUtils ../../chunks/vec3f64 ../../geometry/projection ../draw/support/drawUtils".split(" "),function(l,E,F,u,k,G,v,n,w){function x(c,d){let b=null,a=null;return f=>{if("cancel"===f.action)k.isSome(a)&&(a.execute({action:"cancel"}),a=b=null);else{var e={action:f.action,screenStart:f.start,screenEnd:f.screenPoint};"start"===f.action&&k.isNone(b)&&(b=new r,a=new r,d(c,b,a,f.pointerType,e));k.isSome(b)&&
b.execute(e);"end"===f.action&&k.isSome(b)&&(a=b=null)}}}function y(c,d){return c.events.on("drag",x(c,d))}function z(c,d){let b=null;return a=>{"start"===a.action&&(b=H(c,a.mapStart.spatialReference,d));if(k.isNone(b))return null;const f=a.mapEnd.x-a.mapStart.x,e=a.mapEnd.y-a.mapStart.y,g=a.mapEnd.z-a.mapStart.z;b.move(f,e,g);return{...a,translationX:f,translationY:e,translationZ:g}}}function A(c,d){return k.isNone(c)?null:c.spatialReference.equals(d)?c.clone():n.project(c,d)}function H(c,d,b){const a=
c.geometry;if(k.isNone(a))return null;if("mesh"===a.type)return I(c,a,d,b);const f=A(a,d),e=a.spatialReference;return k.isNone(f)?null:{move:(g,h,m)=>{g=w.move(f.clone(),g,h,m);g.spatialReference.equals(e)?c.geometry=g:c.geometry=n.project(g,e)}}}function I(c,d,b,a){if(k.isSome(d.transform))return J(c,d,d.transform,b);if(!d.spatialReference.equals(b))return null;let f=0,e=0,g=0;return{move:(h,m,p)=>{var q=h-f;const B=m-e,C=p-g;if(q||B||C)q=d.origin.clone().offset(q,B,C),d.centerAt(q,{geographic:1===
a}),c.notifyGeometryChanged(),f=h,e=m,g=p}}}function J(c,d,b,a){const f=b.getOriginPoint(d.spatialReference),e=A(f,a),g=d.spatialReference;return k.isNone(e)?null:{move:(h,m,p)=>{h=w.move(e.clone(),h,m,p);h.spatialReference.equals(g)?b.origin=v.fromValues(h.x,h.y,h.z):(h=n.project(h,g),k.isSome(h)&&(b.origin=v.fromValues(h.x,h.y,h.z)));c.notifyGeometryChanged()}}}function t(c,d){const b=new Map;for(const a of d)b.set(a,F.clone(c[a]));return a=>{b.forEach((f,e)=>{c[e]=f});return a}}function D(c){return k.isSome(c.geometry)&&
"mesh"===c.geometry.type?K(c,c.geometry):t(c,["geometry"])}function K(c,d){const b=k.isSome(d.transform)?d.transform.clone():null,a=d.vertexAttributes.clonePositional();return f=>{d.transform=b;d.vertexAttributes=a;c.notifyGeometryChanged();return f}}let r=function(){function c(){this.execute=()=>{}}c.prototype.next=function(d,b=new c){k.isSome(d)&&(this.execute=a=>{a=d(a);k.isSome(a)&&b.execute(a)});return b};return c}();l.EventPipeline=r;l.addMapDelta=function(){let c=0,d=0,b=0;return a=>{"start"===
a.action&&(c=a.mapStart.x,d=a.mapStart.y,b=a.mapStart.z);const f=a.mapEnd.x-c,e=a.mapEnd.y-d,g=a.mapEnd.z-b;c=a.mapEnd.x;d=a.mapEnd.y;b=a.mapEnd.z;return{...a,mapDeltaX:f,mapDeltaY:e,mapDeltaZ:g,mapDeltaSpatialReference:a.mapStart.spatialReference}}};l.addScreenDelta=function(){let c=0,d=0;return b=>{"start"===b.action&&(c=b.screenStart.x,d=b.screenStart.y);const a=b.screenEnd.x-c,f=b.screenEnd.y-d;c=b.screenEnd.x;d=b.screenEnd.y;return{...b,screenDeltaX:a,screenDeltaY:f}}};l.constrainToMapAxis=function(c,
d){const b=[c.x,c.y,c.z],a=[Math.cos(d),Math.sin(d)];c=Math.sqrt(a[0]*a[0]+a[1]*a[1]);if(0===c)return null;a[0]/=c;a[1]/=c;const f=e=>{const g=(e.x-b[0])*a[0]+(e.y-b[1])*a[1];e.x=b[0]+g*a[0];e.y=b[1]+g*a[1]};return e=>{f(e.mapStart);f(e.mapEnd);return e}};l.createDragEventPipelineCallback=x;l.createManipulatorDragEventPipeline=y;l.createManipulatorDragEventPipelineMany=function(c,d){const b=[];for(const a of c)b.push(y(a,d));return E.handlesGroup(b)};l.dragAtLocation=function(c,d){let b=null,a=0,
f=0;return e=>{"start"===e.action&&(b=c.toScreen(d),0>b.x||b.x>c.width||0>b.y||b.y>c.height?b=null:(a=e.screenStart.x-b.x,f=e.screenStart.y-b.y));if(null==b)return null;var g=u.clamp(e.screenEnd.x-a,0,c.width);const h=u.clamp(e.screenEnd.y-f,0,c.height);g=G.createScreenPoint(g,h);e.screenStart=b;e.screenEnd=g;return e}};l.dragGraphic=z;l.dragGraphicMany=function(c,d){const b=c.map(a=>k.unwrap(z(a,d))).filter(a=>k.isSome(a));return a=>{const f=a.mapEnd.x-a.mapStart.x,e=a.mapEnd.y-a.mapStart.y,g=a.mapEnd.z-
a.mapStart.z;b.forEach(h=>h(a));return{...a,translationX:f,translationY:e,translationZ:g}}};l.resetGraphic=D;l.resetGraphicMany=function(c){const d=c.map(b=>k.unwrap(D(b))).filter(b=>k.isSome(b));return b=>{d.forEach(a=>a(b));return b}};l.resetProperties=t;l.resetSymbol=function(c){return t(c,["symbol"])};l.screenToMap=function(c,d=null,b){let a=null;const f=k.isSome(d)&&!c.spatialReference.equals(d)?g=>k.isSome(g)?n.project(g,d):g:g=>g,e={exclude:[],...b};return g=>{"start"===g.action&&(a=f(c.toMap(g.screenStart,
e)));if(k.isNone(a))return null;const h=f(c.toMap(g.screenEnd,e));return k.isSome(h)?{...g,mapStart:a,mapEnd:h}:null}};Object.defineProperty(l,"__esModule",{value:!0})});