// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Evented ../../core/maybe ../../core/promiseUtils ../../core/screenUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/Logger ../../core/jsonMap ../../core/accessorSupport/decorators/subclass ../../layers/GraphicsLayer ../../layers/graphics/dehydratedFeatures ../2d/interactive/SnappingVisualizer2D ../interactive/coordinateHelper ../interactive/editGeometry/EditGeometry ../interactive/editGeometry/EditGeometryHelper ../interactive/snapping/SnappingContext".split(" "),
function(m,g,e,d,u,q,h,E,F,G,H,v,w,x,y,z,r,A,B){var n;e=n=function(t){function l(a){var c;var b=t.call(this,a)||this;b._hasZ=null;b._cursorScreenPoint=null;b._snappingTask=null;b._stagedVertex=null;b._stagedVertexUnsnapped=null;b._lastVertexUnsnapped=null;b._nativeEventHistory={undoStack:[],redoStack:[]};b.interactiveUndoDisabled=!1;b.history=[];b.redoHistory=[];b.snapToScene=!1;b.view=null;b.elevationInfo=null;b.defaultZ=0;b._coordinateHelper=z.createCoordinateHelper(a.hasZ,!1,a.view.spatialReference,
"local");b._snappingManager=a.snappingManager;b._editGeometry=new A.EditGeometryHelper(new r.EditGeometry(b._coordinateHelper),null!=(c=a.editGeometryType)?c:"polygon");b._snappingGraphicsLayer=new w({id:n.SNAPPING_GRAPHICS_LAYER_ID,listMode:"hide",internal:!0});b._snappingContext=new B.SnappingContext({geometry:b._editGeometry,elevationInfo:{mode:"on-the-ground",offset:0},pointer:"mouse",visualizer:new y.SnappingVisualizer2D(b._snappingGraphicsLayer)});b._activeComponent=new r.Component(b._editGeometry.editGeometry);
b._editGeometry.editGeometry.components.push(b._activeComponent);return b}m._inheritsLoose(l,t);var f=l.prototype;f.initialize=function(){"2d"===this.view.type&&this.view.map.layers.add(this._snappingGraphicsLayer)};f.destroy=function(){this._snappingTask=d.abortMaybe(this._snappingTask);this.view.map.layers.remove(this._snappingGraphicsLayer);this._snappingGraphicsLayer.destroy();d.isSome(this._snappingManager)&&this._snappingManager.doneSnapping();this._editGeometry.destroy()};f.canUndo=function(){return this._editGeometry.editGeometry.canUndo};
f.canRedo=function(){return this._editGeometry.editGeometry.canRedo};f.undo=function(){this.canUndo()&&this._editGeometry.undo()};f.redo=function(){this.canRedo()&&this._editGeometry.redo()};f.getCoordsFromScreenPoint=function(a){a=this.screenToMap(a);return d.isSome(a)?a.hasZ?[a.x,a.y,a.z]:[a.x,a.y]:null};f.getCoordsAndPointFromScreenPoint=function(a){a=this.screenToMap(a);return d.isSome(a)?a.hasZ?{vertex:[a.x,a.y,a.z],mapPoint:a}:{vertex:[a.x,a.y],mapPoint:a}:null};f._pushCursorVertex=function(a){var c=
this;const b=x.makeDehydratedPoint(a[0],a[1],null,this.view.spatialReference);this._stagedVertexUnsnapped=b;d.isNone(this._snappingManager)?this._stagedVertex=b:(this._stagedVertex=this._snappingManager.update(b,this._snappingContext),this._snappingTask=u.createTask(function(){var p=m._asyncToGenerator(function*(k){return d.isSome(c._snappingManager)?(k=yield c._snappingManager.snap(b,c._snappingContext,k),k.valid&&(c._stagedVertex=k.apply(),c.notifyChange("vertices")),k):null});return function(k){return p.apply(this,
arguments)}}()))};f._popCursorVertex=function(){this._stagedVertexUnsnapped=this._stagedVertex=null;this.notifyChange("vertices")};f.getGeometryZValue=function(){return this.defaultZ};f.screenToMap=function(a){var c=null;"3d"===this.view.type?this.hasZ?(c=d.unwrapOr(this.elevationInfo,C),c=this.view.sceneIntersectionHelper.intersectElevationFromScreen(q.createScreenPointArray(a.x,a.y),c,this.getGeometryZValue())):(c=d.unwrapOr(this.elevationInfo,D),c=this.view.sceneIntersectionHelper.intersectElevationFromScreen(q.createScreenPointArray(a.x,
a.y),c,0),d.isSome(c)&&(c.z=void 0)):(c=this.view.toMap(a),d.isSome(c)&&(c.z=this.hasZ?this.getGeometryZValue():void 0));return c};f._isDuplicateOfLastVertex=function(a){const c=this._editGeometry.editGeometry.components[0].getLastVertex();if(d.isSome(c)&&a[0]===c[0]&&a[1]===c[1])return!0;const {x:b,y:p}=this._coordinateHelper.createDehydratedPoint(a);return d.isSome(this._lastVertexUnsnapped)&&b===this._lastVertexUnsnapped.x&&p===this._lastVertexUnsnapped.y?!0:!1};f._vertexAddHandler=function(a){const c=
d.isSome(this._stagedVertex)?this._coordinateHelper.pointToArray(this._stagedVertex):this.getCoordsFromScreenPoint(this._cursorScreenPoint);d.isSome(c)&&this._addVertex(c,a.native)};f._drawCompleteHandler=function(a){this._completeDrawing(a.native)};m._createClass(l,[{key:"_committedVertices",get:function(){return this._editGeometry.editGeometry.components[0].vertices.map(a=>a.pos)}},{key:"vertices",get:function(){return d.isSome(this._stagedVertex)?[...this._committedVertices,this._coordinateHelper.pointToArray(this._stagedVertex)]:
this._committedVertices}},{key:"hasZ",get:function(){return d.isSome(this._hasZ)?this._hasZ:"3d"===this.view.type},set:function(a){this._hasZ=a;this.notifyChange("hasZ")}}]);return l}(e.EventedAccessor);e.SNAPPING_GRAPHICS_LAYER_ID="DrawAction-snapping-graphics-layer";g.__decorate([h.property({readOnly:!0})],e.prototype,"vertices",null);g.__decorate([h.property({type:Boolean,nonNullable:!0})],e.prototype,"interactiveUndoDisabled",void 0);g.__decorate([h.property({readOnly:!0})],e.prototype,"history",
void 0);g.__decorate([h.property({readOnly:!0})],e.prototype,"redoHistory",void 0);g.__decorate([h.property()],e.prototype,"snapToScene",void 0);g.__decorate([h.property()],e.prototype,"view",void 0);g.__decorate([h.property()],e.prototype,"elevationInfo",void 0);g.__decorate([h.property({nonNullable:!0})],e.prototype,"defaultZ",void 0);g.__decorate([h.property()],e.prototype,"hasZ",null);e=n=g.__decorate([v.subclass("esri.views.draw.DrawAction")],e);const C={mode:"absolute-height",offset:0},D={mode:"on-the-ground",
offset:0};return e});