// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../core/Evented ./EditGeometry ./operations/AppendVertex ./operations/UpdateVertices ./operations/RemoveVertices ./operations/SplitEdge ./operations/SetVertexPosition ./operations/CloseComponent ./operations/MoveVertex ./operations/OffsetEdgeVertex ./operations/RotateVertex ./operations/ScaleVertex ./operations/UndoGroup".split(" "),function(f,m,l,h,p,q,r,t,B,C,u,v,w,x,y){l=function(n){function g(a,c){var b=n.call(this)||this;b.editGeometry=
a;b.type=c;b._geometry=null;b._dirty=!0;b._listener=b.editGeometry.on("change",d=>{b._dirty=!0;d.addedVertices&&b.emit("vertex-add",{type:"vertex-add",vertices:d.addedVertices,operation:d.operation});d.removedVertices&&b.emit("vertex-remove",{type:"vertex-remove",vertices:d.removedVertices,operation:d.operation});d.updatedVertices&&b.emit("vertex-update",{type:"vertex-update",vertices:d.updatedVertices,operation:d.operation})});return b}m._inheritsLoose(g,n);var e=g.prototype;e.destroy=function(){this._listener.remove()};
e.splitEdge=function(a,c){return this.editGeometry.apply(new t.SplitEdge(this.editGeometry,a,c))};e.updateVertices=function(a,c,b=1){return this.editGeometry.apply(new q.UpdateVertices(this.editGeometry,a,c),b)};e.moveVertices=function(a,c,b,d,k=1){return this.updateVertices(a,new u.MoveVertex(this.editGeometry.coordinateHelper,c,b,d),k)};e.scaleVertices=function(a,c,b,d,k,z=1,A=0){return this.updateVertices(a,new x.ScaleVertex(this.editGeometry.coordinateHelper,c,b,d,k,A),z)};e.rotateVertices=function(a,
c,b,d=1,k=0){return this.updateVertices(a,new w.RotateVertex(this.editGeometry.coordinateHelper,c,b,k),d)};e.removeVertices=function(a){return this.editGeometry.apply(new r.RemoveVertices(this.editGeometry,a,this._minNumVerticesPerType))};e.appendVertex=function(a){return 0===this.editGeometry.components.length?null:this.editGeometry.apply(new p.AppendVertex(this.editGeometry,this.editGeometry.components[0],a))};e.offsetEdge=function(a,c,b,d=1){return this.updateVertices([c.left,c.right],new v.OffsetEdgeVertex(this.editGeometry.coordinateHelper,
a,c,b),d)};e.canRemoveVertex=function(){return this.editGeometry.components[0].vertices.length>this._minNumVerticesPerType};e.createUndoGroup=function(){const a=new y.UndoGroup;this.editGeometry.apply(a);return{remove(){return a.close()}}};e.undo=function(){return this.editGeometry.undo()};e.redo=function(){return this.editGeometry.redo()};g.fromGeometry=function(a,c){return new g(h.EditGeometry.fromGeometry(a,c),a.type)};m._createClass(g,[{key:"canUndo",get:function(){return this.editGeometry.canUndo}},
{key:"canRedo",get:function(){return this.editGeometry.canRedo}},{key:"geometry",get:function(){if(this._dirty){switch(this.type){case "point":this._geometry=this.editGeometry.toPoint();break;case "polyline":this._geometry=this.editGeometry.toPolyline();break;case "polygon":this._geometry=this.editGeometry.toPolygon()}this._dirty=!1}return this._geometry}},{key:"_minNumVerticesPerType",get:function(){switch(this.type){case "point":return 1;case "polyline":return 2;case "polygon":return 3;default:return 0}}}]);
return g}(l);f.Component=h.Component;f.Edge=h.Edge;f.EditGeometry=h.EditGeometry;f.Vertex=h.Vertex;f.EditGeometryHelper=l;Object.defineProperty(f,"__esModule",{value:!0})});