// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../../../core/compilerUtils ../../../../core/maybe ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3f64 ../../../../geometry/projection ../../../../layers/graphics/dehydratedFeatureUtils ./graphicUtils ../../support/ElevationProvider".split(" "),function(m,A,r,B,C,D,x,E,F,u){function z(a,c,b,d,e){const f=(E.isDehydratedPoint(a)?a.z:u.isSamplePosition(a)?a.array[a.offset+2]:a[2])||0;switch(b.mode){case "on-the-ground":return b=r.unwrapOr(u.getElevationAtPoint(c,
a,"ground"),0),e&&(e.verticalDistanceToGround=0,e.sampledElevation=b),b;case "relative-to-ground":return a=r.unwrapOr(u.getElevationAtPoint(c,a,"ground"),0),b=b.geometryZWithOffset(f,d),e&&(e.verticalDistanceToGround=b,e.sampledElevation=a),b+a;case "relative-to-scene":return a=r.unwrapOr(u.getElevationAtPoint(c,a,"scene"),0),b=b.geometryZWithOffset(f,d),e&&(e.verticalDistanceToGround=b,e.sampledElevation=a),b+a;case "absolute-height":return b=b.geometryZWithOffset(f,d),e&&(d=r.unwrapOr(u.getElevationAtPoint(c,
a,"ground"),0),e.verticalDistanceToGround=b-d,e.sampledElevation=d),b;default:return A.neverReached(b.mode),0}}m.SymbolUpdateType=void 0;(function(a){a[a.NONE=0]="NONE";a[a.UPDATE=1]="UPDATE";a[a.RECREATE=2]="RECREATE"})(m.SymbolUpdateType||(m.SymbolUpdateType={}));const G={"absolute-height":{applyElevationAlignmentBuffer:function(a,c,b,d,e,f,g,h){f=h.calculateOffsetRenderUnits(g);h=h.featureExpressionInfoContext;c*=3;d*=3;for(g=0;g<e;++g){const k=a[c+1],n=a[c+2];b[d+0]=a[c+0];b[d+1]=k;b[d+2]=null==
h?n+f:f;c+=3;d+=3}return 0},requiresAlignment:function(a){const c=a.featureExpressionInfoContext;return 0!==a.meterUnitOffset||null!=c}},"on-the-ground":{applyElevationAlignmentBuffer:function(a,c,b,d,e,f){let g=0;const h=f.spatialReference;c*=3;d*=3;for(let k=0;k<e;++k){const n=a[c+0],l=a[c+1],p=r.unwrapOr(f.getElevation(n,l,a[c+2],h,"ground"),0);g+=p;b[d+0]=n;b[d+1]=l;b[d+2]=p;c+=3;d+=3}return g/e},requiresAlignment:()=>!0},"relative-to-ground":{applyElevationAlignmentBuffer:function(a,c,b,d,e,
f,g,h){let k=0;g=h.calculateOffsetRenderUnits(g);h=h.featureExpressionInfoContext;const n=f.spatialReference;c*=3;d*=3;for(let l=0;l<e;++l){const p=a[c+0],q=a[c+1],v=a[c+2],t=r.unwrapOr(f.getElevation(p,q,v,n,"ground"),0);k+=t;b[d+0]=p;b[d+1]=q;b[d+2]=null==h?v+t+g:t+g;c+=3;d+=3}return k/e},requiresAlignment:()=>!0},"relative-to-scene":{applyElevationAlignmentBuffer:function(a,c,b,d,e,f,g,h){let k=0;g=h.calculateOffsetRenderUnits(g);h=h.featureExpressionInfoContext;const n=f.spatialReference;c*=3;
d*=3;for(let l=0;l<e;++l){const p=a[c+0],q=a[c+1],v=a[c+2],t=r.unwrapOr(f.getElevation(p,q,v,n,"scene"),0);k+=t;b[d+0]=p;b[d+1]=q;b[d+2]=null==h?v+t+g:t+g;c+=3;d+=3}return k/e},requiresAlignment:()=>!0}},H=C.create(),y={verticalDistanceToGround:0,sampledElevation:0},w=D.create();m.applyElevationAlignmentForHUD=function(a,c,b,d,e){b=z(c,b,e,d,y);F.updateVertexAttributeAuxpos1w(a,y.verticalDistanceToGround);e=y.sampledElevation;const f=B.copy(H,a.transformation);w[0]=c.x;w[1]=c.y;w[2]=b;x.computeLinearTransformation(c.spatialReference,
w,f,d.spatialReference)?a.transformation=f:console.warn("Could not locate symbol object properly, it might be misplaced");return e};m.applyPerVertexElevationAlignment=function(a,c,b,d,e,f,g,h,k,n,l){const p=G[l.mode];let q=0;if(x.projectBuffer(a,c,b,d,k.spatialReference,e,h)&&(p.requiresAlignment(l)?(q=p.applyElevationAlignmentBuffer(d,e,f,g,h,k,n,l),a=f,e=g):a=d,x.projectBuffer(a,k.spatialReference,e,f,n.spatialReference,g,h)))return q};m.elevationModeChangeUpdateType=function(a,c,b){return null==
c||null==b?a.definedChanged:"on-the-ground"===c&&"on-the-ground"===b?a.staysOnTheGround:c===b||"on-the-ground"!==c&&"on-the-ground"!==b?m.SymbolUpdateType.UPDATE:a.onTheGroundChanged};m.evaluateElevationAlignmentAtPoint=z;m.needsElevationUpdates2D=function(a){return"relative-to-ground"===a||"relative-to-scene"===a};m.needsElevationUpdates3D=function(a){return"absolute-height"!==a};Object.defineProperty(m,"__esModule",{value:!0})});