// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../geometry ../../../core/arrayUtils ../../../core/Error ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass ../../../geometry/support/quantizationUtils ../../../geometry/support/spatialReferenceUtils ../../../layers/support/arcgisLayerUrl ../../../layers/support/fieldUtils ../../../rest/support/GenerateRendererParameters ../../../rest/support/QuantizationParameters ../../../rest/support/StatisticDefinition ../../../rest/support/UniqueValueDefinition ../../statistics/support/predominanceUtils ../../statistics/support/utils ../../statistics/support/WorkerClient ../utils ./LayerAdapter ./support/utils ../../../tasks/GenerateRendererTask ../../../geometry/Point".split(" "),
function(y,K,E,L,w,R,F,z,S,T,da,ea,fa,U,M,N,V,D,G,W,H,X,I,u,Y,O,Z,n,aa,ba){function P(A){return J.apply(this,arguments)}function J(){J=y._asyncToGenerator(function*(A){if(!A)throw new w("feature-layer-adapter:insufficient-data","layerView is required to fetch the features");const B=z.createAbortController();A=S.whenFalseOnce(A,"updating",B.signal);yield z.timeout(A,5E3,B).catch(m=>{ca.warn("LayerView is taking too long to update. Aborting fetch from layerView.");throw m;})});return J.apply(this,arguments)}
const ca=R.getLogger("esri.smartMapping.support.adapters.FeatureLayerAdapter");E=function(A){function B(a){return A.call(this,a)||this}y._inheritsLoose(B,A);var m=B.prototype;m.destroy=function(){var a;this._hasLocalSource=null;null==(a=this.workerClient)?void 0:a.destroy()};m._isStatsSupportedOnService=function(){const a=this.layer;return!a.get("capabilities.query.supportsStatistics")||"multipatch"===this.geometryType&&!V.isHostedAgolService(a.url)&&10.5>a.version?Promise.reject(new w("feature-layer-adapter:not-supported",
"Layer does not support statistics query")):Promise.resolve()};m._fetchFeaturesFromMemory=function(){var a=y._asyncToGenerator(function*(b,c,d,e){const h=this.layer;e="json"===e;if(this._hasLocalSource)return b=yield h.queryFeatures(c),e?n.ensureFeaturesJSON(b.features):b.features;yield P(b);if(e&&"queryFeaturesJSON"in b&&b.queryFeaturesJSON)return{features:e}=yield b.queryFeaturesJSON(c,{signal:d}),e;b=yield b.queryFeatures(c,{signal:d});return e?n.ensureFeaturesJSON(b.features):b.features});return function(b,
c,d,e){return a.apply(this,arguments)}}();m._fetchFeaturesFromService=function(a,b){return this.layer.queryFeatures(a,{signal:b}).then(c=>c.features)};m._fetchFeaturesJSONFromService=function(a,b){return this._fetchFeaturesFromService(a,b).then(n.ensureFeaturesJSON)};m._fetchFeaturesForStats=function(a,b){return O.getFieldsList({field:a.field,normalizationField:a.normalizationField,valueExpression:a.valueExpression}).then(c=>this.getSampleFeatures({sampleSize:-1,view:a.view,returnGeometry:a.returnGeometry,
requiredFields:c,signal:a.signal},b))};m._summaryStatsFromGenRend=function(a){const b=a.normalizationType,c=a.normalizationField;return this.classBreaks({field:a.field,numClasses:5,classificationMethod:"standard-deviation",standardDeviationInterval:.25,normalizationType:b,normalizationField:"field"===b?c:void 0,minValue:a.minValue,maxValue:a.maxValue,signal:a.signal}).then(d=>{let e,h;d.classBreakInfos.some(f=>{f.hasAvg&&(e=f);return!!e});if(e){var g=e.maxValue-e.minValue;h=e.minValue+g/2;g*=4}return n.processSummaryStatisticsResult({min:d.minValue,
max:d.maxValue,avg:h,stddev:g})})};m._getSummaryStatsQuery=function(a,b){const {field:c,normalizationType:d,normalizationField:e,normalizationTotal:h,minValue:g,maxValue:f}=a;b=this.supportsSQLExpression&&b?n.msSinceUnixEpochSQL(this,c):a.sqlExpression;var k=n.getFieldExpr({field:c,normalizationType:d,normalizationField:e,normalizationTotal:h,layer:this});const l=b||k;k=l?u.getRangeExpr(l,g,f):null;var p=u.getSQLFilterForNormalization({field:c,normalizationField:e,normalizationType:d});a=u.mergeWhereClauses(a.sqlWhere,
p);a=u.mergeWhereClauses(a,k);const q=u.isNullCountSupported({normalizationField:e,normalizationType:d,sqlExpression:b,supportsSQLExpression:this.supportsSQLExpression,minValue:g,maxValue:f}),r=D.isStringField(this.getField(c));k=n.statisticTypes.filter(t=>"nullcount"===t?q:r?"count"===t:!0);p=this.layer.createQuery();p.where=u.mergeWhereClauses(p.where,a);p.sqlFormat=b?"standard":null;p.outStatistics=k.map(t=>{const x=new H;let v=null,C=null,Q=`${t}_value`;"variance"===t?(v="var",C=l):"nullcount"===
t?(v="count",C=this.layer.objectIdField,Q="totalcount_value"):(v=t,C=l);x.statisticType=v;x.onStatisticField=C;x.outStatisticFieldName=Q;return x});return p};m._summaryStatsFromServiceQuery=function(){var a=y._asyncToGenerator(function*(b,c){yield this._isStatsSupportedOnService();"percent-of-total"===b.normalizationType&&(b.normalizationTotal=yield this._getNormalizationTotal(b.field,b.normalizationType));const d=this._getSummaryStatsQuery(b,c);b=yield this.layer.queryFeatures(d,{signal:b.signal});
c=n.getSummaryStatisticsFromFeatureSet(b,c);return n.processSummaryStatisticsResult(c)});return function(b,c){return a.apply(this,arguments)}}();m._summaryStatsFromClientQuery=function(){var a=y._asyncToGenerator(function*(b,c){const d=this._getSummaryStatsQuery(b,c);b=yield this.layer.queryFeatures(d,{signal:b.signal});c=n.getSummaryStatisticsFromFeatureSet(b,c);return n.processSummaryStatisticsResult(c)});return function(b,c){return a.apply(this,arguments)}}();m._summaryStatsFromMemory=function(){var a=
y._asyncToGenerator(function*(b,c){const {view:d,field:e,signal:h}=b,{featuresJSON:g,layerView:f,query:k}=yield this._processStatsFromMemoryParams(b);var l={field:e,valueExpression:b.valueExpression,normalizationType:b.normalizationType,normalizationField:b.normalizationField,normalizationTotal:b.normalizationTotal,minValue:b.minValue,maxValue:b.maxValue};if(b.valueExpression&&d&&g){var p;l.fieldType=null==c?void 0:c.type;l.viewInfoParams={viewingMode:"2d"===d.type?"map":d.viewingMode,scale:d.scale,
spatialReference:null==(p=d.spatialReference)?void 0:p.toJSON()}}if("percent-of-total"===b.normalizationType&&null==b.normalizationTotal){b=(!g&&f&&"querySummaryStatistics"in f&&f.querySummaryStatistics?yield f.querySummaryStatistics(k,{field:e},{signal:h}):yield this.workerClient.summaryStatistics({field:e},g)).sum;if(null==b)throw new w("feature-layer-adapter:invalid","invalid normalizationTotal");l.normalizationTotal=b}l=!g&&f&&"querySummaryStatistics"in f&&f.querySummaryStatistics?yield f.querySummaryStatistics(k,
l,{signal:h}):yield this.workerClient.summaryStatistics(l,g);return n.processSummaryStatisticsResult(l)});return function(b,c){return a.apply(this,arguments)}}();m._processStatsFromMemoryParams=function(){var a=y._asyncToGenerator(function*(b){if(b.features)return{featuresJSON:n.ensureFeaturesJSON(b.features)};if(!b.view)throw new w("feature-layer-adapter:insufficient-data","View is required to fetch the features");const {view:c,field:d,normalizationField:e,valueExpression:h,signal:g}=b;b=yield c.whenLayerView(this.layer);
let f="querySummaryStatistics"in b&&"function"===typeof b.querySummaryStatistics,k=null,l=null;if(f)try{yield P(b);const q=yield O.getFieldsList({field:d,normalizationField:e,valueExpression:h});(yield n.getMissingFields(this,q,b)).length?f=!1:(k=this.layer.createQuery(),k.outFields=q,k.returnGeometry=!1);b.suspended&&(f=!1)}catch{f=!1}if(!f){var p;l=yield this._fetchFeaturesForStats({field:d,valueExpression:h,normalizationField:e,view:c,signal:g},"json");if(null==(p=l)||!p.length)throw new w("feature-layer-adapter:insufficient-data",
"No features are available to calculate statistics");}return{layerView:b,query:k,featuresJSON:l}});return function(b){return a.apply(this,arguments)}}();m._uvFromGenRenderer=function(a,b){const c=a.field,d=new X;d.attributeField=c;const e=new G;e.classificationDefinition=d;return this.generateRenderer(e,a.signal).then(h=>{const g={},f=this.getField(c);h.uniqueValues.forEach(k=>{let l=k.value;if(null==l||""===l||"string"===typeof l&&(""===l.trim()||"\x3cnull\x3e"===l.toLowerCase()))l=null;null==g[l]?
g[l]={count:k.count,data:D.isNumericField(f)&&l?Number(l):l}:g[l].count+=k.count});return{count:g}}).then(h=>n.createUVResult(h,b,a.returnAllCodedValues))};m._getUVQuery=function(a){const b=a.field,c=a.sqlExpression;var d="countOF"+(b||"Expr");const e=new H;e.statisticType="count";e.onStatisticField=c?"1":b;e.outStatisticFieldName=d;d=this.layer.createQuery();d.where=u.mergeWhereClauses(d.where,a.sqlWhere);d.sqlFormat=c?"standard":null;d.outStatistics=[e];d.groupByFieldsForStatistics=[b||c];return d};
m._uvFromServiceQuery=function(a,b){return this._isStatsSupportedOnService().then(()=>this.layer.queryFeatures(this._getUVQuery(a),{signal:a.signal})).then(c=>n.getUniqueValuesFromFeatureSet(c,this,a.field,null,a.signal)).then(c=>n.createUVResult(c,b,a.returnAllCodedValues))};m._uvFromClientQuery=function(){var a=y._asyncToGenerator(function*(b,c){var {signal:d}=b,e=this._getUVQuery(b);e=yield this.layer.queryFeatures(e,{signal:d});d=yield n.getUniqueValuesFromFeatureSet(e,this,b.field,null,d);return n.createUVResult(d,
c,b.returnAllCodedValues)});return function(b,c){return a.apply(this,arguments)}}();m._uvFromMemory=function(){var a=y._asyncToGenerator(function*(b,c){const {field:d,valueExpression:e,view:h,signal:g}=b;var f={field:d,valueExpression:e,view:h,signal:g};f=b.features?b.features:yield this._fetchFeaturesForStats(f);return n.calculateUniqueValuesFromMemory(b,f,c)});return function(b,c){return a.apply(this,arguments)}}();m._calcBinsSQL=function(a,b,c){const d=[],e=b.length;b.forEach((h,g)=>{const [f,
k]=h;h=null;h=0!==g||c?g!==e-1||c?u.mergeWhereClauses(`${a} >= ${f}`,`${a} ${g===e-1?" \x3c\x3d ":" \x3c "} ${k}`):`${a} >= ${f}`:`${a} < ${k}`;d.push("WHEN ("+h+") THEN "+(g+1))});return["CASE",d.join(" "),"ELSE 0 END"].join(" ")};m._getNormalizationTotal=function(a,b,c){return a&&"percent-of-total"===b?this.summaryStatistics({field:a,signal:c}).then(d=>d.sum):Promise.resolve(null)};m._getQueryParamsForExpr=function(a,b){const c=a.signal;if(!a.valueExpression&&!a.sqlExpression){const {field:e,normalizationType:h,
normalizationField:g}=a;var d=e?this.getField(e):null;d=D.isDateField(d);b={field:e,normalizationType:h,normalizationField:g,normalizationTotal:b,layer:this};return{sqlExpression:d?n.msSinceUnixEpochSQL(this,e):n.getFieldExpr(b),sqlWhere:d?null:a.sqlWhere||u.getSQLFilterForNormalization({field:e,normalizationType:h,normalizationField:g}),signal:c}}return{valueExpression:a.valueExpression,sqlExpression:a.sqlExpression,sqlWhere:a.sqlWhere,signal:c}};m._getDataRange=function(a,b,c){return null!=b&&null!=
c?Promise.resolve({min:b,max:c}):this.summaryStatistics(a).then(d=>({min:d.min,max:d.max}))};m._histogramForExpr=function(a){return this._getNormalizationTotal(a.field,a.normalizationType,a.signal).then(b=>{const c=this._getQueryParamsForExpr(a,b);return this._getDataRange(c,a.minValue,a.maxValue).then(d=>{const {min:e,max:h}=d,g=a.numBins||10;d=n.getEqualIntervalBins(e,h,g);d=this._calcBinsSQL(c.sqlExpression,d,null!=a.minValue&&null!=a.maxValue);const f=new H({statisticType:"count",outStatisticFieldName:"countOFExpr",
onStatisticField:"1"}),k=this.layer.createQuery();k.where=u.mergeWhereClauses(k.where,c.sqlWhere);k.sqlFormat="standard";k.outStatistics=[f];k.groupByFieldsForStatistics=[d];k.orderByFields=[d];return this._isStatsSupportedOnService().then(()=>this.layer.queryFeatures(k,{signal:c.signal})).then(l=>n.getHistogramFromFeatureSet(l,e,h,g,b))})})};m._histogramForField=function(a){let b=null;b=null!=a.minValue&&null!=a.maxValue?Promise.resolve({min:a.minValue,max:a.maxValue}):this.summaryStatistics(a).then(c=>
{if(!c.count)throw new w("feature-layer-adapter:insufficient-data","Either the layer has no features or none of the features have data for the field");return{min:c.min,max:c.max}});return b.then(c=>this._getBins({min:c.min,max:c.max},a.field,a.numBins,a.signal))};m._getBins=function(a,b,c=10,d){const {min:e,max:h,normTotal:g,excludeZerosExpr:f}=a,k=a.intervals||n.getEqualIntervalBins(e,h,c);return this._queryBins(k,a.sqlExpr||b,f,d).then(l=>({bins:l.map((p,q)=>({minValue:k[q][0],maxValue:k[q][1],
count:p.value})),minValue:e,maxValue:h,normalizationTotal:g}))};m._queryBins=function(a,b,c,d){const e=[],h=a.length;for(let g=0;g<h;g++){const f=u.mergeWhereClauses(c,u.mergeWhereClauses(b+" \x3e\x3d "+a[g][0],null!==a[g][1]?b+(g===h-1?" \x3c\x3d ":" \x3c ")+a[g][1]:""));e.push(f)}return z.eachAlways(e.map(g=>this.queryFeatureCount(g,d)))};m._binParamsFromGenRend=function(a,b){const {field:c,normalizationType:d,normalizationField:e,signal:h}=a,g=u.getSQLFilterForNormalization({field:c,normalizationType:d,
normalizationField:e});a=new G({classificationDefinition:n.createCBDefn({field:c,normalizationType:d,normalizationField:e,classificationMethod:a.classificationMethod,standardDeviationInterval:a.standardDeviationInterval,breakCount:a.numBins||10}),where:u.mergeWhereClauses(g,b)});return this.generateRenderer(a,h).then(f=>{const {normalizationTotal:k,classBreaks:l}=f;return n.generateBinParams({field:c,normalizationType:d,normalizationField:e,normalizationTotal:k,classBreaks:l,where:g,layer:this})})};
m._histogramFromMemory=function(a){const {field:b,normalizationField:c,normalizationType:d,valueExpression:e,classificationMethod:h,minValue:g,maxValue:f,view:k,signal:l}=a,p={field:b,valueExpression:e,normalizationField:c,view:k,signal:l};return(a.features?Promise.resolve(a.features):this._fetchFeaturesForStats(p)).then(q=>{if(!q||!q.length)throw new w("feature-layer-adapter:insufficient-data","No features are available to calculate histogram");var r=null!=g&&null!=f;let t=null;h&&"equal-interval"!==
h||d?(r={...a},r.features=q,t=this._getBinParamsFromMemory(r)):t=r?Promise.resolve({min:g,max:f,source:"parameters"}):this.summaryStatistics({field:b,valueExpression:e,features:q,view:k,signal:l}).then(x=>x.count?{min:x.min,max:x.max}:Promise.reject(new w("feature-layer-adapter:insufficient-data","No features are available to calculate histogram")));return t.then(x=>n.calculateHistogramFromMemory(a,x,q))})};m._getBinParamsFromMemory=function(){var a=y._asyncToGenerator(function*(b){const {field:c,
valueExpression:d,classificationMethod:e,standardDeviationInterval:h,normalizationType:g,normalizationField:f,minValue:k,maxValue:l,features:p,view:q,signal:r}=b;return this._classBreaksFromMemory({field:c,valueExpression:d,normalizationType:g,normalizationField:f,classificationMethod:e,standardDeviationInterval:h,minValue:k,maxValue:l,numClasses:b.numBins,features:p,view:q,signal:r}).then(t=>{const x=t.normalizationTotal;t=t.classBreakInfos;const v=u.getSQLFilterForNormalization({field:c,normalizationType:g,
normalizationField:f});return n.generateBinParams({field:c,normalizationType:g,normalizationField:f,normalizationTotal:x,classBreaks:t,where:v,layer:this})})});return function(b){return a.apply(this,arguments)}}();m._classBreaksFromGenRend=function(a){const {field:b,normalizationType:c,normalizationField:d,normalizationTotal:e,signal:h}=a,g=u.getSQLFilterForNormalization({field:b,normalizationType:c,normalizationField:d});var f=n.getFieldExpr({field:b,normalizationType:c,normalizationField:d,normalizationTotal:e,
layer:this});f=u.getRangeExpr(f,a.minValue,a.maxValue);const k=n.createCBDefn({field:b,normalizationType:c,normalizationField:d,classificationMethod:a.classificationMethod,standardDeviationInterval:a.standardDeviationInterval,breakCount:a.numClasses||5}),l=new G;l.classificationDefinition=k;l.where=u.mergeWhereClauses(g,f);return this.generateRenderer(l,h).then(p=>n.resolveCBResult(a,p))};m._classBreaksFromInterpolation=function(a){const {minValue:b,maxValue:c}=a,d=a.numClasses||5,e=[],h=(c-b)/d;
for(let g=0;g<d;g++){const f=b+g*h;e.push({minValue:f,maxValue:f+h})}e[d-1].maxValue=c;a=n.resolveCBResult(a,{classBreaks:e,normalizationTotal:a.normalizationTotal});return Promise.resolve(a)};m._classBreaksFromMemory=function(){var a=y._asyncToGenerator(function*(b){const {field:c,normalizationField:d,valueExpression:e,view:h,signal:g}=b;var f={field:c,valueExpression:e,normalizationField:d,view:h,signal:g};f=b.features||(yield this._fetchFeaturesForStats(f));if(!f||!f.length)throw new w("feature-layer-adapter:insufficient-data",
"No features are available to calculate statistics");b={...b};if("percent-of-total"===b.normalizationType){const k=(yield n.calculateStatsFromMemory({field:c},f)).sum;if(null==k)throw new w("feature-layer-adapter:invalid","invalid normalizationTotal");b.normalizationTotal=k}return n.calculateClassBreaksFromMemory(b,f)});return function(b){return a.apply(this,arguments)}}();m._heatmapStatsFromMemory=function(){var a=y._asyncToGenerator(function*(b,c){const {blurRadius:d,field:e,view:h,signal:g}=b,
{resolution:f,size:k}=h.state,l=new W({extent:h.extent,tolerance:f});b=this._quantizeFeatures(b.features||(yield this._fetchFeaturesForStats({field:e,view:h,returnGeometry:!0,signal:g})),l,h);if(!b||!b.length)return{count:0,min:null,max:null,avg:null,stddev:null};if(c=n.calculateHeatmapStats(b,d,c,e,k[0],k[1]))return{count:c.count,min:c.min,max:c.max,avg:c.mean,stddev:c.stdDev};throw new w("feature-layer-adapter:invalid","unable to calculate heatmap statistics");});return function(b,c){return a.apply(this,
arguments)}}();m._quantizeFeatures=function(a,b,c){const d=M.toQuantizationTransform(b),{spatialReference:e,size:h}=c,g=N.isWrappable(e)?N.getInfo(e):null,f=g?Math.round((g.valid[1]-g.valid[0])/d.scale[0]):null;return a.map(k=>{const l=new ba(F.unwrap(k.geometry));M.quantizePoint(d,l,l,l.hasZ,l.hasM);k.geometry=g?this._wrapPoint(l,f,h[0]):l;return k})};m._wrapPoint=function(a,b,c){0>a.x?a.x+=b:a.x>c&&(a.x-=b);return a};m.getField=function(a=""){return this.layer.getField(a)};m.getFieldUsageInfo=function(a){return this.getField(a)?
{supportsLabelingInfo:!0,supportsRenderer:!0,supportsPopupTemplate:!0,supportsLayerQuery:!0,supportsStatistics:!0}:null};m.getFieldDomain=function(a,b){return this.layer.getFieldDomain(a,b)};m.summaryStatistics=function(a){const {field:b,normalizationType:c,sqlExpression:d,view:e,features:h}=a,g=b?this.getField(b):null,f=D.isDateField(g),k=a.valueExpression||d,l=k&&!d,p=e&&"3d"===e.type;return this._hasLocalSource||h||l?l||h||p?this._summaryStatsFromMemory(a,g):this._summaryStatsFromClientQuery(a,
f):this.supportsSQLExpression||!f&&!k&&"natural-log"!==c&&"square-root"!==c?(c&&!this.supportsSQLExpression?this._summaryStatsFromGenRend(a):this._summaryStatsFromServiceQuery(a,f)).catch(()=>{z.throwIfAborted(a.signal);return this._summaryStatsFromMemory(a,g)}):Promise.reject(new w("feature-layer-adapter:not-supported","Layer does not support standardized SQL expression for queries"))};m.uniqueValues=function(a){const {field:b,valueExpression:c,sqlExpression:d,signal:e}=a,h=(b?this.getField(b):null)&&
this.getFieldDomain(b),g=c&&(!d||!this.supportsSQLExpression),f=a.view,k=f&&"3d"===f.type;return this._hasLocalSource||a.features||g?g||a.features||k?this._uvFromMemory(a,h):this._uvFromClientQuery(a,h):this._uvFromServiceQuery(a,h).catch(l=>{z.throwIfAborted(e);return a.field?this._uvFromGenRenderer(a,h):l}).catch(()=>{z.throwIfAborted(e);return g||a.features||k?this._uvFromMemory(a,h):this._uvFromClientQuery(a,h)})};m.histogram=function(a){const {field:b,normalizationType:c,normalizationField:d,
classificationMethod:e,signal:h}=a;var g=b?this.getField(b):null;g=D.isDateField(g);const f=a.valueExpression||a.sqlExpression,k=f&&!a.sqlExpression,l=this.supportsSQLExpression,p=!e||"equal-interval"===e,q=a.minValue,r=a.maxValue,t=null!=q&&null!=r,x=a.numBins||10;return this._hasLocalSource||a.features||k?this._histogramFromMemory(a):(f||l)&&p?l||!f&&"natural-log"!==c&&"square-root"!==c?this._histogramForExpr(a):Promise.reject(new w("feature-layer-adapter:not-supported","Layer does not support standardized SQL expression for queries")):
g&&p?Promise.reject(new w("feature-layer-adapter:not-supported","Normalization and date field are not allowed when layer does not support standardized SQL expression for queries")):c||!p?this._binParamsFromGenRend(a).then(v=>{if(!t)return this._getBins(v,b,x,h);if(q>v.max||r<v.min)throw new w("histogram:insufficient-data","Range defined by 'minValue' and 'maxValue' does not intersect available data range of the field");if(p)return this._getBins({min:q,max:r,sqlExpr:v.sqlExpr,excludeZerosExpr:v.excludeZerosExpr},
b,x,h);v=n.getFieldExpr({field:b,normalizationType:c,normalizationField:d,normalizationTotal:v.normTotal,layer:this});v=u.getRangeExpr(v,q,r);return this._binParamsFromGenRend(a,v).then(C=>this._getBins(C,b,x,h))}):this._histogramForField(a)};m.classBreaks=function(a){const b=!1!==a.analyzeData,c=this._hasLocalSource||a.features||a.valueExpression;return b&&c?this._classBreaksFromMemory(a):(b?this._classBreaksFromGenRend(a):this._classBreaksFromInterpolation(a)).catch(()=>{z.throwIfAborted(a.signal);
return this._classBreaksFromMemory(a)})};m.queryFeatureCount=function(a,b){if(this._hasLocalSource)return Promise.reject(new w("feature-layer-adapter:not-supported","Layer does not support count query"));const c=this.layer,d=c.createQuery();d.where=u.mergeWhereClauses(d.where,a);return c.queryFeatureCount(d,{signal:b})};m.generateRenderer=function(a,b){var c=this.layer;if(this._hasLocalSource||10.1>c.version)return Promise.reject(new w("feature-layer-adapter:not-supported","Layer does not support generateRenderer operation (requires ArcGIS Server version 10.1+)"));
const d=new aa({url:c.parsedUrl.path,source:c.dynamicDataSource,gdbVersion:c.gdbVersion});c=c.createQuery();a.where=u.mergeWhereClauses(a.where,c.where);return d.execute(a,{signal:b})};m.heatmapStatistics=function(a){const {field:b,fieldOffset:c,signal:d}=a;return(b&&null==c?this.summaryStatistics({field:b,signal:d}):Promise.resolve(null)).then(e=>{let h=c||0;if(e){const {count:g,min:f,max:k}=e;g?f===k&&0===f?h=1:0>=k?h="abs":0>f&&(h=-1.01*f):h=1}return this._heatmapStatsFromMemory(a,h).then(g=>({...g,
summaryStatistics:e,fieldOffset:h}))})};m.predominantCategories=function(){var a=y._asyncToGenerator(function*(b){if(!this._hasLocalSource&&!this.supportsSQLExpression)throw new w("feature-layer-adapter:not-supported","Layer does not support advanced SQL expressions and standardized queries");const {fields:c,view:d,signal:e}=b;b=I.getArcadeForPredominantCategory(c);var h=I.getSQLForPredominantCategoryName(c);b=(d&&this._hasLocalSource?yield this._uvFromMemory({valueExpression:b,view:d,signal:e}):
yield this._uvFromServiceQuery({sqlExpression:h.expression,valueExpression:b,signal:e})).uniqueValueInfos;const g=b.map(f=>f.value);h=c.filter(f=>-1===g.indexOf(f));for(const f of h)b.push({value:f,count:0});b.sort((f,k)=>c.indexOf(f.value)-c.indexOf(k.value));for(const f of b)f.value===I.noDominantCategoryField&&(f.value=null);return{predominantCategoryInfos:b}});return function(b){return a.apply(this,arguments)}}();m.getSampleFeatures=function(){var a=y._asyncToGenerator(function*(b,c){const {view:d,
sampleSize:e,requiredFields:h,returnGeometry:g,signal:f}=b,k=this.layer.createQuery(),l="json"===c;k.outSpatialReference=b.spatialReference||d&&d.spatialReference;k.returnGeometry=!!g;k.outFields=h;let p=[],q=!1;if(d)try{const r=yield d.whenLayerView(this.layer);if(q=!(yield n.getMissingFields(this,h,r)).length)if(p=yield this._fetchFeaturesFromMemory(r,k,f,c),p.length&&0<e&&e<=p.length)return L.pickRandom(p,e,1)}catch(r){z.throwIfAborted(f)}try{if(this._hasLocalSource)return q?p:l?this._fetchFeaturesJSONFromService(k,
f):this._fetchFeaturesFromService(k,f);const r=yield this.queryFeatureCount(null,f),t=this.layer.capabilities.query.maxRecordCount;c=-1===e?r:e;c=t&&c>t?t:c;if(r<=p.length||p.length>=t)return p;const x=d.extent.width/d.width/d.scale*4E5;k.maxAllowableOffset=b.resolution||x;if(r<=c)return l?this._fetchFeaturesJSONFromService(k,f):this._fetchFeaturesFromService(k,f);if(2E4>=r){const v=yield this.layer.queryObjectIds();k.objectIds=L.pickRandom(v,c,1);return l?this._fetchFeaturesJSONFromService(k,f):
this._fetchFeaturesFromService(k,f)}this.layer.get("capabilities.query.supportsPagination")&&(k.num=Math.min(c,2E4));return l?this._fetchFeaturesJSONFromService(k,f):this._fetchFeaturesFromService(k,f)}catch(r){return z.throwIfAborted(f),p}});return function(b,c){return a.apply(this,arguments)}}();m.load=function(a){var b=this;const c=this.layer.load(a).then(function(){var d=y._asyncToGenerator(function*(e){b.geometryType=e.geometryType;b.objectIdField=e.objectIdField;b.supportsSQLExpression=e.get("capabilities.query.supportsSqlExpression");
b._hasLocalSource=!e.url&&!!e.source;b.hasQueryEngine=b._hasLocalSource;b.minScale=e.minScale;b.maxScale=e.maxScale;b.fullExtent=e.fullExtent;b.workerClient=Y.WorkerClient.getInstance();yield b.workerClient.open(F.unwrap(F.unwrap(a).signal))});return function(e){return d.apply(this,arguments)}}());this.addResolvingPromise(c);return Promise.resolve(this)};return B}(Z);K.__decorate([T.property({constructOnly:!0})],E.prototype,"layer",void 0);return E=K.__decorate([U.subclass("esri.smartMapping.support.adapters.FeatureLayerAdapter")],
E)});