// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
require({cache:{"esri/AggregateGraphic":function(){define("./chunks/_rollupPluginBabelHelpers ./chunks/tslib.es6 ./Graphic ./core/accessorSupport/decorators/property ./core/has ./core/accessorSupport/ensureType ./core/Logger ./core/jsonMap ./core/accessorSupport/decorators/subclass".split(" "),function(k,m,l,p,q,g,r,n,e){var x;l=x=function(y){function h(){var t=y.apply(this,arguments)||this;t.isAggregate=!0;return t}k._inheritsLoose(h,y);var v=h.prototype;v.getEffectivePopupTemplate=function(t){return this.popupTemplate?
this.popupTemplate:(t=this.sourceLayer&&this.sourceLayer.featureReduction)&&"popupTemplate"in t&&t.popupEnabled?t.popupTemplate:null};v.getObjectId=function(){return this.objectId};v.clone=function(){return new x({objectId:this.objectId,...this.cloneProperties()})};return h}(l);m.__decorate([p.property({type:Boolean})],l.prototype,"isAggregate",void 0);m.__decorate([p.property({type:Number,json:{read:!0}})],l.prototype,"objectId",void 0);return l=x=m.__decorate([e.subclass("esri.AggregateGraphic")],
l)})},"esri/renderers/support/clickToleranceUtils":function(){define(["exports"],function(k){function m(q,g){return g?"xoffset"in g&&g.xoffset?Math.max(q,Math.abs(g.xoffset)):"yoffset"in g&&g.yoffset?Math.max(q,Math.abs(g.yoffset||0)):q:q}function l(q,g){if("number"===typeof q)return q;if(q&&q.stops&&q.stops.length){{q=q.stops;let r=g=0;for(let n=0;n<q.length;n++){const e=q[n].size;"number"===typeof e&&(g+=e,r++)}q=g/r}return q}return g}function p(q,g){if(!g)return q;g=g.filter(e=>"size"===e.type).map(e=>
{const {maxSize:x,minSize:y}=e;return(l(x,q)+l(y,q))/2});let r=0;const n=g.length;if(0===n)return q;for(let e=0;e<n;e++)r+=g[e];return Math.max(Math.floor(r/n),q)}k.calculateTolerance=function(q){const g=q&&q.renderer;q="touch"===(q&&q.event&&q.event.pointerType)?9:6;if(!g)return q;q="visualVariables"in g?p(q,g.visualVariables):q;if("simple"===g.type)return m(q,g.symbol);if("unique-value"===g.type){let r=q;g.uniqueValueInfos.forEach(n=>{r=m(r,n.symbol)});return r}if("class-breaks"===g.type){let r=
q;g.classBreakInfos.forEach(n=>{r=m(r,n.symbol)});return r}return q};Object.defineProperty(k,"__esModule",{value:!0})})},"esri/views/2d/layers/LayerView2D":function(){define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/Collection ../../../core/collectionUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/Logger ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass ../engine/Container ../../layers/support/ClipArea ../../layers/support/ClipRect ../../layers/support/Geometry ../../layers/support/Path".split(" "),
function(k,m,l,p,q,g,r,n,e,x,y,h,v,t,d,f,z){const E=p.ofType({key:"type",base:t,typeMap:{rect:d,path:z,geometry:f}});k.LayerView2DMixin=D=>{D=function(A){function L(){var K=A.apply(this,arguments)||this;K.clips=new E;K.moving=!1;K.attached=!1;K.lastUpdateId=-1;K.updateRequested=!1;return K}m._inheritsLoose(L,A);var H=L.prototype;H.initialize=function(){var K;this.container||(this.container=new v.Container);this.container.fadeTransitionEnabled=!0;this.container.opacity=0;this.container.clips=this.clips;
this.handles.add([g.init(this,"suspended",J=>{this.container&&(this.container.visible=!J);this.view&&!J&&this.updateRequested&&this.view.requestUpdate()},!0),g.init(this,["layer.opacity","container"],()=>{if(this.container){var J,I;this.container.opacity=null!=(J=null==(I=this.layer)?void 0:I.opacity)?J:1}},!0),g.init(this,["layer.blendMode"],J=>{this.container&&(this.container.blendMode=J)},!0),g.init(this,["layer.effect"],J=>{this.container&&(this.container.effect=J)},!0),this.clips.on("change",
()=>{this.container.clips=this.clips;this.notifyChange("clips")})]);null!=(K=this.view)&&K.whenLayerView?this.view.whenLayerView(this.layer).then(J=>{J!==this||this.attached||this.destroyed||(this.attach(),this.requestUpdate(),this.attached=!0)},()=>{}):this.when().then(()=>{this.attached||this.destroyed||(this.attach(),this.requestUpdate(),this.attached=!0)},()=>{})};H.destroy=function(){this.attached&&(this.detach(),this.attached=!1);this.handles.remove("initialize");this.updateRequested=!1};H.isVisibleAtScale=
function(K){var J=!0,I=this.layer;const B=I.minScale;I=I.maxScale;if(null!=B&&null!=I){J=!B;let G=!I;!J&&K<=B&&(J=!0);!G&&K>=I&&(G=!0);J=J&&G}return J};H.requestUpdate=function(){this.destroyed||this.updateRequested||(this.updateRequested=!0,this.suspended||this.view.requestUpdate())};H.processUpdate=function(K){this.isFulfilled()&&!this.isResolved()?this.updateRequested=!1:(this._set("updateParameters",K),this.updateRequested&&!this.suspended&&(this.updateRequested=!1,this.update(K)))};H.isUpdating=
function(){return!1};H.isRendering=function(){return!1};H.canResume=function(){return A.prototype.canResume.call(this)?this.isVisibleAtScale(this.view.scale):!1};m._createClass(L,[{key:"updating",get:function(){return!this.attached||!this.suspended&&(this.updateRequested||this.isUpdating())}}]);return L}(D);l.__decorate([r.property({type:E,set(A){A=q.referenceSetter(A,this._get("clips"),E);this._set("clips",A)}})],D.prototype,"clips",void 0);l.__decorate([r.property()],D.prototype,"moving",void 0);
l.__decorate([r.property()],D.prototype,"attached",void 0);l.__decorate([r.property()],D.prototype,"container",void 0);l.__decorate([r.property()],D.prototype,"suspended",void 0);l.__decorate([r.property({readOnly:!0})],D.prototype,"updateParameters",void 0);l.__decorate([r.property()],D.prototype,"updateRequested",void 0);l.__decorate([r.property()],D.prototype,"updating",null);l.__decorate([r.property()],D.prototype,"view",void 0);return D=l.__decorate([h.subclass("esri.views.2d.layers.LayerView2D")],
D)};Object.defineProperty(k,"__esModule",{value:!0})})},"esri/views/layers/support/ClipArea":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/JSONSupport ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/Logger ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass".split(" "),function(k,m,l,p,q,g,r,n,e){l=function(x){function y(){return x.apply(this,arguments)||
this}k._inheritsLoose(y,x);return y}(l.JSONSupport);return l=m.__decorate([e.subclass("esri.views.layers.support.ClipArea")],l)})},"esri/views/layers/support/ClipRect":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/Logger ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass ./ClipArea".split(" "),function(k,m,l,p,q,g,
r,n,e){var x;p=x=function(y){function h(){var v=y.apply(this,arguments)||this;v.type="rect";v.left=null;v.right=null;v.top=null;v.bottom=null;return v}k._inheritsLoose(h,y);h.prototype.clone=function(){return new x({left:this.left,right:this.right,top:this.top,bottom:this.bottom})};k._createClass(h,[{key:"version",get:function(){return(this._get("version")||0)+1}}]);return h}(e);m.__decorate([l.property({type:[Number,String],json:{write:!0}})],p.prototype,"left",void 0);m.__decorate([l.property({type:[Number,
String],json:{write:!0}})],p.prototype,"right",void 0);m.__decorate([l.property({type:[Number,String],json:{write:!0}})],p.prototype,"top",void 0);m.__decorate([l.property({type:[Number,String],json:{write:!0}})],p.prototype,"bottom",void 0);m.__decorate([l.property({readOnly:!0})],p.prototype,"version",null);return p=x=m.__decorate([n.subclass("esri.views.layers.support.ClipRect")],p)})},"esri/views/layers/support/Geometry":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../geometry ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/Logger ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass ../../../geometry/Geometry ../../../geometry/support/jsonUtils ./ClipArea ../../../geometry/Extent ../../../geometry/Polygon".split(" "),
function(k,m,l,p,q,g,r,n,e,x,y,h,v,t){var d;l={base:x,key:"type",typeMap:{extent:v,polygon:t}};h=d=function(f){function z(){var E=f.apply(this,arguments)||this;E.type="geometry";E.geometry=null;return E}k._inheritsLoose(z,f);z.prototype.clone=function(){return new d({geometry:this.geometry.clone()})};k._createClass(z,[{key:"version",get:function(){return(this._get("version")||0)+1}}]);return z}(h);m.__decorate([p.property({types:l,json:{read:y.fromJSON,write:!0}})],h.prototype,"geometry",void 0);
m.__decorate([p.property({readOnly:!0})],h.prototype,"version",null);return h=d=m.__decorate([e.subclass("esri.views.layers.support.Geometry")],h)})},"esri/views/layers/support/Path":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/Logger ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass ./ClipArea".split(" "),function(k,
m,l,p,q,g,r,n,e){p=function(x){function y(){var h=x.apply(this,arguments)||this;h.type="path";h.path=[];return h}k._inheritsLoose(y,x);k._createClass(y,[{key:"version",get:function(){return(this._get("version")||0)+1}}]);return y}(e);m.__decorate([l.property({type:[[[Number]]],json:{write:!0}})],p.prototype,"path",void 0);m.__decorate([l.property({readOnly:!0})],p.prototype,"version",null);return p=m.__decorate([n.subclass("esri.views.layers.support.Path")],p)})},"esri/views/2d/layers/features/tileRenderers":function(){define(["require",
"exports","../../../../chunks/_rollupPluginBabelHelpers"],function(k,m,l){function p(){p=l._asyncToGenerator(function*(q,g){if(!q)return null;switch(q.type){case "class-breaks":case "simple":case "unique-value":case "dot-density":case "dictionary":return new (yield new Promise(function(r,n){k(["./tileRenderers/SymbolTileRenderer"],function(e){r(Object.freeze({__proto__:null,"default":e}))},n)})).default(g);case "heatmap":return new (yield new Promise(function(r,n){k(["./tileRenderers/HeatmapTileRenderer"],
function(e){r(Object.freeze({__proto__:null,"default":e}))},n)})).default(g)}});return p.apply(this,arguments)}m.createOrReuseTileRenderer=function(q,g){return p.apply(this,arguments)};Object.defineProperty(m,"__esModule",{value:!0})})},"esri/views/2d/layers/support/FeatureCommandQueue":function(){define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Accessor ../../../../core/accessorSupport/decorators/property ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/Logger ../../../../core/jsonMap ../../../../core/accessorSupport/decorators/subclass ../../../support/QueueProcessor".split(" "),
function(k,m,l,p,q,g,r,n,e,x){function y(d){return d.some(f=>f.globalId)}function h(d){return d.filter(f=>!f.error).map(f=>{var z;return null!=(z=f.objectId)?z:f.globalId})}function v(d,f){d=new Set(d);for(const z of f.values())d.add(z);return d}function t(d,f){d=new Set(d);for(const z of f.values())d.delete(z);return d}l=function(d){function f(E){var D=d.call(this)||this;D._hasGlobalIds=!1;D._queueProcessor=new x.QueueProcessor({concurrency:1,process:E.process});return D}k._inheritsLoose(f,d);var z=
f.prototype;z.destroy=function(){this._queueProcessor.clear()};z.push=function(E){const D=this._queueProcessor;var A=D.last();switch(E.type){case "update":case "refresh":if((null==A?void 0:A.type)===E.type)return;D.push(E).finally(()=>this.notifyChange("updating"));break;case "edit":(A="processed-edit"===(null==A?void 0:A.type)?A:null)&&D.popLast();E=this._mergeEdits(A,E);for(const L of E)D.push(L).finally(()=>this.notifyChange("updating"))}this.notifyChange("updating")};z._mergeEdits=function(E,
D){var A,L;const {addedFeatures:H,deletedFeatures:K,updatedFeatures:J}=D.edits;if(this._hasGlobalIds=this._hasGlobalIds||y(H)||y(J)||y(K))return D=[...H,...J],[E,{type:"processed-edit",edits:{addOrModified:D,removed:K}}];D=new Set(h(null!=(A=null==E?void 0:E.edits.addOrModified)?A:[]));E=new Set(h(null!=(L=null==E?void 0:E.edits.removed)?L:[]));L=new Set([...h(H),...h(J)]);A=new Set(h(K));D=Array.from(v(t(D,A),L)).map(I=>({objectId:I}));E=Array.from(v(t(E,L),A)).map(I=>({objectId:I}));return[{type:"processed-edit",
edits:{addOrModified:D,removed:E}}]};k._createClass(f,[{key:"updating",get:function(){return 0<this._queueProcessor.length}}]);return f}(l);m.__decorate([p.property({readOnly:!0})],l.prototype,"updating",null);return l=m.__decorate([e.subclass("esri.views.2d.layers.support.FeatureCommandQueue")],l)})},"esri/views/2d/layers/support/FeatureLayerProxy":function(){define("../../../../chunks/_rollupPluginBabelHelpers ../../../../chunks/tslib.es6 ../../../../core/Promise ../../../../core/promiseUtils ../../../../core/workers/workers ../../../../core/accessorSupport/decorators/property ../../../../core/has ../../../../core/accessorSupport/ensureType ../../../../core/Logger ../../../../core/jsonMap ../../../../core/accessorSupport/decorators/subclass".split(" "),
function(k,m,l,p,q,g,r,n,e,x,y){l=function(h){function v(d){d=h.call(this,d)||this;d._startupResolver=p.createResolver();d.isReady=!1;return d}k._inheritsLoose(v,h);var t=v.prototype;t.initialize=function(){this._controller=p.createAbortController();this.addResolvingPromise(this._startWorker(this._controller.signal))};t.destroy=function(){this._controller.abort();this._connection&&this._connection.close()};t.startup=function(){var d=k._asyncToGenerator(function*(f,z,E,D){yield this.when();var A=this._controller.signal;
A=Array.isArray(E.source)?{transferList:E.source,signal:A}:void 0;f=f.tileInfo.toJSON();yield this._connection.invoke("startup",{service:E,config:z,tileInfo:f,tiles:D},A);this._startupResolver.resolve();this._set("isReady",!0)});return function(f,z,E,D){return d.apply(this,arguments)}}();t.updateTiles=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;return p.ignoreAbortErrors(this._connection.invoke("updateTiles",f))});return function(f){return d.apply(this,arguments)}}();
t.update=function(){var d=k._asyncToGenerator(function*(f){f={config:f};yield this._startupResolver.promise;return this._connection.invoke("update",f)});return function(f){return d.apply(this,arguments)}}();t.applyUpdate=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;return this._connection.invoke("applyUpdate",f)});return function(f){return d.apply(this,arguments)}}();t.setHighlight=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;
return p.ignoreAbortErrors(this._connection.invoke("controller.setHighlight",f))});return function(f){return d.apply(this,arguments)}}();t.refresh=function(){var d=k._asyncToGenerator(function*(){yield this._startupResolver.promise;return p.ignoreAbortErrors(this._connection.invoke("controller.refresh"))});return function(){return d.apply(this,arguments)}}();t.querySummaryStatistics=function(){var d=k._asyncToGenerator(function*(f,z,E){yield this._startupResolver.promise;return this._connection.invoke("controller.querySummaryStatistics",
{query:f.toJSON(),params:z},E)});return function(f,z,E){return d.apply(this,arguments)}}();t.queryFeatures=function(){var d=k._asyncToGenerator(function*(f,z){yield this._startupResolver.promise;return this._connection.invoke("controller.queryFeatures",f.toJSON(),z)});return function(f,z){return d.apply(this,arguments)}}();t.queryObjectIds=function(){var d=k._asyncToGenerator(function*(f,z){yield this._startupResolver.promise;return this._connection.invoke("controller.queryObjectIds",f.toJSON(),z)});
return function(f,z){return d.apply(this,arguments)}}();t.queryFeatureCount=function(){var d=k._asyncToGenerator(function*(f,z){yield this._startupResolver.promise;return this._connection.invoke("controller.queryFeatureCount",f.toJSON(),z)});return function(f,z){return d.apply(this,arguments)}}();t.queryExtent=function(){var d=k._asyncToGenerator(function*(f,z){return this._connection.invoke("controller.queryExtent",f.toJSON(),z)});return function(f,z){return d.apply(this,arguments)}}();t.queryLatestObservations=
function(){var d=k._asyncToGenerator(function*(f,z){yield this._startupResolver.promise;return this._connection.invoke("controller.queryLatestObservations",f.toJSON(),z)});return function(f,z){return d.apply(this,arguments)}}();t.queryStatistics=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;return this._connection.invoke("controller.queryStatistics",f)});return function(f){return d.apply(this,arguments)}}();t.getObjectId=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;
return this._connection.invoke("controller.getObjectId",f)});return function(f){return d.apply(this,arguments)}}();t.getDisplayId=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;return this._connection.invoke("controller.getDisplayId",f)});return function(f){return d.apply(this,arguments)}}();t.getFeature=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;return this._connection.invoke("controller.getFeature",f)});return function(f){return d.apply(this,
arguments)}}();t.getAggregate=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;return this._connection.invoke("controller.getAggregate",f)});return function(f){return d.apply(this,arguments)}}();t.getAggregateValueRanges=function(){var d=k._asyncToGenerator(function*(){yield this._startupResolver.promise;return this._connection.invoke("controller.getAggregateValueRanges")});return function(){return d.apply(this,arguments)}}();t.mapValidDisplayIds=function(){var d=
k._asyncToGenerator(function*(f){yield this._startupResolver.promise;return this._connection.invoke("controller.mapValidDisplayIds",f)});return function(f){return d.apply(this,arguments)}}();t.onEdits=function(){var d=k._asyncToGenerator(function*(f){yield this._startupResolver.promise;return p.ignoreAbortErrors(this._connection.invoke("controller.onEdits",f))});return function(f){return d.apply(this,arguments)}}();t.enableEvent=function(){var d=k._asyncToGenerator(function*(f,z){yield this._startupResolver.promise;
return p.ignoreAbortErrors(this._connection.invoke("controller.enableEvent",{name:f,value:z}))});return function(f,z){return d.apply(this,arguments)}}();t._startWorker=function(){var d=k._asyncToGenerator(function*(f){try{this._connection=yield q.open("Pipeline",{client:this.client,strategy:"dedicated",signal:f})}catch(z){p.throwIfNotAbortError(z)}});return function(f){return d.apply(this,arguments)}}();k._createClass(v,[{key:"tileRenderer",set:function(d){this.client.tileRenderer=d}},{key:"closed",
get:function(){return this._connection.closed}}]);return v}(l.EsriPromise);m.__decorate([g.property()],l.prototype,"isReady",void 0);m.__decorate([g.property()],l.prototype,"client",void 0);m.__decorate([g.property()],l.prototype,"tileRenderer",null);return l=m.__decorate([y.subclass("esri.views.2d.layers.support.FeatureLayerProxy")],l)})},"esri/views/2d/tiling/TileManager":function(){define(["exports","../../../core/maybe","./TileCoverage","./TileKey"],function(k,m,l,p){let q=function(){function g(n){this._tiles=
new Map;this.buffer=0;this.acquireTile=n.acquireTile;this.releaseTile=n.releaseTile;this.tileInfoView=n.tileInfoView;this.buffer=n.buffer}var r=g.prototype;r.destroy=function(){};r.clear=function(){this._tiles.forEach(n=>this._releaseTile(n))};r.tileKeys=function(){const n=[];this._tiles.forEach((e,x)=>n.push(x));return n};r.update=function(n){n=this.tileInfoView.getTileCoverage(n.state,this.buffer,"closest");const {spans:e,lodInfo:x}=n,{level:y}=x,h=[],v=[],t=new Set,d=new Set;for(const {row:f,colFrom:z,
colTo:E}of e)for(let D=z;D<=E;D++){const A=p.getId(y,f,x.normalizeCol(D),x.getWorldForColumn(D)),L=this._getOrAcquireTile(h,A);t.add(A);L.isReady?L.visible=!0:d.add(L.key)}d.forEach(f=>this._addPlaceholders(t,f));this._tiles.forEach(f=>{t.has(f.key.id)||(v.push(f.key.id),this._releaseTile(f))});l.pool.release(n);return{hasMissingTiles:0<d.size,added:h,removed:v}};r._getOrAcquireTile=function(n,e){if(!this._tiles.has(e)){const x=this.acquireTile(new p(e));n.push(e);this._tiles.set(e,x);x.visible=!1}return this._tiles.get(e)};
r._getTile=function(n){return this._tiles.get(n)};r._releaseTile=function(n){this._tiles.delete(n.key.id);this.releaseTile(n)};r._addPlaceholders=function(n,e){const x=this._addPlaceholderChildren(n,e);1E-6>Math.abs(1-x)||this._addPlaceholderParent(n,e)||(this._getTile(e.id).visible=!0)};r._addPlaceholderChildren=function(n,e){let x=0;this._tiles.forEach(y=>{x+=this._addPlaceholderChild(n,y,e)});return x};r._addPlaceholderChild=function(n,e,x){if(e.key.level<=x.level||!e.hasData||!x.contains(e.key))return 0;
e.visible=!0;n.add(e.key.id);return 1/(1<<2*(e.key.level-x.level))};r._addPlaceholderParent=function(n,e){e=e.getParentKey();let x=0,y=null;for(;m.isSome(e);){if(n.has(e.id))return!0;const h=this._getTile(e.id);if(null!=h&&h.isReady)return h.visible=!0,n.add(h.key.id),!0;null!=h&&h.hasData&&h.patchCount>x&&(x=h.patchCount,y=h);e=e.getParentKey()}return y?(y.visible=!0,n.add(y.key.id),!0):!1};return g}();k.TileManager=q;Object.defineProperty(k,"__esModule",{value:!0})})},"esri/views/layers/FeatureLayerView":function(){define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/Error ../../core/Logger ../../core/maybe ../../core/promiseUtils ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/jsonMap ../../core/accessorSupport/decorators/subclass ../../layers/support/commonProperties ../../layers/support/fieldUtils ../../rest/support/Query ../../support/arcadeOnDemand ./support/FeatureEffect ./support/FeatureFilter ./support/popupUtils".split(" "),
function(k,m,l,p,q,g,r,n,e,x,y,h,v,t,d,f,z,E,D,A){const L=q.getLogger("esri.views.layers.FeatureLayerView");q=H=>{H=function(K){function J(...B){B=K.call(this,...B)||this;B._updatingRequiredFieldsPromise=null;B.effect=null;B.filter=null;B.timeExtent=null;B.layer=null;B.requiredFields=[];B.view=null;return B}m._inheritsLoose(J,K);var I=J.prototype;I.initialize=function(){n.init(this,"layer.renderer layer.labelingInfo layer.elevationInfo.featureExpressionInfo layer.displayField filter effect layer.timeInfo layer.floorInfo timeExtent".split(" "),
()=>this._handleRequiredFieldsChange(),!0);n.on(this,"view.floors","change",()=>this._handleRequiredFieldsChange());n.on(this,"layer.sublayer","change",()=>this._handleRequiredFieldsChange())};I.highlight=function(B){throw Error("missing implementation");};I.createQuery=function(){var B={outFields:["*"],returnGeometry:!0,outSpatialReference:this.view.spatialReference};B=g.isSome(this.filter)?this.filter.createQuery(B):new f(B);g.isSome(this.timeExtent)&&(B.timeExtent=g.isSome(B.timeExtent)?B.timeExtent.intersection(this.timeExtent):
this.timeExtent.clone());return B};I.queryFeatures=function(B,G){throw Error("missing implementation");};I.queryObjectIds=function(B,G){throw Error("missing implementation");};I.queryFeatureCount=function(B,G){throw Error("missing implementation");};I.queryExtent=function(B,G){throw Error("missing implementation");};I._loadArcadeModules=function(B){if(B.get("expressionInfos.length"))return z.loadArcade()};I._handleRequiredFieldsChange=function(){const B=this._updateRequiredFields();this._set("_updatingRequiredFieldsPromise",
B);B.then(()=>{this._updatingRequiredFieldsPromise===B&&this._set("_updatingRequiredFieldsPromise",null)})};I._updateRequiredFields=function(){var B=m._asyncToGenerator(function*(){if(this.layer&&this.view){var G="3d"===this.view.type,{layer:C,layer:{fieldsIndex:U,objectIdField:R}}=this,O="renderer"in C&&C.renderer,Q=C.featureReduction,M=new Set;O=yield r.eachAlways([O?O.collectRequiredFields(M,U):null,d.collectLabelingFields(M,C),G?d.collectElevationFields(M,C):null,g.isSome(this.filter)?d.collectFilterFields(M,
C,this.filter):null,this.effect?d.collectFilterFields(M,C,this.effect.filter):null,Q?d.collectFeatureReductionFields(M,C,Q):null]);C.timeInfo&&this.timeExtent&&d.collectFields(M,C.fieldsIndex,[C.timeInfo.startField,C.timeInfo.endField]);"feature"===C.type&&C.floorInfo&&d.collectFields(M,C.fieldsIndex,[C.floorInfo.floorField]);"subtype-group"===C.type&&(d.collectField(M,U,C.subtypeField),Q=C.sublayers.map(Y=>{var da;return Promise.all([null==(da=Y.renderer)?void 0:da.collectRequiredFields(M,U),d.collectLabelingFields(M,
Y)])}),yield r.eachAlways(Q));for(const Y of O)Y.error&&L.error(Y.error);d.collectField(M,U,R);G&&"displayField"in C&&C.displayField&&d.collectField(M,U,C.displayField);G=Array.from(M).sort();this._set("requiredFields",G)}});return function(){return B.apply(this,arguments)}}();I.validateFetchPopupFeatures=function(B){if(g.isNone(B))return null;for(const G of B.clientGraphics){const C=G.layer;if("popupEnabled"in C&&!C.popupEnabled)return new p("featurelayerview:fetchPopupFeatures","Popups are disabled",
{layer:C});if("popupTemplate"in C&&!A.getFetchPopupTemplate(C,B))return new p("featurelayerview:fetchPopupFeatures","Layer does not define a popup template",{layer:C})}};I.fetchClientPopupFeatures=function(){var B=m._asyncToGenerator(function*(G){var C=g.isSome(G)?G.clientGraphics:null;if(!C||0===C.length)return Promise.resolve([]);const U=[],R=[],O=yield this.createPopupQuery(G);for(const M of C){var {layer:Q}=M;if(!("popupEnabled"in Q))continue;C=d.unpackFieldNames(this.layer.fieldsIndex,O.outFields);
Q=A.getFetchPopupTemplate(Q,G);if(!g.isSome(Q))continue;const Y=yield this._loadArcadeModules(Q);Y&&Y.arcadeUtils.hasGeometryOperations(Q)||!d.featureHasFields(C,M)?R.push(M):U.push(M)}if("stream"===this.layer.type||0===R.length)return Promise.resolve(U);O.objectIds=R.map(M=>M.attributes[this.layer.objectIdField]);return this.layer.queryFeatures(O).then(M=>U.concat(M.features)).catch(()=>R)});return function(G){return B.apply(this,arguments)}}();I.createPopupQuery=function(){var B=m._asyncToGenerator(function*(G){const C=
this.layer.createQuery(),U=new Set;var R=!1,O=g.isSome(G)&&G.clientGraphics?G.clientGraphics.map(Q=>Q.layer):[this.layer];for(const Q of O)if("popupEnabled"in Q&&(O=A.getFetchPopupTemplate(Q,G),g.isSome(O))){R=(R=yield this._loadArcadeModules(O))&&R.arcadeUtils.hasGeometryOperations(O);R=!("point"!==this.layer.geometryType&&!R);O=yield A.getRequiredFields(this.layer,O);for(const M of O)U.add(M)}C.returnGeometry=R;C.returnZ=R;C.returnM=R;C.outFields=Array.from(U);C.outSpatialReference=this.view.spatialReference;
return C});return function(G){return B.apply(this,arguments)}}();I.canResume=function(){return!K.prototype.canResume.call(this)||g.isSome(this.timeExtent)&&this.timeExtent.isEmpty?!1:!0};m._createClass(J,[{key:"availableFields",get:function(){const {layer:B,layer:{fieldsIndex:G},requiredFields:C}=this;return"outFields"in B&&B.outFields?d.fixFields(G,[...d.unpackFieldNames(G,B.outFields),...C]):d.fixFields(G,C)}},{key:"maximumNumberOfFeatures",get:function(){return 0},set:function(B){L.error("#maximumNumberOfFeatures\x3d",
"Setting maximum number of features is not supported")}},{key:"maximumNumberOfFeaturesExceeded",get:function(){return!1}}]);return J}(H);l.__decorate([e.property()],H.prototype,"_updatingRequiredFieldsPromise",void 0);l.__decorate([e.property({readOnly:!0})],H.prototype,"availableFields",null);l.__decorate([e.property({type:E})],H.prototype,"effect",void 0);l.__decorate([e.property({type:D})],H.prototype,"filter",void 0);l.__decorate([e.property(t.combinedViewLayerTimeExtentProperty)],H.prototype,
"timeExtent",void 0);l.__decorate([e.property()],H.prototype,"layer",void 0);l.__decorate([e.property({type:Number})],H.prototype,"maximumNumberOfFeatures",null);l.__decorate([e.property({readOnly:!0,type:Boolean})],H.prototype,"maximumNumberOfFeaturesExceeded",null);l.__decorate([e.property({readOnly:!0})],H.prototype,"requiredFields",void 0);l.__decorate([e.property()],H.prototype,"suspended",void 0);l.__decorate([e.property()],H.prototype,"view",void 0);return H=l.__decorate([v.subclass("esri.views.layers.FeatureLayerView")],
H)};k.FeatureLayerView=q;k.default=q;Object.defineProperty(k,"__esModule",{value:!0})})},"esri/views/layers/support/FeatureEffect":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../core/JSONSupport ../../../core/accessorSupport/decorators/property ../../../core/has ../../../core/accessorSupport/ensureType ../../../core/Logger ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass ./FeatureFilter".split(" "),function(k,m,l,p,q,g,r,n,e,
x){var y;l=y=function(h){function v(){var t=h.apply(this,arguments)||this;t.filter=null;t.includedEffect=null;t.excludedEffect=null;t.excludedLabelsVisible=!1;return t}k._inheritsLoose(v,h);v.prototype.clone=function(){return new y({filter:this.filter&&this.filter.clone(),includedEffect:this.includedEffect,excludedEffect:this.excludedEffect,excludedLabelsVisible:this.excludedLabelsVisible})};return v}(l.JSONSupport);m.__decorate([p.property({type:x,json:{write:!0}})],l.prototype,"filter",void 0);
m.__decorate([p.property({json:{write:!0}})],l.prototype,"includedEffect",void 0);m.__decorate([p.property({json:{write:!0}})],l.prototype,"excludedEffect",void 0);m.__decorate([p.property({type:Boolean,json:{write:!0}})],l.prototype,"excludedLabelsVisible",void 0);return l=y=m.__decorate([e.subclass("esri.views.layers.support.FeatureEffect")],l)})},"esri/views/layers/support/FeatureFilter":function(){define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../geometry ../../../TimeExtent ../../../core/jsonMap ../../../core/JSONSupport ../../../core/lang ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/has ../../../core/Logger ../../../core/accessorSupport/decorators/subclass ../../../core/accessorSupport/decorators/writer ../../../geometry/support/jsonUtils ../../../rest/support/Query".split(" "),
function(k,m,l,p,q,g,r,n,e,x,y,h,v,t,d){var f;e=new q.JSONMap({esriSpatialRelIntersects:"intersects",esriSpatialRelContains:"contains",esriSpatialRelCrosses:"crosses",esriSpatialRelDisjoint:"disjoint",esriSpatialRelEnvelopeIntersects:"envelope-intersects",esriSpatialRelIndexIntersects:"index-intersects",esriSpatialRelOverlaps:"overlaps",esriSpatialRelTouches:"touches",esriSpatialRelWithin:"within",esriSpatialRelRelation:"relation"});q=new q.JSONMap({esriSRUnit_Meter:"meters",esriSRUnit_Kilometer:"kilometers",
esriSRUnit_Foot:"feet",esriSRUnit_StatuteMile:"miles",esriSRUnit_NauticalMile:"nautical-miles",esriSRUnit_USNauticalMile:"us-nautical-miles"});g=f=function(z){function E(A){A=z.call(this,A)||this;A.where=null;A.geometry=null;A.spatialRelationship="intersects";A.hiddenIds=new Set;A.distance=void 0;A.objectIds=null;A.units=null;A.timeExtent=null;A.enabled=!1;return A}k._inheritsLoose(E,z);var D=E.prototype;D.writeWhere=function(A,L){L.where=A||"1\x3d1"};D.enable=function(){this._set("enabled",!0)};
D.createQuery=function(A={}){const {where:L,geometry:H,spatialRelationship:K,timeExtent:J,objectIds:I,units:B,distance:G}=this;return new d({geometry:r.clone(H),objectIds:r.clone(I),spatialRelationship:K,timeExtent:r.clone(J),where:L,units:B,distance:G,...A})};D.clone=function(){const {where:A,geometry:L,spatialRelationship:H,hiddenIds:K,timeExtent:J,objectIds:I,units:B,distance:G}=this,C=new Set;K.forEach(U=>C.add(U));return new f({geometry:r.clone(L),hiddenIds:C,objectIds:r.clone(I),spatialRelationship:H,
timeExtent:r.clone(J),where:A,units:B,distance:G})};return E}(g.JSONSupport);m.__decorate([n.property({type:String})],g.prototype,"where",void 0);m.__decorate([v.writer("where")],g.prototype,"writeWhere",null);m.__decorate([n.property({types:l.geometryTypes,json:{read:t.fromJSON,write:!0}})],g.prototype,"geometry",void 0);m.__decorate([n.property({type:String,json:{read:{source:"spatialRel",reader:e.read},write:{target:"spatialRel",writer:e.write}}})],g.prototype,"spatialRelationship",void 0);m.__decorate([n.property({json:{write:(z,
E,D)=>E[D]=Array.from(z),read:z=>new Set(z)}})],g.prototype,"hiddenIds",void 0);m.__decorate([n.property({type:Number,json:{write:{overridePolicy(z){return{enabled:0<z}}}}})],g.prototype,"distance",void 0);m.__decorate([n.property({type:[Number],json:{write:!0}})],g.prototype,"objectIds",void 0);m.__decorate([n.property({type:String,json:{read:q.read,write:{writer:q.write,overridePolicy(z){return{enabled:z&&0<this.distance}}}}})],g.prototype,"units",void 0);m.__decorate([n.property({type:p,json:{write:!0}})],
g.prototype,"timeExtent",void 0);m.__decorate([n.property({readOnly:!0})],g.prototype,"enabled",void 0);return g=f=m.__decorate([h.subclass("esri.views.layers.support.FeatureFilter")],g)})},"esri/views/layers/support/popupUtils":function(){define(["exports","../../../chunks/_rollupPluginBabelHelpers","../../../core/maybe","../../../layers/support/fieldUtils"],function(k,m,l,p){function q(){q=m._asyncToGenerator(function*(g,r=g.popupTemplate){if(!l.isSome(r))return[];const n=yield r.getRequiredFields(g.fieldsIndex);
({lastEditInfoEnabled:r}=r);const {objectIdField:e,typeIdField:x,globalIdField:y,relationships:h}=g;if(n.includes("*"))return["*"];r=r?yield p.getFeatureEditFields(g):[];const v=p.fixFields(g.fieldsIndex,[...n,...r]);x&&v.push(x);v&&e&&g.fieldsIndex.has(e)&&-1===v.indexOf(e)&&v.push(e);v&&y&&g.fieldsIndex.has(y)&&-1===v.indexOf(y)&&v.push(y);h&&h.forEach(t=>{({keyField:t}=t);v&&t&&g.fieldsIndex.has(t)&&-1===v.indexOf(t)&&v.push(t)});return v});return q.apply(this,arguments)}k.getFetchPopupTemplate=
function(g,r){return g.popupTemplate?g.popupTemplate:l.isSome(r)&&r.defaultPopupTemplateEnabled&&l.isSome(g.defaultPopupTemplate)?g.defaultPopupTemplate:null};k.getRequiredFields=function(g){return q.apply(this,arguments)};Object.defineProperty(k,"__esModule",{value:!0})})},"esri/views/support/drapedUtils":function(){define("exports ../../geometry ../../core/maybe ../../core/unitUtils ../../renderers/support/clickToleranceUtils ../../geometry/Extent".split(" "),function(k,m,l,p,q,g){function r(e,
x,y,h=new g){let v;if("2d"===y.type)v=x*y.resolution;else if("3d"===y.type){var t=y.overlayPixelSizeInMapUnits(e),d=y.basemapSpatialReference;v=l.isSome(d)&&!d.equals(y.spatialReference)?p.getMetersPerUnitForSR(d)/p.getMetersPerUnitForSR(y.spatialReference):x*t}x=e.x-v;t=e.y-v;d=e.x+v;e=e.y+v;({spatialReference:y}=y);h.xmin=Math.min(x,d);h.ymin=Math.min(t,e);h.xmax=Math.max(x,d);h.ymax=Math.max(t,e);h.spatialReference=y;return h}const n=new g;k.createQueryGeometry=r;k.intersectsDrapedGeometry=function(e,
x,y){e=y.toMap(e);if(l.isNone(e))return!1;const h=q.calculateTolerance();return r(e,h,y,n).intersects(x)};Object.defineProperty(k,"__esModule",{value:!0})})},"*noref":1}});
define("../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../AggregateGraphic ../../../geometry ../../../Graphic ../../../core/arrayUtils ../../../core/Collection ../../../core/Error ../../../core/has ../../../core/lang ../../../core/Logger ../../../core/maybe ../../../core/promiseUtils ../../../core/watchUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass ../../../layers/support/arcgisLayerUrl ../../../renderers/support/clickToleranceUtils ../../../rest/support/FeatureSet ../../../rest/support/Query ../engine/webgl/definitions ./LayerView2D ./features/schemaUtils ./features/tileRenderers ./features/support/pixelBuffering ./support/clusterUtils ./support/FeatureCommandQueue ./support/FeatureLayerProxy ./support/util ../tiling/TileManager ../../layers/FeatureLayerView ../../layers/LayerView ../../layers/RefreshableLayerView ../../layers/effects/EffectList ../../layers/support/FeatureFilter ../../layers/support/FeatureEffect ../../support/drapedUtils ../../webgl/capabilities ../../../geometry/Extent".split(" "),function(k,
m,l,p,q,g,r,n,e,x,y,h,v,t,d,f,z,E,D,A,L,H,K,J,I,B,G,C,U,R,O,Q,M,Y,da,fa,ha,ka,la,ia,ma){function ja(ca){return ca&&"openPorts"in ca}const aa=y.getLogger("esri.views.2d.layers.FeatureLayerView2D");p=function(ca){function ea(){var a=ca.apply(this,arguments)||this;a._pipelineIsUpdating=!0;a._commandsQueue=new U({process:b=>{switch(b.type){case "processed-edit":return a._doEdit(b);case "refresh":return a._doRefresh();case "update":return a._doUpdate()}}});a._visibilityOverrides=new Set;a._effect=null;
a._highlightIds=new Map;a._lastPixelBuffer=0;a._updateHighlight=v.debounce(k._asyncToGenerator(function*(){return a._proxy.setHighlight(Array.from(a._highlightIds.keys()))}));a._uploadsLocked=!1;a._needsClusterSizeUpdate=!1;a.filter=null;a.effectLists={included:new fa["default"],excluded:new fa["default"]};return a}k._inheritsLoose(ea,ca);var w=ea.prototype;w.destroy=function(){var a,b;h.andThen(this._updateClusterSizeTask,c=>c.remove());null==(a=this._proxy)?void 0:a.destroy();null==(b=this.tileRenderer)?
void 0:b.destroy();this._commandsQueue.destroy()};w.initialize=function(){this.addResolvingPromise(Promise.all([this._initProxy(),this._initServiceOptions()]));this.handles.add([this.on("valueRangesChanged",a=>{this._set("_aggregateValueRanges",a.valueRanges)}),t.init(this,"effect",a=>{this.effectLists.included.effect=null==a?void 0:a.includedEffect}),t.init(this,"effect",a=>{this.effectLists.excluded.effect=null==a?void 0:a.excludedEffect})])};w._initProxy=function(){var a=k._asyncToGenerator(function*(){if("isTable"in
this.layer&&this.layer.isTable)throw new n("featurelayerview:table-not-supported","table feature layer can't be displayed",{layer:this.layer});this._proxy&&this._proxy.destroy();const b=this._createClientOptions();this._set("_proxy",new R({client:b}));return this._proxy.when()});return function(){return a.apply(this,arguments)}}();w._initServiceOptions=function(){var a=k._asyncToGenerator(function*(){this._set("_serviceOptions",yield this._createServiceOptions())});return function(){return a.apply(this,
arguments)}}();w.highlight=function(a){let b;a instanceof q?b=[a.getObjectId()]:"number"===typeof a||"string"===typeof a?b=[a]:r.isCollection(a)?b=a.map(c=>c&&c.getAttribute(this.layer.objectIdField)).toArray():Array.isArray(a)&&0<a.length&&(b="number"===typeof a[0]||"string"===typeof a[0]?a:a.map(c=>c&&c.getAttribute(this.layer.objectIdField)));if(!b||!b.length)return{remove:()=>{}};b=b.filter(c=>null!=c);this._addHighlight(b);return{remove:()=>this._removeHighlight(b)}};w.hasHighlight=function(){return!!this._highlightIds.size};
w.hitTest=function(a,b){return this._hitTest(a,b)};w.queryStatistics=function(){return this._proxy.queryStatistics()};w.querySummaryStatistics=function(){var a=k._asyncToGenerator(function*(b,c,u){const F={...c};if(c.valueExpression){var N;F.viewInfoParams={viewingMode:"map",scale:this.view.scale,spatialReference:null==(N=this.view.spatialReference)?void 0:N.toJSON()}}return this._proxy.querySummaryStatistics(this._cleanUpQuery(b),F,u)});return function(b,c,u){return a.apply(this,arguments)}}();w.queryFeatures=
function(a,b){return this.queryFeaturesJSON(a,b).then(c=>{c=L.fromJSON(c);c.features.forEach(u=>this._setLayersForFeature(u));return c})};w.queryFeaturesJSON=function(a,b){return this._proxy.queryFeatures(this._cleanUpQuery(a),b)};w.queryObjectIds=function(a,b){return this._proxy.queryObjectIds(this._cleanUpQuery(a),b)};w.queryFeatureCount=function(a,b){return this._proxy.queryFeatureCount(this._cleanUpQuery(a),b)};w.queryExtent=function(a,b){return this._proxy.queryExtent(this._cleanUpQuery(a),b).then(c=>
({count:c.count,extent:ma.fromJSON(c.extent)}))};w.setVisibility=function(a,b){b?this._visibilityOverrides.delete(a):this._visibilityOverrides.add(a);this._update()};w.update=function(a){if(this._tileStrategy&&this.tileRenderer){var {hasMissingTiles:b,added:c,removed:u}=this._tileStrategy.update(a);(c.length||u.length)&&this._proxy.updateTiles({added:c,removed:u});b&&this.requestUpdate();this.notifyChange("updating")}};w.attach=function(){this.view.timeline.record(`${this.layer.title} (FeatureLayer) Attach`);
this._tileStrategy=new Q.TileManager({acquireTile:a=>this._acquireTile(a),releaseTile:a=>this._releaseTile(a),tileInfoView:this.view.featuresTilingScheme,buffer:0});this.handles.add(t.init(this,"renderingConfigHash",()=>this._update()),"attach");"stream"!==this.layer.type&&this.handles.add(this.layer.on("edits",a=>this._edit(a)),"attach")};w.detach=function(){this.container.removeAllChildren();this.handles.remove("attach");this.tileRenderer&&(this.tileRenderer.uninstall(this.container),this.tileRenderer=
null);this._tileStrategy&&(this._tileStrategy.destroy(),this._tileStrategy=null);this._tileRendererHash=null};w.moveStart=function(){this.requestUpdate()};w.viewChange=function(){this.requestUpdate()};w.moveEnd=function(){this.requestUpdate()};w.fetchPopupFeatures=function(){var a=k._asyncToGenerator(function*(b,c){if(h.isSome(c)&&c.clientGraphics.length){var u=c.clientGraphics[0];if(u instanceof l)return[u];c.clientGraphics=c.clientGraphics.filter(F=>{({layer:F}=F);const N="popupTemplate"in F&&F.popupTemplate,
V=this.view.popup.defaultPopupTemplateEnabled;return"popupEnabled"in F&&F.popupEnabled&&(N||V)})}if(u=this.validateFetchPopupFeatures(c))throw u;if(h.isSome(c)&&0===c.clientGraphics.length)return[];u=this.fetchClientPopupFeatures(c);if(!b)return u;b=this._fetchServicePopupFeatures(b,c);return v.eachAlwaysValues([u,b]).then(g.flatten)});return function(b,c){return a.apply(this,arguments)}}();w._fetchServicePopupFeatures=function(){var a=k._asyncToGenerator(function*(b,c){if("stream"===this.layer.type||
"ogc-feature"===this.layer.type)return[];const u=yield this.createPopupQuery(c),{layer:F}=this;var N="renderer"in F&&F.renderer;const V=h.isSome(c)?c.event:null;N=A.calculateTolerance({renderer:N,event:V});u.geometry=this.createFetchPopupFeaturesQueryGeometry(b,N);const S=new Set,{objectIdField:W}=F;if(b=h.isSome(c)?c.clientGraphics:null)for(const P of b)S.add(P.attributes[W]);return F.queryFeatures(u).then(P=>P.features.filter(T=>!S.has(T.attributes[W])))});return function(b,c){return a.apply(this,
arguments)}}();w.createFetchPopupFeaturesQueryGeometry=function(a,b){return la.createQueryGeometry(a,b,this.view)};w.isUpdating=function(){var a;const b="renderer"in this.layer&&null!=this.layer.renderer,c=this._commandsQueue.updating,u=null!=this._updatingRequiredFieldsPromise,F=!this._proxy||!this._proxy.isReady,N=this._pipelineIsUpdating,V=null===this.tileRenderer||(null==(a=this.tileRenderer)?void 0:a.updating);a=b&&(c||u||F||N||V);e("esri-2d-log-updating")&&console.log(`Updating FLV2D: ${a}
  -> hasRenderer ${b}
  -> hasPendingCommand ${c}
  -> updatingRequiredFields ${u}
  -> updatingProxy ${F}
  -> updatingPipeline ${N}
  -> updatingTileRenderer ${V}
`);return a};w._createClientOptions=function(){return{setUpdating:a=>{this._set("_pipelineIsUpdating",a)},emitEvent:a=>{this.emit(a.name,a.event)}}};w._detectQueryMode=function(){var a=k._asyncToGenerator(function*(b){if("path"in b&&D.isHostedAgolService(b.path)&&("feature"===this.layer.type||"subtype-group"===this.layer.type)&&"point"===this.layer.geometryType&&!this.layer.capabilities.operations.supportsEditing&&e("featurelayer-snapshot-enabled"))try{const c=yield this.layer.queryFeatureCount(),
u=e("featurelayer-snapshot-point-min-threshold");if(c<=u)return{mode:"snapshot",featureCount:c};const F=e("featurelayer-snapshot-point-max-threshold"),N=e("featurelayer-snapshot-point-coverage"),V=this.view.extent,S=this.layer.fullExtent,W=null==S?void 0:S.clone().intersection(V),P=(null==W?NaN:W.width)*(null==W?NaN:W.height),T=(null==S?NaN:S.width)*(null==S?NaN:S.height);b=0===T?0:P/T;if(c<=F&&b>=N)return{mode:"snapshot",featureCount:c}}catch(c){aa.warn("mapview-feature-layer","Encountered an error when querying for featureCount",
{error:c})}return{mode:"on-demand"}});return function(b){return a.apply(this,arguments)}}();w._createServiceOptions=function(){var a=k._asyncToGenerator(function*(){var b,c=this.layer;if("stream"===c.type)return null;const {capabilities:u,objectIdField:F}=c,N=c.fields.map(na=>na.toJSON()),V=c.fullExtent&&c.fullExtent.toJSON(),S=O.toJSONGeometryType(c.geometryType),W=c.timeInfo&&c.timeInfo.toJSON()||null,P=c.spatialReference?c.spatialReference.toJSON():null,T={..."customParameters"in c?c.customParameters:
void 0,token:"apiKey"in c?c.apiKey:void 0},Z="feature"===c.type?c.globalIdField:null;let X;"ogc-feature"===c.type?X=c.source.getFeatureDefinition():ja(c.source)?X=yield c.source.openPorts():c.parsedUrl&&(X=x.clone(c.parsedUrl),"dynamicDataSource"in c&&c.dynamicDataSource&&(X.query={layer:JSON.stringify({source:c.dynamicDataSource})}));c=null!=(b="subtypeField"in this.layer&&this.layer.subtypeField)?b:null;const {mode:ba,featureCount:oa}=yield this._detectQueryMode(X);return{type:ba,subtypeField:c,
featureCount:oa,globalIdField:Z,maxRecordCount:u.query.maxRecordCount,tileMaxRecordCount:u.query.tileMaxRecordCount,capabilities:u,fields:N,fullExtent:V,geometryType:S,objectIdField:F,source:X,timeInfo:W,spatialReference:P,customParameters:T}});return function(){return a.apply(this,arguments)}}();w._createMemoryServiceOptions=function(){var a=k._asyncToGenerator(function*(b){b=yield b.openPorts();return{...this._createServiceOptions(),type:"memory",source:b}});return function(b){return a.apply(this,
arguments)}}();w._cleanUpQuery=function(a){a=H.from(a)||this.createQuery();a.outSpatialReference||(a.outSpatialReference=this.view.spatialReference);return a};w._update=function(){var a=k._asyncToGenerator(function*(){return this._commandsQueue.push({type:"update"})});return function(){return a.apply(this,arguments)}}();w._edit=function(){var a=k._asyncToGenerator(function*(b){if(this._validateEdit(b))return this._commandsQueue.push({type:"edit",edits:b})});return function(b){return a.apply(this,
arguments)}}();w.doRefresh=function(){var a=k._asyncToGenerator(function*(){return this._commandsQueue.push({type:"refresh"})});return function(){return a.apply(this,arguments)}}();w._validateEdit=function(a){const b="globalIdField"in this.layer&&this.layer.globalIdField,c=a.deletedFeatures.some(F=>-1===F.objectId||!F.objectId),u=b&&this.availableFields.includes(b);return c&&!u?(aa.error(new n("mapview-apply-edits",`Editing the specified service requires the layer's globalIdField, ${b} to be included the layer's outFields for updates to be reflected on the map`)),
null):a};w._doUpdate=function(){var a=k._asyncToGenerator(function*(){try{if(!this.destroyed&&this._hasRequiredSupport(this.layer)&&this._tileStrategy){var {effect:b,filter:c}=this;yield this._updateRequiredFields();var {renderer:u}=this._getEffectiveRenderer();this._set("_effectiveRenderer",u);var F=this._createSchemaConfig(),N=O.toJSONGeometryType(this.layer.geometryType),V=yield G.computePxBuffer(u,N,this.layer.featureReduction),S=this._createConfiguration(F,c,b);this._lastPixelBuffer=0===V?0:
Math.max(V,this._lastPixelBuffer);S.schema.source.pixelBuffer=this._lastPixelBuffer;var W=this._createTileRendererHash(u);if(W!==this._tileRendererHash){yield this._initTileRenderer(u);const P=this._serviceOptions;this.effects.forEach(X=>h.isSome(X)&&h.isSome(X.filter)&&X.filter.enable());this.tileRenderer.onConfigUpdate(u);const T={added:this._tileStrategy.tileKeys(),removed:[]},Z=this.layer;"stream"!==Z.type&&ja(Z.source)&&(P.source=yield Z.source.openPorts());yield this._proxy.startup(this.view.featuresTilingScheme,
S,P,T);this.hasHighlight()&&(yield this._proxy.setHighlight(Array.from(this._highlightIds.keys())));yield this._onceTilesUpdated();this.tileRenderer.onConfigUpdate(u)}else{const P=yield this._proxy.update(S);(P.mesh||P.targets.aggregate)&&this._lockGPUUploads();try{yield this._proxy.applyUpdate(P)}catch(T){v.isAbortError(T)||aa.error(T)}(P.mesh||P.targets.aggregate)&&this._unlockGPUUploads();this.effects.forEach(T=>h.isSome(T)&&h.isSome(T.filter)&&T.filter.enable());this.tileRenderer.onConfigUpdate(u);
this._updateClusterSizeVariable();this._forceAttributeTextureUpload()}this._tileRendererHash=W;this.tileRenderer.invalidateLabels();this.requestUpdate()}}catch(P){}});return function(){return a.apply(this,arguments)}}();w._doEdit=function(){var a=k._asyncToGenerator(function*(b){try{yield this._proxy.onEdits(b)}catch(c){v.isAbortError(c)}});return function(b){return a.apply(this,arguments)}}();w._doRefresh=function(){var a=k._asyncToGenerator(function*(){this._lockGPUUploads();try{yield this._proxy.refresh()}catch(b){v.isAbortError(b)}this._unlockGPUUploads()});
return function(){return a.apply(this,arguments)}}();w._updateClusterSizeVariable=function(){this._needsClusterSizeUpdate&&(this.tileRenderer.onConfigUpdate(this._effectiveRenderer),this._needsClusterSizeUpdate=!1)};w._createUpdateClusterSizeTask=function(a,b){var c=this;return this.watch("_aggregateValueRanges",function(){var u=k._asyncToGenerator(function*(F){c._updateClusterEffectiveRendererSizeVariable(a,b,F);c._needsClusterSizeUpdate=!0;c._uploadsLocked||c._updateClusterSizeVariable()});return function(F){return u.apply(this,
arguments)}}())};w._updateClusterEffectiveRendererSizeVariable=function(){var a=k._asyncToGenerator(function*(b,c,u){if(b.dynamicClusterSize&&"visualVariables"in b&&b.visualVariables){var F=C.findSizeVV(b.visualVariables);h.isSome(F)&&"cluster_count"===F.field&&(F=b.visualVariables.indexOf(F),b.visualVariables[F]=C.createClusterCountSizeVariable(c,u),b=b.clone(),b.dynamicClusterSize=!0,this._set("_effectiveRenderer",b))}});return function(b,c,u){return a.apply(this,arguments)}}();w._getEffectiveRenderer=
function(){var a="renderer"in this.layer&&this.layer.renderer;const b=this.layer.featureReduction;h.isSome(this._updateClusterSizeTask)&&(this._updateClusterSizeTask.remove(),this._updateClusterSizeTask=null);if(b&&"cluster"===b.type&&C.isClusterCompatibleRenderer(a)){const c=[];a=C.createClusterRenderer(c,a,b,this._aggregateValueRanges);h.andThen(this._updateClusterSizeTask,u=>u.remove());this._updateClusterSizeTask=this._createUpdateClusterSizeTask(a,b);return{renderer:a,aggregateFields:c,featureReduction:b}}return{renderer:a,
aggregateFields:[],featureReduction:null}};w._acquireTile=function(a){a=this.tileRenderer.acquireTile(a);a.once("attach",()=>{this.requestUpdate()});return a};w._releaseTile=function(a){this.tileRenderer.releaseTile(a)};w._initTileRenderer=function(){var a=k._asyncToGenerator(function*(b){const c=yield B.createOrReuseTileRenderer(b,{layerView:this,tileInfoView:this.view.featuresTilingScheme,layer:this.layer});this.tileRenderer&&(this._tileStrategy.clear(),this.tileRenderer.uninstall(this.container),
this.tileRenderer.destroy(),this.tileRenderer=null);if(this.destroyed)return null;this._proxy.tileRenderer=c;this._set("tileRenderer",c);this.tileRenderer.install(this.container);this.tileRenderer.onConfigUpdate(b);this.requestUpdate();return this.tileRenderer});return function(b){return a.apply(this,arguments)}}();w._createTileRendererHash=function(a){return`${"heatmap"===a.type?"heatmap":"symbol"}.${"dot-density"===a.type}`};w._createFeatureDataHash=function(a,b,c){a=a.getAttributeHash();b=JSON.stringify(b);
c=h.isSome(c)&&JSON.stringify(c.filter);const u=JSON.stringify(this.timeExtent);let F="";this._visibilityOverrides.forEach(N=>F+=N);return`${a}.${b}.${c}.${u}.${F}`};w._injectOverrides=function(a){var b=h.isSome(a)?a.timeExtent:null;b=h.isSome(this.timeExtent)&&h.isSome(b)?this.timeExtent.intersection(b):this.timeExtent||b;var c=null;const u="floorInfo"in this.layer&&this.layer.floorInfo;u&&(c=h.isSome(a)&&a.where,c=this._addFloorFilterClause(c));if(!this._visibilityOverrides.size&&!b&&!u)return a;
a=h.isSome(a)&&a.clone()||new ha;a.hiddenIds=this._visibilityOverrides;a.timeExtent=b;c&&(a.where=c);return a};w._addFloorFilterClause=function(a){var b=this.layer;a=a||"";if("floorInfo"in b&&b.floorInfo){var c,u=this.view.floors;if(!u||!u.length)return a;null!=(c=b.floorInfo.viewAllLevelIds)&&c.length&&(u=b.floorInfo.viewAllLevelIds);c=u.filter(F=>""!==F).map(F=>"'"+F+"'");c.push("''");b=b.floorInfo.floorField;u="("+b+" IN ({ids}) OR "+b+" IS NULL)";u=u.replace("{ids}",c.join(", "));h.isSome(a)&&
a.includes(b)&&(c=new RegExp("AND \\("+b+".*NULL\\)","g"),a=a.replace(c,""),c=new RegExp("\\("+b+".*NULL\\)","g"),a=a.replace(c,""),a=a.replace(/\s+/g," ").trim());a=""!==a?"("+a+") AND "+u:u}return""!==a?a:null};w._createConfiguration=function(a,b,c){const u="feature"===this.layer.type&&this.layer.historicMoment?this.layer.historicMoment.getTime():void 0,F="feature"===this.layer.type?this.layer.gdbVersion:void 0,N=Array(K.MAX_FILTERS);b=this._injectOverrides(b);N[0]=h.isSome(b)?b.toJSON():null;N[1]=
h.isSome(c)&&c.filter?c.filter.toJSON():null;a=I.createSchema(a);if(h.isNone(a))return null;c=ia();return{definitionExpression:this.layer.definitionExpression,availableFields:this.availableFields,gdbVersion:F,historicMoment:u,devicePixelRatio:window.devicePixelRatio||1,filters:N,schema:a,supportsTextureFloat:c.supportsTextureFloat,maxTextureSize:c.maxTextureSize}};w._hasRequiredSupport=function(a){var b;return"renderer"in a&&"dot-density"===(null==(b=a.renderer)?void 0:b.type)&&!ia().supportsTextureFloat?
(aa.error(new n("webgl-missing-extension","Missing WebGL extension OES_Texture_Float which is required for DotDensity")),!1):!0};w._onceTilesUpdated=function(){this.requestUpdate();return t.whenFalseOnce(this,"_pipelineIsUpdating",!1)};w._lockGPUUploads=function(){this.tileRenderer&&(this._uploadsLocked=!0,this.tileRenderer.lockGPUUploads())};w._unlockGPUUploads=function(){this.tileRenderer&&(this._uploadsLocked=!1,this.tileRenderer.unlockGPUUploads())};w._forceAttributeTextureUpload=function(){this.tileRenderer&&
this.tileRenderer.forceAttributeTextureUpload()};w._createSchemaConfig=function(){return{renderer:"renderer"in this.layer&&this.layer.renderer,spatialReference:this.layer.spatialReference,timeExtent:this.layer.timeExtent,definitionExpression:this.layer.definitionExpression,featureReduction:this.layer.featureReduction,fields:this.layer.fields,geometryType:this.layer.geometryType,historicMoment:"feature"===this.layer.type?this.layer.historicMoment:null,labelsVisible:"labelsVisible"in this.layer&&this.layer.labelsVisible,
labelingInfo:"labelingInfo"in this.layer&&this.layer.labelingInfo,availableFields:this.availableFields,effect:this.effect,filter:this.filter,gdbVersion:"feature"===this.layer.type?this.layer.gdbVersion:null,pixelBuffer:0}};w._addHighlight=function(a){for(const b of a)this._highlightIds.has(b)?(a=this._highlightIds.get(b),this._highlightIds.set(b,a+1)):this._highlightIds.set(b,1);this._updateHighlight().catch(b=>{v.isAbortError(b)||aa.error(b)})};w._removeHighlight=function(a){for(const b of a)this._highlightIds.has(b)&&
(a=this._highlightIds.get(b)-1,0===a?this._highlightIds.delete(b):this._highlightIds.set(b,a));this._updateHighlight().catch(b=>{v.isAbortError(b)||aa.error(b)})};w._setLayersForFeature=function(a){const b=this.layer;a.layer=b;a.sourceLayer=b};w._createHittestResult=function(a){this._setLayersForFeature(a);h.isSome(a.geometry)&&(a.geometry.spatialReference=this.view.spatialReference);return a};w._hitTest=function(){var a=k._asyncToGenerator(function*(b,c){if(this.suspended||!this.tileRenderer)return null;
b=yield this.tileRenderer.hitTest(b,c);if(0===b.length)return yield v.after(1),null;b=b[0];if(1!==(b&2147483648)>>>31)return b=yield this._proxy.getFeature(b),h.andThen(b,u=>this._createHittestResult(q.fromJSON(u)));b=yield this._proxy.getAggregate(b);return h.isNone(b)?null:h.isSome(b.referenceId)?(b=yield this._proxy.getFeature(b.referenceId),h.andThen(b,u=>this._createHittestResult(q.fromJSON(u)))):this._createHittestResult(l.fromJSON(b))});return function(b,c){return a.apply(this,arguments)}}();
k._createClass(ea,[{key:"labelsVisible",get:function(){const a="subtype-group"===this.layer.type?this.layer.sublayers.items:[this.layer];return!this.suspended&&a.some(b=>b.labelingInfo&&b.labelsVisible)}},{key:"effect",get:function(){return h.unwrapOr(this._effect,null)},set:function(a){const b=this._effect;h.isSome(b)&&h.isSome(b.filter)&&b.filter.enabled&&h.isSome(a)&&h.isSome(a.filter)&&a.filter.enable();this._effect=a;this.notifyChange("effect")}},{key:"effects",get:function(){return this.effect&&
[this.effect]||[]}},{key:"queryMode",get:function(){return this._serviceOptions.type}},{key:"renderingConfigHash",get:function(){if(!this.layer)return null;const a=this.availableFields;var b=this.layer;const c=this.view.floors,{definitionExpression:u}=b,F="subtype-group"!==this.layer.type&&this.layer.labelsVisible&&this.layer.labelingInfo,N="renderer"in b&&b.renderer,V="feature"===b.type?b.gdbVersion:void 0,S="feature"===b.type&&b.historicMoment?b.historicMoment.getTime():void 0,{timeExtent:W}=this,
P="stream"===b.type?`${JSON.stringify(b.geometryDefinition)}${b.definitionExpression}`:null,T=JSON.stringify(this.clips);b=b.featureReduction&&b.featureReduction.toJSON();const Z="sublayers"in this.layer&&this.layer.sublayers.items.reduce((X,ba)=>X+`${ba.visible?1:0}.${JSON.stringify(ba.renderer)}.${ba.labelsVisible}
.${JSON.stringify(ba.labelingInfo)}`,"");return JSON.stringify({sublayerHash:Z,filterHash:h.isSome(this.filter)&&this.filter.toJSON(),effectHash:h.isSome(this.effect)&&this.effect.toJSON(),streamFilter:P,gdbVersion:V,definitionExpression:u,historicMoment:S,availableFields:a,renderer:N,labelingInfo:F,timeExtent:W,floors:c,clipsHash:T,featureReduction:b})}},{key:"hasEffects",get:function(){return this.effectLists.included.hasEffects||this.effectLists.excluded.hasEffects}},{key:"hasFilter",get:function(){const a=
!!("floorInfo"in this.layer&&this.layer.floorInfo&&this.view.floors&&this.view.floors.length);return!!this.filter||a||!!this._visibilityOverrides.size||!!this.timeExtent}}]);return ea}(M.FeatureLayerView(da.RefreshableLayerView(J.LayerView2DMixin(Y))));m.__decorate([d.property()],p.prototype,"_serviceOptions",void 0);m.__decorate([d.property()],p.prototype,"_proxy",void 0);m.__decorate([d.property()],p.prototype,"_pipelineIsUpdating",void 0);m.__decorate([d.property()],p.prototype,"_effectiveRenderer",
void 0);m.__decorate([d.property()],p.prototype,"_aggregateValueRanges",void 0);m.__decorate([d.property()],p.prototype,"_commandsQueue",void 0);m.__decorate([d.property()],p.prototype,"labelsVisible",null);m.__decorate([d.property({type:ha})],p.prototype,"filter",void 0);m.__decorate([d.property({type:ka})],p.prototype,"effect",null);m.__decorate([d.property({readOnly:!0})],p.prototype,"effects",null);m.__decorate([d.property({readOnly:!0})],p.prototype,"queryMode",null);m.__decorate([d.property()],
p.prototype,"renderingConfigHash",null);m.__decorate([d.property()],p.prototype,"tileRenderer",void 0);m.__decorate([d.property()],p.prototype,"updating",void 0);return p=m.__decorate([E.subclass("esri.views.2d.layers.FeatureLayerView2D")],p)});