// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../../../../chunks/_rollupPluginBabelHelpers ../../../../../geometry ../../../../../core/has ../../../../../core/maybe ../../../../../layers/graphics/centroid ../../../../../layers/graphics/featureConversionUtils ../../../../../layers/graphics/OptimizedGeometry ./StaticBitSet ../../../../../geometry/support/jsonUtils".split(" "),function(l,n,m,v,g,p,q,r,t,u){let h=0;m=function(){function k(a){this.type="FeatureSetReader";this.seen=!1;this._ty=this._tx=this.instance=0;this._sy=this._sx=
1;this._deleted=null;this._joined=[];this._objectIdToIndex=null;this.instance=a}k.createInstance=function(){h++;return h=65535<h?0:h};var b=k.prototype;b.setArcadeSpatialReference=function(a){this._arcadeSpatialReference=a};b.attachStorage=function(a){this._storage=a};b.getQuantizationTransform=function(){throw Error("Unable to find transform for featureSet");};b.getStorage=function(){return this._storage};b.getComputedNumeric=function(a){return this.getComputedNumericAtIndex(0)};b.setComputedNumeric=
function(a,c){return this.setComputedNumericAtIndex(c,0)};b.getComputedString=function(a){return this.getComputedStringAtIndex(0)};b.setComputedString=function(a,c){return this.setComputedStringAtIndex(0,c)};b.getComputedNumericAtIndex=function(a){return this._storage.getComputedNumericAtIndex(this.getDisplayId(),a)};b.setComputedNumericAtIndex=function(a,c){this._storage.setComputedNumericAtIndex(this.getDisplayId(),a,c)};b.getComputedStringAtIndex=function(a){return this._storage.getComputedStringAtIndex(this.getDisplayId(),
a)};b.setComputedStringAtIndex=function(a,c){return this._storage.setComputedStringAtIndex(this.getDisplayId(),a,c)};b.transform=function(a,c,d,f){const e=this.copy();e._tx+=a;e._ty+=c;e._sx*=d;e._sy*=f;return e};b.readAttribute=function(a,c=!1){var d=this._readAttribute(a,c);if(void 0!==d)return d;for(const f of this._joined)if(f.setIndex(this.getIndex()),d=f._readAttribute(a,c),void 0!==d)return d};b.readAttributes=function(){const a=this._readAttributes();for(const c of this._joined){c.setIndex(this.getIndex());
const d=c._readAttributes();for(const f of Object.keys(d))a[f]=d[f]}return a};b.joinAttributes=function(a){this._joined.push(a)};b.readArcadeFeature=function(){return this};b.geometry=function(){var a=this.readHydratedGeometry();a=q.convertToGeometry(a,this.geometryType,this.hasZ,this.hasM);if(a=u.fromJSON(a))a.spatialReference=this._arcadeSpatialReference;return a};b.field=function(a){return this.readAttribute(a,!0)};b.hasField=function(a){return!0};b.setField=function(a,c){};b.keys=function(){return[]};
b.castToText=function(){return""};b.removeIds=function(a){if(g.isNone(this._objectIdToIndex)){var c=new Map;const d=this.getCursor();for(;d.next();)c.set(d.getObjectId(),d.getIndex());this._objectIdToIndex=c}c=this._objectIdToIndex;for(const d of a)c.has(d)&&this.removeAtIndex(c.get(d))};b.removeAtIndex=function(a){g.isNone(this._deleted)&&(this._deleted=t.StaticBitSet.create(this.getSize()));this._deleted.set(a)};b.features=function*(){const a=this.getCursor();for(;a.next();)yield a.readOptimizedFeature()};
b._getExists=function(){return g.isNone(this._deleted)||!this._deleted.has(this.getIndex())};b._computeCentroid=function(){if("esriGeometryPolygon"!==this.geometryType)return null;const a=this.readUnquantizedGeometry();if(!a||a.hasIndeterminateRingOrder)return null;const c=g.unwrapOr(this.getQuantizationTransform(),null);return p.getCentroidOptimizedGeometry(new r,a,this.hasM,this.hasZ,c)};b.copyInto=function(a){a.seen=this.seen;a._storage=this._storage;a._arcadeSpatialReference=this._arcadeSpatialReference;
a._joined=this._joined;a._tx=this._tx;a._ty=this._ty;a._sx=this._sx;a._sy=this._sy;a._deleted=this._deleted;a._objectIdToIndex=this._objectIdToIndex};n._createClass(k,[{key:"isEmpty",get:function(){return g.isSome(this._deleted)&&this._deleted.countSet()===this.getSize()}}]);return k}();l.FeatureSetReader=m;Object.defineProperty(l,"__esModule",{value:!0})});