// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../core/Logger ./enums ./Renderbuffer ./RenderingContext ./Texture ./Util".split(" "),function(x,p,u,q,y,n,v){function m(k){return"type"in k&&"texture"===k.type}function w(k,e){void 0!==e.width&&0<=e.width&&void 0!==e.height&&0<=e.height?e.width===k.width&&e.height===k.height||console.error("Renderbuffer dimensions must match the framebuffer's!"):(e.width=k.width,e.height=k.height)}const z=p.getLogger("esri.views.webgl.FrameBufferObject");p=function(){function k(a,
b,c,f){this._context=a;this._stencilAttachment=this._depthAttachment=this._glName=null;this._colorAttachments=new Map;this._initialized=!1;this._desc={...b};a.instanceCounter.increment(u.ResourceType.Framebuffer,this);if(c)for(Array.isArray(c)||(c=[c]),b=0;b<c.length;++b){var d;const g=c[b];let h;m(g)?(h=g.descriptor,this._colorAttachments.set(36064+b,g)):(h=g,this._colorAttachments.set(36064+b,new n(a,g)));0!==(null==(d=this._desc)?void 0:d.colorTarget)&&console.error("Framebuffer is initialized with a texture however the descriptor indicates using a renderbuffer color attachment!");
this._validateColorAttachmentPoint(36064+b);this._validateTextureDimensions(h,this._desc)}if(f instanceof q){var l;a=null!=(l=this._desc.depthStencilTarget)?l:3;2===a?this._stencilAttachment=f:1===a||3===a?this._depthAttachment=f:console.error('If a Renderbuffer is provided, "depthStencilTarget" must be one of STENCIL_RENDER_BUFFER, DEPTH_RENDER_BUFFER or DEPTH_STENCIL_RENDER_BUFFER');w(f.descriptor,this._desc)}else if(f){this._context.capabilities.depthTexture||console.error("Extension WEBGL_depth_texture isn't supported therefore it is no possible to set the depth/stencil texture as an attachment!");
let g;m(f)?(this._depthStencilTexture=f,g=f.descriptor):this._depthStencilTexture=new n(this._context,f);this._validateTextureDimensions(g,this._desc)}}var e=k.prototype;e.dispose=function(){if(this._desc){var a=this._context.getBoundFramebufferObject();this._disposeColorAttachments();this._disposeDepthStencilAttachments();this._glName&&(this._context.gl.deleteFramebuffer(this._glName),this._glName=null);this._context.bindFramebuffer(a);this._context.instanceCounter.decrement(u.ResourceType.Framebuffer,
this);this._desc=null}};e.getColorTexture=function(a){return(a=this._colorAttachments.get(a))&&m(a)?a:null};e.attachColorTexture=function(a,b=36064){if(a){this._validateColorAttachmentPoint(b);this._validateTextureDimensions(a.descriptor,this._desc);this._disposeColorAttachments();if(this._initialized){this._context.bindFramebuffer(this);const c=this._context.gl;c.framebufferTexture2D(c.FRAMEBUFFER,b,c.TEXTURE_2D,a.glName,0)}this._colorAttachments.set(b,a)}};e.detachColorTexture=function(a=36064){const b=
this._colorAttachments.get(a);if(m(b)){if(this._initialized){this._context.bindFramebuffer(this);const c=this._context.gl;c.framebufferTexture2D(c.FRAMEBUFFER,a,c.TEXTURE_2D,null,0)}this._colorAttachments.delete(a);return b}};e.attachDepthStencilTexture=function(a){if(a){var b=a.descriptor;34041!==b.pixelFormat&&console.error("Depth/Stencil texture must have a pixel type of DEPTH_STENCIL!");34042!==b.dataType&&console.error("Depth/Stencil texture must have data type of UNSIGNED_INT_24_8!");this._context.capabilities.depthTexture||
console.error("Extension WEBGL_depth_texture isn't supported therefore it is no possible to set the depth/stencil texture!");this._validateTextureDimensions(b,this._desc);this._desc.depthStencilTarget&&4!==this._desc.depthStencilTarget&&(this._desc.depthStencilTarget=4);this._disposeDepthStencilAttachments();this._initialized&&(this._context.bindFramebuffer(this),b=this._context.gl,b.framebufferTexture2D(b.FRAMEBUFFER,b.DEPTH_STENCIL_ATTACHMENT,b.TEXTURE_2D,a.glName,0));this._depthStencilTexture=
a}};e.detachDepthStencilTexture=function(){const a=this._depthStencilTexture;if(a&&this._initialized){this._context.bindFramebuffer(this);const b=this._context.gl;this._context.gl.framebufferTexture2D(b.FRAMEBUFFER,b.DEPTH_STENCIL_ATTACHMENT,b.TEXTURE_2D,null,0)}this._depthStencilTexture=null;return a};e.attachDepthStencilBuffer=function(a){if(a){var b=a.descriptor;34041!==b.internalFormat&&33189!==b.internalFormat&&console.error("Depth/Stencil buffer must have correct internalFormat");w(b,this._desc);
this._disposeDepthStencilAttachments();this._desc.depthStencilTarget=34041===b.internalFormat?3:1;this._initialized&&(this._context.bindFramebuffer(this),b=this._context.gl,b.framebufferRenderbuffer(b.FRAMEBUFFER,1===this._desc.depthStencilTarget?b.DEPTH_ATTACHMENT:b.DEPTH_STENCIL_ATTACHMENT,b.RENDERBUFFER,a.glName));this._depthAttachment=a}};e.detachDepthStencilBuffer=function(){const a=this._context.gl,b=this._depthAttachment;b&&this._initialized&&(this._context.bindFramebuffer(this),a.framebufferRenderbuffer(a.FRAMEBUFFER,
1===this._desc.depthStencilTarget?a.DEPTH_ATTACHMENT:a.DEPTH_STENCIL_ATTACHMENT,a.RENDERBUFFER,null));this._depthAttachment=null;return b};e.detachAll=function(){this.detachColorTexture();this.detachDepthStencilBuffer();this.detachDepthStencilTexture()};e.copyToTexture=function(a,b,c,f,d,l,g){(0>a||0>b||0>d||0>l)&&console.error("Offsets cannot be negative!");(0>=c||0>=f)&&console.error("Copy width and height must be greater than zero!");var h=this._desc;const r=g.descriptor;3553!==g.descriptor.target&&
console.error("Texture target must be TEXTURE_2D!");(a+c>h.width||b+f>h.height||d+c>r.width||l+f>r.height)&&console.error("Bad dimensions, the current input values will attempt to read or copy out of bounds!");h=this._context;g=h.bindTexture(g,n.TEXTURE_UNIT_FOR_UPDATES);h.bindFramebuffer(this);h.gl.copyTexSubImage2D(3553,0,d,l,a,b,c,f);h.bindTexture(g,n.TEXTURE_UNIT_FOR_UPDATES)};e.readPixels=function(a,b,c,f,d,l,g){(0>=c||0>=f)&&console.error("Copy width and height must be greater than zero!");
g||console.error("Target memory is not initialized!");this._context.bindFramebuffer(this);this._context.gl.readPixels(a,b,c,f,d,l,g)};e.resize=function(a,b){const c=this._desc;if(c.width!==a||c.height!==b)if(this._initialized){c.width=a;c.height=b;this._colorAttachments.forEach(f=>{f&&f.resize(a,b)});if(null!=this._depthStencilTexture)this._depthStencilTexture.resize(a,b);else if(this._depthAttachment||this._stencilAttachment)this._depthAttachment&&this._depthAttachment.resize(a,b),this._stencilAttachment&&
this._stencilAttachment.resize(a,b);this._context.getBoundFramebufferObject()===this&&this._context.bindFramebuffer(null);this._initialized=!1}else c.width=a,c.height=b,this._colorAttachments.forEach(f=>{f&&f.resize(a,b)}),this._depthStencilTexture&&this._depthStencilTexture.resize(a,b)};e.initializeAndBind=function(){var a,b,c,f;const d=this._context.gl;if(this._initialized)d.bindFramebuffer(d.FRAMEBUFFER,this.glName);else{this._glName&&d.deleteFramebuffer(this._glName);var l=this._context,g=d.createFramebuffer(),
h=this._desc,r=null!=(a=h.colorTarget)?a:1;a=null!=(b=h.width)?b:1;b=null!=(c=h.height)?c:1;d.bindFramebuffer(d.FRAMEBUFFER,g);0===this._colorAttachments.size&&(0===r?this._colorAttachments.set(36064,new n(l,{target:3553,pixelFormat:6408,dataType:5121,samplingMode:9728,wrapMode:33071,width:h.width,height:h.height})):(c=new q(l,{internalFormat:32854,width:a,height:b}),this._colorAttachments.set(36064,c)));this._colorAttachments.forEach((t,A)=>{t&&(m(t)?d.framebufferTexture2D(d.FRAMEBUFFER,A,d.TEXTURE_2D,
t.glName,0):d.framebufferRenderbuffer(d.FRAMEBUFFER,d.COLOR_ATTACHMENT0,d.RENDERBUFFER,t.glName))});c=null!=(f=h.depthStencilTarget)?f:0;switch(c){case 1:case 3:this._depthAttachment||(this._depthAttachment=new q(l,{internalFormat:1===h.depthStencilTarget?33189:34041,width:a,height:b}));d.framebufferRenderbuffer(d.FRAMEBUFFER,1===c?d.DEPTH_ATTACHMENT:d.DEPTH_STENCIL_ATTACHMENT,d.RENDERBUFFER,this._depthAttachment.glName);break;case 2:this._stencilAttachment||(this._stencilAttachment=new q(l,{internalFormat:36168,
width:a,height:b}));d.framebufferRenderbuffer(d.FRAMEBUFFER,d.STENCIL_ATTACHMENT,d.RENDERBUFFER,this._stencilAttachment.glName);break;case 4:this._depthStencilTexture||(l.capabilities.depthTexture||console.error("Extension WEBGL_depth_texture isn't supported therefore it is no possible to set the depth/stencil texture as an attachment!"),this._depthStencilTexture=new n(l,{target:3553,pixelFormat:34041,dataType:34042,samplingMode:9728,wrapMode:33071,width:a,height:b})),d.framebufferTexture2D(d.FRAMEBUFFER,
d.DEPTH_STENCIL_ATTACHMENT,d.TEXTURE_2D,this._depthStencilTexture.glName,0)}y.webglValidateShadersEnabled()&&d.checkFramebufferStatus(d.FRAMEBUFFER)!==d.FRAMEBUFFER_COMPLETE&&console.error("Framebuffer is incomplete!");this._glName=g;this._initialized=!0}};e._disposeColorAttachments=function(){this._colorAttachments.forEach((a,b)=>{if(m(a)){if(this._initialized){this._context.bindFramebuffer(this);var c=this._context.gl;c.framebufferTexture2D(c.FRAMEBUFFER,b,c.TEXTURE_2D,null,0)}a.dispose()}else a instanceof
WebGLRenderbuffer&&(c=this._context.gl,this._initialized&&(this._context.bindFramebuffer(this),c.framebufferRenderbuffer(c.FRAMEBUFFER,b,c.RENDERBUFFER,null)),this._context.gl.deleteRenderbuffer(a))});this._colorAttachments.clear()};e._disposeDepthStencilAttachments=function(){const a=this._context.gl;this._depthAttachment&&(this._initialized&&(this._context.bindFramebuffer(this),a.framebufferRenderbuffer(a.FRAMEBUFFER,1===this._desc.depthStencilTarget?a.DEPTH_ATTACHMENT:a.DEPTH_STENCIL_ATTACHMENT,
a.RENDERBUFFER,null)),this._depthAttachment.dispose(),this._depthAttachment=null);this._stencilAttachment&&(this._initialized&&(this._context.bindFramebuffer(this),a.framebufferRenderbuffer(a.FRAMEBUFFER,a.STENCIL_ATTACHMENT,a.RENDERBUFFER,null)),this._stencilAttachment.dispose(),this._stencilAttachment=null);this._depthStencilTexture&&(this._initialized&&(this._context.bindFramebuffer(this),a.framebufferTexture2D(a.FRAMEBUFFER,a.DEPTH_STENCIL_ATTACHMENT,a.TEXTURE_2D,null,0)),this._depthStencilTexture.dispose(),
this._depthStencilTexture=null)};e._validateTextureDimensions=function(a,b){3553!==a.target&&console.error("Texture type must be TEXTURE_2D!");void 0!==b.width&&0<=b.width&&void 0!==b.height&&0<=b.height?b.width===a.width&&b.height===a.height||console.error("Color attachment texture must match the framebuffer's!"):(b.width=a.width,b.height=a.height)};e._validateColorAttachmentPoint=function(a){if(-1===k._MAX_COLOR_ATTACHMENTS){const b=this._context.capabilities.drawBuffers;k._MAX_COLOR_ATTACHMENTS=
b?this._context.gl.getParameter(b.MAX_COLOR_ATTACHMENTS):1}a-=36064;a+1>k._MAX_COLOR_ATTACHMENTS&&z.error("esri.FrameBufferObject",`illegal attachment point for color attachment: ${a+1}. Implementation supports up to ${k._MAX_COLOR_ATTACHMENTS} color attachments`)};x._createClass(k,[{key:"glName",get:function(){return this._glName}},{key:"descriptor",get:function(){return this._desc}},{key:"colorTexture",get:function(){const a=this._colorAttachments.get(36064);return a&&m(a)?a:null}},{key:"colorAttachment",
get:function(){return this._colorAttachments.get(36064)}},{key:"depthStencilAttachment",get:function(){return this._depthStencilTexture||this._depthAttachment||this._stencilAttachment}},{key:"depthStencilTexture",get:function(){return this._depthStencilTexture}},{key:"width",get:function(){return this._desc.width}},{key:"height",get:function(){return this._desc.height}},{key:"gpuMemoryUsage",get:function(){return v.getGpuMemoryUsage(this.colorAttachment)+v.getGpuMemoryUsage(this.depthStencilAttachment)}}]);
return k}();p._MAX_COLOR_ATTACHMENTS=-1;return p});