// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../chunks/_rollupPluginBabelHelpers ../geometry ../core/workers/workers ./Point ./support/jsonUtils".split(" "),function(d,h,S,Q,n,O){function f(a){var b;return Array.isArray(a)?null==(b=a[0])?void 0:b.spatialReference:null==a?void 0:a.spatialReference}function P(a){return a?Array.isArray(a)?a.map(P):a.toJSON?a.toJSON():a:a}function k(a){return Array.isArray(a)?a.map(b=>O.fromJSON(b)):O.fromJSON(a)}function R(){return p.apply(this,arguments)}function p(){p=h._asyncToGenerator(function*(){q||
(q=Q.open("geometryEngineWorker",{strategy:"distributed"}));return q});return p.apply(this,arguments)}function e(a,b){return r.apply(this,arguments)}function r(){r=h._asyncToGenerator(function*(a,b){return(yield R()).invoke("executeGEOperation",{operation:a,parameters:P(b)})});return r.apply(this,arguments)}function t(){t=h._asyncToGenerator(function*(a,b){a=yield e("clip",[f(a),a,b]);return k(a)});return t.apply(this,arguments)}function u(){u=h._asyncToGenerator(function*(a,b){a=yield e("cut",[f(a),
a,b]);return k(a)});return u.apply(this,arguments)}function v(){v=h._asyncToGenerator(function*(a){a=yield e("simplify",[f(a),a]);return k(a)});return v.apply(this,arguments)}function w(){w=h._asyncToGenerator(function*(a,b=!1){a=yield e("convexHull",[f(a),a,b]);return k(a)});return w.apply(this,arguments)}function x(){x=h._asyncToGenerator(function*(a,b){a=yield e("difference",[f(a),a,b]);return k(a)});return x.apply(this,arguments)}function y(){y=h._asyncToGenerator(function*(a,b){a=yield e("symmetricDifference",
[f(a),a,b]);return k(a)});return y.apply(this,arguments)}function z(){z=h._asyncToGenerator(function*(a,b){a=yield e("intersect",[f(a),a,b]);return k(a)});return z.apply(this,arguments)}function A(){A=h._asyncToGenerator(function*(a,b=null){{let c;Array.isArray(a)?c=a:(c=[],c.push(a),null!=b&&c.push(b));a=c}a=yield e("union",[f(a),a]);return k(a)});return A.apply(this,arguments)}function B(){B=h._asyncToGenerator(function*(a,b,c,g,l,m){a=yield e("offset",[f(a),a,b,c,g,l,m]);return k(a)});return B.apply(this,
arguments)}function C(){C=h._asyncToGenerator(function*(a,b,c,g=!1){a=[f(a),a,b,c,g];a=yield e("buffer",a);return k(a)});return C.apply(this,arguments)}function D(){D=h._asyncToGenerator(function*(a,b,c,g,l,m){a=[f(a),a,b,c,g,l,m];a=yield e("geodesicBuffer",a);return k(a)});return D.apply(this,arguments)}function E(){E=h._asyncToGenerator(function*(a,b,c=!0){a=yield e("nearestCoordinate",[f(a),a,b,c]);return{...a,coordinate:n.fromJSON(a.coordinate)}});return E.apply(this,arguments)}function F(){F=
h._asyncToGenerator(function*(a,b){a=yield e("nearestVertex",[f(a),a,b]);return{...a,coordinate:n.fromJSON(a.coordinate)}});return F.apply(this,arguments)}function G(){G=h._asyncToGenerator(function*(a,b,c,g){return(yield e("nearestVertices",[f(a),a,b,c,g])).map(l=>({...l,coordinate:n.fromJSON(l.coordinate)}))});return G.apply(this,arguments)}function H(a){return"xmin"in a?a.center:"x"in a?a:a.extent.center}function I(){I=h._asyncToGenerator(function*(a,b,c){var g;if(null==a)throw Error("Illegal Argument Exception");
const l=a.spatialReference;c=null!=(g=c)?g:H(a);a=a.constructor.fromJSON(yield e("rotate",[l,a,b,c]));a.spatialReference=l;return a});return I.apply(this,arguments)}function J(){J=h._asyncToGenerator(function*(a,b){var c;if(null==a)throw Error("Illegal Argument Exception");const g=a.spatialReference;b=null!=(c=b)?c:H(a);a=a.constructor.fromJSON(yield e("flipHorizontal",[g,a,b]));a.spatialReference=g;return a});return J.apply(this,arguments)}function K(){K=h._asyncToGenerator(function*(a,b){var c;
if(null==a)throw Error("Illegal Argument Exception");const g=a.spatialReference;b=null!=(c=b)?c:H(a);a=a.constructor.fromJSON(yield e("flipVertical",[g,a,b]));a.spatialReference=g;return a});return K.apply(this,arguments)}function L(){L=h._asyncToGenerator(function*(a,b,c,g){a=yield e("generalize",[f(a),a,b,c,g]);return k(a)});return L.apply(this,arguments)}function M(){M=h._asyncToGenerator(function*(a,b,c){a=yield e("densify",[f(a),a,b,c]);return k(a)});return M.apply(this,arguments)}function N(){N=
h._asyncToGenerator(function*(a,b,c,g=0){a=yield e("geodesicDensify",[f(a),a,b,c,g]);return k(a)});return N.apply(this,arguments)}let q;d.buffer=function(a,b,c){return C.apply(this,arguments)};d.clip=function(a,b){return t.apply(this,arguments)};d.contains=function(a,b){return e("contains",[f(a),a,b])};d.convexHull=function(a){return w.apply(this,arguments)};d.crosses=function(a,b){return e("crosses",[f(a),a,b])};d.cut=function(a,b){return u.apply(this,arguments)};d.densify=function(a,b,c){return M.apply(this,
arguments)};d.difference=function(a,b){return x.apply(this,arguments)};d.disjoint=function(a,b){return e("disjoint",[f(a),a,b])};d.distance=function(a,b,c){return e("distance",[f(a),a,b,c])};d.equals=function(a,b){return e("equals",[f(a),a,b])};d.extendedSpatialReferenceInfo=function(a){return e("extendedSpatialReferenceInfo",[a])};d.flipHorizontal=function(a,b){return J.apply(this,arguments)};d.flipVertical=function(a,b){return K.apply(this,arguments)};d.generalize=function(a,b,c,g){return L.apply(this,
arguments)};d.geodesicArea=function(a,b,c){return e("geodesicArea",[f(a),a,b,c])};d.geodesicBuffer=function(a,b,c,g,l,m){return D.apply(this,arguments)};d.geodesicDensify=function(a,b,c){return N.apply(this,arguments)};d.geodesicLength=function(a,b,c){return e("geodesicLength",[f(a),a,b,c])};d.intersect=function(a,b){return z.apply(this,arguments)};d.intersects=function(a,b){return e("intersects",[f(a),a,b])};d.isSimple=function(a){return e("isSimple",[f(a),a])};d.nearestCoordinate=function(a,b){return E.apply(this,
arguments)};d.nearestVertex=function(a,b){return F.apply(this,arguments)};d.nearestVertices=function(a,b,c,g){return G.apply(this,arguments)};d.offset=function(a,b,c,g,l,m){return B.apply(this,arguments)};d.overlaps=function(a,b){return e("overlaps",[f(a),a,b])};d.planarArea=function(a,b){return e("planarArea",[f(a),a,b])};d.planarLength=function(a,b){return e("planarLength",[f(a),a,b])};d.relate=function(a,b,c){return e("relate",[f(a),a,b,c])};d.rotate=function(a,b,c){return I.apply(this,arguments)};
d.simplify=function(a){return v.apply(this,arguments)};d.symmetricDifference=function(a,b){return y.apply(this,arguments)};d.touches=function(a,b){return e("touches",[f(a),a,b])};d.union=function(a){return A.apply(this,arguments)};d.within=function(a,b){return e("within",[f(a),a,b])};Object.defineProperty(d,"__esModule",{value:!0})});