// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
/*
 tabbable 5.2.0
 @license MIT, https://github.com/focus-trap/tabbable/blob/master/LICENSE
 focus-trap 6.5.1
 @license MIT, https://github.com/focus-trap/focus-trap/blob/master/LICENSE
*/
require({cache:{"esri/identity/IdentityManagerBase":function(){define("exports ../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../config ../kernel ../request ../core/Error ../core/Evented ../core/events ../core/global ../core/lang ../core/object ../core/promiseUtils ../core/urlUtils ../core/accessorSupport/decorators/property ../core/accessorSupport/ensureType ../core/has ../core/Logger ../core/jsonMap ../core/accessorSupport/decorators/subclass ./IdentityForm ./IdentityModal ./OAuthCredential ./OAuthInfo ./ServerInfo".split(" "),
function(y,u,p,m,q,G,z,W,U,J,T,A,x,C,N,X,H,da,ma,ha,ea,S,ia,ja,Z){const aa={},ka=P=>{const Q=(new C.Url(P.owningSystemUrl)).host;P=(new C.Url(P.server)).host;const n=/.+\.arcgis\.com$/i;return n.test(Q)&&n.test(P)},na=(P,Q)=>!!(ka(P)&&Q&&Q.some(n=>n.test(P.server)));let la=null,fa=null;try{la=window.localStorage,fa=window.sessionStorage}catch{}X=function(P){function Q(){var a=P.call(this)||this;a._portalConfig=J.esriGeowConfig;a.serverInfos=[];a.oAuthInfos=[];a.credentials=[];a._soReqs=[];a._xoReqs=
[];a._portals=[];a.defaultOAuthInfo=null;a.defaultTokenValidity=60;a.dialog=null;a.formConstructor=ea;a.tokenValidity=null;a.normalizeWebTierAuth=!1;a._appOrigin="null"!==window.origin?window.origin:window.location.origin;a._appUrlObj=C.urlToObject(window.location.href);a._busy=null;a._rejectOnPersistedPageShow=!1;a._oAuthHash=null;a._gwTokenUrl="/sharing/rest/generateToken";a._agsRest="/rest/services";a._agsPortal=/\/sharing(\/|$)/i;a._agsAdmin=/(https?:\/\/[^\/]+\/[^\/]+)\/admin\/?(\/.*)?$/i;a._adminSvcs=
/\/rest\/admin\/services(\/|$)/i;a._gwDomains=[{regex:/^https?:\/\/www\.arcgis\.com/i,customBaseUrl:"maps.arcgis.com",tokenServiceUrl:"https://www.arcgis.com/sharing/rest/generateToken"},{regex:/^https?:\/\/(?:dev|[a-z\d-]+\.mapsdev)\.arcgis\.com/i,customBaseUrl:"mapsdev.arcgis.com",tokenServiceUrl:"https://dev.arcgis.com/sharing/rest/generateToken"},{regex:/^https?:\/\/(?:devext|[a-z\d-]+\.mapsdevext)\.arcgis\.com/i,customBaseUrl:"mapsdevext.arcgis.com",tokenServiceUrl:"https://devext.arcgis.com/sharing/rest/generateToken"},
{regex:/^https?:\/\/(?:qaext|[a-z\d-]+\.mapsqa)\.arcgis\.com/i,customBaseUrl:"mapsqa.arcgis.com",tokenServiceUrl:"https://qaext.arcgis.com/sharing/rest/generateToken"},{regex:/^https?:\/\/[a-z\d-]+\.maps\.arcgis\.com/i,customBaseUrl:"maps.arcgis.com",tokenServiceUrl:"https://www.arcgis.com/sharing/rest/generateToken"}];a._legacyFed=[];a._regexSDirUrl=/http.+\/rest\/services\/?/gi;a._regexServerType=/(\/(FeatureServer|GPServer|GeoDataServer|GeocodeServer|GeoenrichmentServer|GeometryServer|GlobeServer|ImageServer|MapServer|MobileServer|NAServer|NetworkDiagramServer|OGCFeatureServer|ParcelFabricServer|RelationalCatalogServer|SceneServer|StreamServer|UtilityNetworkServer|ValidationServer|VectorTileServer|VersionManagementServer)).*/gi;
a._gwUser=/http.+\/users\/([^\/]+)\/?.*/i;a._gwItem=/http.+\/items\/([^\/]+)\/?.*/i;a._gwGroup=/http.+\/groups\/([^\/]+)\/?.*/i;a._rePortalTokenSvc=/\/sharing(\/rest)?\/generatetoken/i;a._createDefaultOAuthInfo=!0;a._hasTestedIfAppIsOnPortal=!1;a._getOAuthHash();window.addEventListener("pageshow",b=>{a._pageShowHandler(b)});return a}u._inheritsLoose(Q,P);var n=Q.prototype;n.registerServers=function(a){const b=this.serverInfos;b?(a=a.filter(c=>!this.findServerInfo(c.server)),this.serverInfos=b.concat(a)):
this.serverInfos=a;a.forEach(c=>{c.owningSystemUrl&&this._portals.push(c.owningSystemUrl);c.hasPortal&&this._portals.push(c.server)})};n.registerOAuthInfos=function(a){const b=this.oAuthInfos;if(b){for(const c of a){const d=this.findOAuthInfo(c.portalUrl);d&&b.splice(b.indexOf(d),1)}this.oAuthInfos=b.concat(a)}else this.oAuthInfos=a};n.registerToken=function(a){a={...a};const b=this._sanitizeUrl(a.server),c=this._isServerRsrc(b);let d=this.findServerInfo(b),e=!0,g;d||(d=new Z,d.server=this._getServerInstanceRoot(b),
c?d.hasServer=!0:(d.tokenServiceUrl=this._getTokenSvcUrl(b),d.hasPortal=!0),this.registerServers([d]));(g=this._findCredential(b))?(delete a.server,Object.assign(g,a),e=!1):(g=new y.Credential({userId:a.userId,server:d.server,token:a.token,expires:a.expires,ssl:a.ssl,scope:c?"server":"portal"}),g.resources=[b],this.credentials.push(g));g.emitTokenChange(!1);e||g.refreshServerTokens()};n.toJSON=function(){return T.fixJson({serverInfos:this.serverInfos.map(a=>a.toJSON()),oAuthInfos:this.oAuthInfos.map(a=>
a.toJSON()),credentials:this.credentials.map(a=>a.toJSON())})};n.initialize=function(a){if(a){"string"===typeof a&&(a=JSON.parse(a));var b=a.serverInfos,c=a.oAuthInfos;a=a.credentials;if(b){const d=[];b.forEach(e=>{e.server&&e.tokenServiceUrl&&d.push(e.declaredClass?e:new Z(e))});d.length&&this.registerServers(d)}if(c){const d=[];c.forEach(e=>{e.appId&&d.push(e.declaredClass?e:new ja(e))});d.length&&this.registerOAuthInfos(d)}a&&a.forEach(d=>{d.server&&d.token&&d.expires&&d.expires>Date.now()&&(d=
d.declaredClass?d:new y.Credential(d),d.emitTokenChange(),this.credentials.push(d))})}};n.findServerInfo=function(a){let b;a=this._sanitizeUrl(a);for(const c of this.serverInfos)if(this._hasSameServerInstance(c.server,a)){b=c;break}return b};n.findOAuthInfo=function(a){let b;a=this._sanitizeUrl(a);for(const c of this.oAuthInfos)if(this._hasSameServerInstance(c.portalUrl,a)){b=c;break}return b};n.findCredential=function(a,b){let c;a=this._sanitizeUrl(a);const d=this._isServerRsrc(a)?"server":"portal";
if(b)for(const e of this.credentials){if(this._hasSameServerInstance(e.server,a)&&b===e.userId&&e.scope===d){c=e;break}}else for(const e of this.credentials)if(this._hasSameServerInstance(e.server,a)&&-1!==this._getIdenticalSvcIdx(a,e)&&e.scope===d){c=e;break}return c};n.getCredential=function(a,b){let c=!0;if(b){var d=!!b.token;var e=b.error;c=!1!==b.prompt}b={...b};a=this._sanitizeUrl(a);const g=x.createAbortController(),h=x.createResolver();if(b.signal)x.onAbort(b.signal,()=>{g.abort()});x.onAbort(g,
()=>{h.reject(new z("identity-manager:user-aborted","ABORTED"))});if(x.isAborted(g))return h.promise;b.signal=g.signal;const t=this._isAdminResource(a);if((d=d?this.findCredential(a):null)&&e&&e.details&&498===e.details.httpStatus)d.destroy();else if(d)return a=new z("identity-manager:not-authorized","You are currently signed in as: '"+d.userId+"'. You do not have access to this resource: "+a,{error:e}),h.reject(a),h.promise;if(e=this._findCredential(a,b))return h.resolve(e),h.promise;let f=this.findServerInfo(a);
if(f)!f.hasServer&&this._isServerRsrc(a)&&(f._restInfoPms=this._getTokenSvcUrl(a),f.hasServer=!0);else{e=this._getTokenSvcUrl(a);if(!e)return a=new z("identity-manager:unknown-resource","Unknown resource - could not find token service endpoint."),h.reject(a),h.promise;f=new Z;f.server=this._getServerInstanceRoot(a);"string"===typeof e?(f.tokenServiceUrl=e,f.hasPortal=!0):(f._restInfoPms=e,f.hasServer=!0);this.registerServers([f])}f.hasPortal&&void 0===f._selfReq&&(c||C.hasSameOrigin(f.tokenServiceUrl,
this._appOrigin)||this._gwDomains.some(k=>k.tokenServiceUrl===f.tokenServiceUrl))&&(f._selfReq={owningTenant:b&&b.owningTenant,selfDfd:this._getPortalSelf(f.tokenServiceUrl.replace(this._rePortalTokenSvc,"/sharing/rest/portals/self"),a)});return this._enqueue(a,f,b,h,t)};n.getResourceName=function(a){return this._isRESTService(a)?a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"")||"":this._gwUser.test(a)&&a.replace(this._gwUser,"$1")||this._gwItem.test(a)&&a.replace(this._gwItem,"$1")||
this._gwGroup.test(a)&&a.replace(this._gwGroup,"$1")||""};n.generateToken=function(a,b,c){const d=this._rePortalTokenSvc.test(a.tokenServiceUrl),e=new C.Url(this._appOrigin);var g=a.shortLivedTokenValidity;let h,t,f,k,v,r,E;b&&(E=this.tokenValidity||g||this.defaultTokenValidity,E>g&&0<g&&(E=g));c&&(h=c.isAdmin,t=c.serverUrl,f=c.token,v=c.signal,r=c.ssl,a.customParameters=c.customParameters);h?g=a.adminTokenServiceUrl:(g=a.tokenServiceUrl,k=new C.Url(g.toLowerCase()),a.webTierAuth&&null!=c&&c.serverUrl&&
!r&&"http"===e.scheme&&(C.hasSameOrigin(e.uri,g,!0)||"https"===k.scheme&&e.host===k.host&&"7080"===e.port&&"7443"===k.port)&&(g=g.replace(/^https:/i,"http:").replace(/:7443/i,":7080")));c={query:{request:"getToken",username:null==b?void 0:b.username,password:null==b?void 0:b.password,serverUrl:t,token:f,expiration:E,referer:h||d?this._appOrigin:null,client:h?"referer":null,f:"json",...a.customParameters},method:"post",authMode:"anonymous",useProxy:this._useProxy(a,c),signal:v,...null==c?void 0:c.ioArgs};
d||(c.withCredentials=!1);return G(g,c).then(D=>{D=D.data;if(!D||!D.token)return new z("identity-manager:authentication-failed","Unable to generate token");const w=a.server;aa[w]||(aa[w]={});b&&(aa[w][b.username]=b.password);D.validity=E;return D})};n.isBusy=function(){return!!this._busy};n.checkSignInStatus=function(a){return this.checkAppAccess(a,"").then(b=>b.credential)};n.checkAppAccess=function(a,b,c){let d=!1;return this.getCredential(a,{prompt:!1}).then(e=>{let g;const h={f:"json"};if("portal"===
e.scope)if(b&&(this._doPortalSignIn(a)||c&&c.force))g=e.server+"/sharing/rest/oauth2/validateAppAccess",h.client_id=b;else if(e.token)g=e.server+"/sharing/rest";else return{credential:e};else if(e.token)g=e.server+"/rest/services";else return{credential:e};e.token&&(h.token=e.token);return G(g,{query:h,authMode:"anonymous"}).then(t=>{if(!1===t.data.valid)throw new z("identity-manager:not-authorized",`You are currently signed in as: '${e.userId}'.`,t.data);d=!!t.data.viewOnlyUserTypeApp;return{credential:e}}).catch(t=>
{if("identity-manager:not-authorized"===t.name)throw t;t=t.details&&t.details.httpStatus;if(498===t)throw e.destroy(),new z("identity-manager:not-authenticated","User is not signed in.");if(400===t)throw new z("identity-manager:invalid-request");return{credential:e}})}).then(e=>({credential:e.credential,viewOnly:d}))};n.setOAuthResponseHash=function(a){var b;const c=this._oAuthDfd;this._oAuthDfd=null;if(c&&a)if(clearInterval(this._oAuthIntervalId),null==(b=this._oAuthOnHashHandle)?void 0:b.remove(),
"#"===a.charAt(0)&&(a=a.substring(1)),a=C.queryToObject(a),a.error)b="access_denied"===a.error,a=new z(b?"identity-manager:user-aborted":"identity-manager:authentication-failed",b?"ABORTED":"OAuth: "+a.error+" - "+a.error_description),c.reject(a);else{b=c.oinfo_;const d=b._oAuthCred,e=new y.Credential({userId:a.username,server:c.sinfo_.server,token:a.access_token,expires:Date.now()+1E3*Number(a.expires_in),ssl:"true"===a.ssl,_oAuthCred:d});b.userId=e.userId;d.storage=a.persist?la:fa;d.token=e.token;
d.expires=e.expires;d.userId=e.userId;d.ssl=e.ssl;d.save();c.resolve(e)}};n.setOAuthRedirectionHandler=function(a){this._oAuthRedirectFunc=a};n.setProtocolErrorHandler=function(a){this._protocolFunc=a};n.signIn=function(a,b,c={}){const d=x.createResolver(),e=()=>{var v,r,E,D,w;null==(v=t)?void 0:v.remove();null==(r=f)?void 0:r.remove();null==(E=k)?void 0:E.remove();null==(D=h)?void 0:D.destroy();null==(w=this.dialog)?void 0:w.destroy();this.dialog=h=t=f=k=null},g=()=>{e();this._oAuthDfd=null;d.reject(new z("identity-manager:user-aborted",
"ABORTED"))};if(c.signal)x.onAbort(c.signal,()=>{g()});let h=new this.formConstructor;h.resource=this.getResourceName(a);h.server=b.server;this.dialog=new S;this.dialog.content=h;this.dialog.open=!0;this.emit("dialog-create");let t=h.on("cancel",g),f=this.dialog.watch("open",g),k=h.on("submit",v=>{this.generateToken(b,v,{isAdmin:c.isAdmin,signal:c.signal}).then(r=>{e();r=new y.Credential({userId:v.username,server:b.server,token:r.token,expires:null!=r.expires?Number(r.expires):null,ssl:!!r.ssl,isAdmin:c.isAdmin,
validity:r.validity});d.resolve(r)}).catch(r=>{h.error=r;h.signingIn=!1})});return d.promise};n.oAuthSignIn=function(a,b,c,d){const e=this._oAuthDfd=x.createResolver();if(null!=d&&d.signal)x.onAbort(d.signal,()=>{const r=this._oAuthDfd&&this._oAuthDfd.oAuthWin_;r&&!r.closed?r.close():this.dialog&&h()});e.resUrl_=a;e.sinfo_=b;e.oinfo_=c;d=!d||!1!==d.oAuthPopupConfirmation;if(!c.popup||!d)return this._doOAuthSignIn(a,b,c),e.promise;const g=new this.formConstructor;g.oAuthPrompt=!0;g.server=b.server;
this.dialog=new S;this.dialog.content=g;this.dialog.open=!0;this.emit("dialog-create");const h=()=>{v();this._oAuthDfd=null;e.reject(new z("identity-manager:user-aborted","ABORTED"))},t=g.on("cancel",h),f=this.dialog.watch("open",h),k=g.on("submit",()=>{v();this._doOAuthSignIn(a,b,c)}),v=()=>{t.remove();f.remove();k.remove();g.destroy();this.dialog.destroy();this.dialog=null};return e.promise};n.destroyCredentials=function(){this.credentials&&this.credentials.slice().forEach(a=>{a.destroy()});this.emit("credentials-destroy")};
n.enablePostMessageAuth=function(a="https://www.arcgis.com/sharing/rest"){this._postMessageAuthHandle&&this._postMessageAuthHandle.remove();this._postMessageAuthHandle=U.on(window,"message",b=>{var c;if((b.origin===this._appOrigin||b.origin.endsWith(".arcgis.com"))&&"arcgis:auth:requestCredential"===(null==(c=b.data)?void 0:c.type)){const d=b.source;this.getCredential(a).then(e=>{d.postMessage({type:"arcgis:auth:credential",credential:{expires:e.expires,server:e.server,ssl:e.ssl,token:e.token,userId:e.userId}},
b.origin)}).catch(e=>{d.postMessage({type:"arcgis:auth:error",error:{name:e.name,message:e.message}},b.origin)})}})};n.disablePostMessageAuth=function(){this._postMessageAuthHandle&&(this._postMessageAuthHandle.remove(),this._postMessageAuthHandle=null)};n._getOAuthHash=function(){var a=window.location.hash;if(a){"#"===a.charAt(0)&&(a=a.substring(1));a=C.queryToObject(a);let b=!1;if(a.access_token&&a.expires_in&&a.state&&a.hasOwnProperty("username"))try{a.state=JSON.parse(a.state),"object"===typeof a.state&&
a.state.portalUrl&&(this._oAuthHash=a,b=!0)}catch{}else a.error&&a.error_description&&(console.log("IdentityManager OAuth Error: ",a.error," - ",a.error_description),"access_denied"===a.error&&(b=!0));b&&(window.location.hash="object"===typeof a.state&&a.state.hash||"")}};n._pageShowHandler=function(a){a.persisted&&this.isBusy()&&this._rejectOnPersistedPageShow&&(a=new z("identity-manager:user-aborted","ABORTED"),this._errbackFunc(a))};n._findCredential=function(a,b){let c=-1,d,e,g;const h=b&&b.token;
b=b&&b.resource;const t=this._isServerRsrc(a)?"server":"portal",f=this.credentials.filter(k=>this._hasSameServerInstance(k.server,a)&&k.scope===t);a=b||a;if(f.length)if(1===f.length)if(b=f[0],e=(d=(g=this.findServerInfo(b.server))&&g.owningSystemUrl)&&this.findCredential(d,b.userId),c=this._getIdenticalSvcIdx(a,b),h)-1!==c&&(b.resources.splice(c,1),this._removeResource(a,e));else return-1===c&&b.resources.push(a),this._addResource(a,e),b;else{let k,v;f.some(r=>{v=this._getIdenticalSvcIdx(a,r);return-1!==
v?(k=r,e=(d=(g=this.findServerInfo(k.server))&&g.owningSystemUrl)&&this.findCredential(d,k.userId),c=v,!0):!1});if(h)k&&(k.resources.splice(c,1),this._removeResource(a,e));else if(k)return this._addResource(a,e),k}};n._findOAuthInfo=function(a){let b=this.findOAuthInfo(a);if(!b)for(const c of this.oAuthInfos)if(this._isIdProvider(c.portalUrl,a)){b=c;break}return b};n._addResource=function(a,b){b&&-1===this._getIdenticalSvcIdx(a,b)&&b.resources.push(a)};n._removeResource=function(a,b){let c=-1;b&&
(c=this._getIdenticalSvcIdx(a,b),-1<c&&b.resources.splice(c,1))};n._useProxy=function(a,b){return b&&b.isAdmin&&!C.hasSameOrigin(a.adminTokenServiceUrl,this._appOrigin)||!this._isPortalDomain(a.tokenServiceUrl)&&"10.1"===String(a.currentVersion)&&!C.hasSameOrigin(a.tokenServiceUrl,this._appOrigin)};n._getOrigin=function(a){a=new C.Url(a);return a.scheme+"://"+a.host+(null!=a.port?":"+a.port:"")};n._getServerInstanceRoot=function(a){const b=a.toLowerCase();let c=b.indexOf(this._agsRest);-1===c&&this._isAdminResource(a)&&
(c=this._agsAdmin.test(a)?a.replace(this._agsAdmin,"$1").length:a.search(this._adminSvcs));-1===c&&(c=b.indexOf("/sharing"));-1===c&&"/"===b.substr(-1)&&(c=b.length-1);return-1<c?a.substring(0,c):a};n._hasSameServerInstance=function(a,b){"/"===a.substr(-1)&&(a=a.slice(0,-1));a=a.toLowerCase();b=this._getServerInstanceRoot(b).toLowerCase();a=this._normalizeAGOLorgDomain(a);b=this._normalizeAGOLorgDomain(b);a=a.substr(a.indexOf(":"));b=b.substr(b.indexOf(":"));return a===b};n._normalizeAGOLorgDomain=
function(a){const b=/^https?:\/\/(?:cdn|[a-z\d-]+\.maps)\.arcgis\.com/i,c=/^https?:\/\/(?:cdndev|[a-z\d-]+\.mapsdevext)\.arcgis\.com/i,d=/^https?:\/\/(?:cdnqa|[a-z\d-]+\.mapsqa)\.arcgis\.com/i;b.test(a)?a=a.replace(b,"https://www.arcgis.com"):c.test(a)?a=a.replace(c,"https://devext.arcgis.com"):d.test(a)&&(a=a.replace(d,"https://qaext.arcgis.com"));return a};n._sanitizeUrl=function(a){const b=(m.request.proxyUrl||"").toLowerCase(),c=b?a.toLowerCase().indexOf(b+"?"):-1;-1!==c&&(a=a.substring(c+b.length+
1));a=C.normalize(a);return C.urlToObject(a).path};n._isRESTService=function(a){return-1<a.indexOf(this._agsRest)};n._isAdminResource=function(a){return this._agsAdmin.test(a)||this._adminSvcs.test(a)};n._isServerRsrc=function(a){return this._isRESTService(a)||this._isAdminResource(a)};n._isIdenticalService=function(a,b){if(this._isRESTService(a)&&this._isRESTService(b)){a=this._getSuffix(a).toLowerCase();b=this._getSuffix(b).toLowerCase();var c=a===b;c||(c=/(.*)\/(MapServer|FeatureServer|UtilityNetworkServer).*/gi,
c=a.replace(c,"$1")===b.replace(c,"$1"))}else this._isAdminResource(a)&&this._isAdminResource(b)?c=!0:this._isServerRsrc(a)||this._isServerRsrc(b)||!this._isPortalDomain(a)||(c=!0);return c};n._isPortalDomain=function(a){const b=new C.Url(a.toLowerCase());a=this._portalConfig;let c=this._gwDomains.some(d=>d.regex.test(b.uri));!c&&a&&(c=this._hasSameServerInstance(this._getServerInstanceRoot(a.restBaseUrl),b.uri));c||m.portalUrl&&(c=C.hasSameOrigin(b,m.portalUrl,!0));c||(c=this._portals.some(d=>this._hasSameServerInstance(d,
b.uri)));return c=c||this._agsPortal.test(b.path)};n._isIdProvider=function(a,b){let c=-1,d=-1;this._gwDomains.forEach((g,h)=>{-1===c&&g.regex.test(a)&&(c=h);-1===d&&g.regex.test(b)&&(d=h)});let e=!1;if(-1<c&&-1<d)if(0===c||4===c){if(0===d||4===d)e=!0}else if(1===c){if(1===d||2===d)e=!0}else 2===c?2===d&&(e=!0):3===c&&3===d&&(e=!0);if(!e){const g=this.findServerInfo(b),h=g&&g.owningSystemUrl;h&&ka(g)&&this._isPortalDomain(h)&&this._isIdProvider(a,h)&&(e=!0)}return e};n._getIdenticalSvcIdx=function(a,
b){let c=-1;for(let d=0;d<b.resources.length;d++)if(this._isIdenticalService(a,b.resources[d])){c=d;break}return c};n._getSuffix=function(a){return a.replace(this._regexSDirUrl,"").replace(this._regexServerType,"$1")};n._getTokenSvcUrl=function(a){if(this._isRESTService(a)||this._isAdminResource(a)){var b=this._getServerInstanceRoot(a);var c=b+"/admin/generateToken";a=b+"/rest/info";b=G(a,{query:{f:"json"}}).then(d=>d.data);return{adminUrl:c,promise:b}}if(this._isPortalDomain(a)){let d="";this._gwDomains.some(e=>
{e.regex.test(a)&&(d=e.tokenServiceUrl);return!!d});d||this._portals.some(e=>{this._hasSameServerInstance(e,a)&&(d=e+this._gwTokenUrl);return!!d});d||(c=a.toLowerCase().indexOf("/sharing"),-1!==c&&(d=a.substring(0,c)+this._gwTokenUrl));d||(d=this._getOrigin(a)+this._gwTokenUrl);d&&(c=(new C.Url(a)).port,/^http:\/\//i.test(a)&&"7080"===c&&(d=d.replace(/:7080/i,":7443")),d=d.replace(/http:/i,"https:"));return d}if(-1!==a.toLowerCase().indexOf("premium.arcgisonline.com"))return"https://premium.arcgisonline.com/server/tokens"};
n._exchangeToken=function(a,b,c){return G(`${a}/sharing/rest/oauth2/exchangeToken`,{authMode:"anonymous",method:"post",query:{f:"json",client_id:b,token:c}}).then(d=>d.data.token)};n._getPlatformSelf=function(a,b){return G(`${a}/sharing/rest/oauth2/platformSelf`,{authMode:"anonymous",headers:{"X-Esri-Auth-Client-Id":b,"X-Esri-Auth-Redirect-Uri":window.location.href.replace(/#.*$/,"")},method:"post",query:{f:"json"},withCredentials:!0}).then(c=>c.data)};n._getPortalSelf=function(a,b){let c;this._gwDomains.some(d=>
{d.regex.test(a)&&(c=d.customBaseUrl);return!!c});if(c)return Promise.resolve({allSSL:!0,currentVersion:"4.4",customBaseUrl:c,portalMode:"multitenant",supportsOAuth:!0});this._appOrigin.startsWith("https:")?a=a.replace(/^http:/i,"https:").replace(/:7080/i,":7443"):/^http:/i.test(b)&&(a=a.replace(/^https:/i,"http:").replace(/:7443/i,":7080"));return G(a,{query:{f:"json"},authMode:"anonymous",withCredentials:!0}).then(d=>d.data)};n._doPortalSignIn=function(a){const b=this._portalConfig,c=window.location.href,
d=this.findServerInfo(a);return(b||this._isPortalDomain(c))&&(d?d.hasPortal||d.owningSystemUrl&&this._isPortalDomain(d.owningSystemUrl):this._isPortalDomain(a))&&(this._isIdProvider(c,a)||b&&(this._hasSameServerInstance(this._getServerInstanceRoot(b.restBaseUrl),a)||this._isIdProvider(b.restBaseUrl,a))||C.hasSameOrigin(c,a,!0))?!0:!1};n._checkProtocol=function(a,b,c,d){let e=!0;d=d?b.adminTokenServiceUrl:b.tokenServiceUrl;d.trim().toLowerCase().startsWith("https:")&&!this._appOrigin.startsWith("https:")&&
C.getProxyRule(d)&&(e=this._protocolFunc?!!this._protocolFunc({resourceUrl:a,serverInfo:b}):!1,e||(a=new z("identity-manager:aborted","Aborted the Sign-In process to avoid sending password over insecure connection."),c(a)));return e};n._enqueue=function(a,b,c,d,e,g){d||(d=x.createResolver());d.resUrl_=a;d.sinfo_=b;d.options_=c;d.admin_=e;d.refresh_=g;this._busy?this._hasSameServerInstance(this._getServerInstanceRoot(a),this._busy.resUrl_)?(this._oAuthDfd&&this._oAuthDfd.oAuthWin_&&this._oAuthDfd.oAuthWin_.focus(),
this._soReqs.push(d)):this._xoReqs.push(d):this._doSignIn(d);return d.promise};n._doSignIn=function(a){this._busy=a;this._rejectOnPersistedPageShow=!1;const b=f=>{var k=a.options_&&a.options_.resource;const v=a.resUrl_,r=a.refresh_;let E=!1;-1===this.credentials.indexOf(f)&&(r&&-1!==this.credentials.indexOf(r)?(r.userId=f.userId,r.token=f.token,r.expires=f.expires,r.validity=f.validity,r.ssl=f.ssl,r.creationTime=f.creationTime,E=!0,f=r):this.credentials.push(f));f.resources||(f.resources=[]);f.resources.push(k||
v);f.scope=this._isServerRsrc(v)?"server":"portal";f.emitTokenChange();k=this._soReqs;const D={};this._soReqs=[];k.forEach(w=>{if(!this._isIdenticalService(v,w.resUrl_)){const I=this._getSuffix(w.resUrl_);D[I]||(D[I]=!0,f.resources.push(w.resUrl_))}});a.resolve(f);k.forEach(w=>{this._hasSameServerInstance(this._getServerInstanceRoot(v),w.resUrl_)?w.resolve(f):this._soReqs.push(w)});this._busy=a.resUrl_=a.sinfo_=a.refresh_=null;E||this.emit("credential-create",{credential:f});this._soReqs.length?this._doSignIn(this._soReqs.shift()):
this._xoReqs.length&&this._doSignIn(this._xoReqs.shift())},c=f=>{a.reject(f);this._busy=a.resUrl_=a.sinfo_=a.refresh_=null;this._soReqs.length?this._doSignIn(this._soReqs.shift()):this._xoReqs.length&&this._doSignIn(this._xoReqs.shift())},d=(f,k,v,r)=>{var E,D;const w=a.sinfo_,I=!a.options_||!1!==a.options_.prompt,O=w.hasPortal&&this._findOAuthInfo(a.resUrl_);let L,Y;if(f)b(new y.Credential({userId:f,server:w.server,token:v||null,expires:null!=r?Number(r):null,ssl:!!k}));else if(window!==window.parent&&
null!=(E=this._appUrlObj.query)&&E["arcgis-auth-origin"]&&null!=(D=this._appUrlObj.query)&&D["arcgis-auth-portal"]&&this._hasSameServerInstance(this._getServerInstanceRoot(this._appUrlObj.query["arcgis-auth-portal"]),a.resUrl_)){var oa;window.parent.postMessage({type:"arcgis:auth:requestCredential"},this._appUrlObj.query["arcgis-auth-origin"]);const F=U.on(window,"message",R=>{R.source===window.parent&&R.data&&("arcgis:auth:credential"===R.data.type?(F.remove(),b(new y.Credential(R.data.credential))):
"arcgis:auth:error"===R.data.type&&(F.remove(),c(z.fromJSON(R.data.error))))});x.onAbort(null==(oa=a.options_)?void 0:oa.signal,()=>{F.remove()})}else if(O){let F=O._oAuthCred;F||(f=new ia(O,la),k=new ia(O,fa),f.isValid()&&k.isValid()?f.expires>k.expires?(F=f,k.destroy()):(F=k,f.destroy()):F=f.isValid()?f:k,O._oAuthCred=F);if(F.isValid())L=new y.Credential({userId:F.userId,server:w.server,token:F.token,expires:F.expires,ssl:F.ssl,_oAuthCred:F}),O.appId!==F.appId&&this._doPortalSignIn(a.resUrl_)?a._pendingDfd=
this._exchangeToken(L.server,O.appId,L.token).then(R=>{L.token=R;F.token=R;F.save();b(L)}).catch(()=>{b(L)}):b(L);else if(this._oAuthHash&&this._hasSameServerInstance(O.portalUrl,this._oAuthHash.state.portalUrl))f=this._oAuthHash,L=new y.Credential({userId:f.username,server:w.server,token:f.access_token,expires:Date.now()+1E3*Number(f.expires_in),ssl:"true"===f.ssl,oAuthState:f.state,_oAuthCred:F}),O.userId=L.userId,F.storage=f.persist?la:fa,F.token=L.token,F.expires=L.expires,F.userId=L.userId,F.ssl=
L.ssl,F.save(),this._oAuthHash=null,b(L);else{const R=()=>{I?a._pendingDfd=this.oAuthSignIn(a.resUrl_,w,O,a.options_).then(b,c):(Y=new z("identity-manager:not-authenticated","User is not signed in."),c(Y))};this._doPortalSignIn(a.resUrl_)?a._pendingDfd=this._getPlatformSelf(w.server,O.appId).then(({portalUrl:pa,token:qa,username:ra})=>{!pa||C.hasSameOrigin(pa,this._appOrigin,!0)?(L=new y.Credential({server:w.server,userId:ra,token:qa}),b(L)):R()}).catch(R):R()}}else I?this._checkProtocol(a.resUrl_,
w,c,a.admin_)&&(f=a.options_,a.admin_&&(f=f||{},f.isAdmin=!0),a._pendingDfd=this.signIn(a.resUrl_,w,f).then(b,c)):(Y=new z("identity-manager:not-authenticated","User is not signed in."),c(Y))},e=()=>{const f=a.sinfo_;var k=f.owningSystemUrl;const v=a.options_;let r,E,D,w;v&&(r=v.token,E=v.error,D=v.prompt);w=this._findCredential(k,{token:r,resource:a.resUrl_});if(!w)for(const I of this.credentials)if(this._isIdProvider(k,I.server)){w=I;break}w?(k=this.findCredential(a.resUrl_,w.userId))?b(k):na(f,
this._legacyFed)?(k=w.toJSON(),k.server=f.server,k.resources=null,b(new y.Credential(k))):(a._pendingDfd=this.generateToken(this.findServerInfo(w.server),null,{serverUrl:a.resUrl_,token:w.token,signal:a.options_.signal,ssl:w.ssl})).then(I=>{b(new y.Credential({userId:w.userId,server:f.server,token:I.token,expires:null!=I.expires?Number(I.expires):null,ssl:!!I.ssl,isAdmin:a.admin_,validity:I.validity}))},c):(this._busy=null,r&&(a.options_.token=null),(a._pendingDfd=this.getCredential(k.replace(/\/?$/,
"/sharing"),{resource:a.resUrl_,owningTenant:f.owningTenant,signal:a.options_.signal,token:r,error:E,prompt:D})).then(()=>{this._enqueue(a.resUrl_,a.sinfo_,a.options_,a,a.admin_)},I=>{c(I)}))};this._errbackFunc=c;const g=a.sinfo_.owningSystemUrl,h=this._isServerRsrc(a.resUrl_),t=a.sinfo_._restInfoPms;t?t.promise.then(f=>{const k=a.sinfo_;k._restInfoPms&&(k.adminTokenServiceUrl=k._restInfoPms.adminUrl,k._restInfoPms=null,k.tokenServiceUrl=A.getDeepValue("authInfo.tokenServicesUrl",f)||A.getDeepValue("authInfo.tokenServiceUrl",
f)||A.getDeepValue("tokenServiceUrl",f),k.shortLivedTokenValidity=A.getDeepValue("authInfo.shortLivedTokenValidity",f),k.currentVersion=f.currentVersion,k.owningTenant=f.owningTenant,(f=k.owningSystemUrl=f.owningSystemUrl)&&this._portals.push(f));h&&k.owningSystemUrl?e():d()},()=>{a.sinfo_._restInfoPms=null;const f=new z("identity-manager:server-identification-failed","Unknown resource - could not find token service endpoint.");c(f)}):h&&g?e():a.sinfo_._selfReq?a.sinfo_._selfReq.selfDfd.then(f=>{const k=
{};let v,r,E,D;f&&(v=f.user&&f.user.username,k.username=v,k.allSSL=f.allSSL,r=f.supportsOAuth,E=f.currentVersion,"multitenant"===f.portalMode&&(D=f.customBaseUrl));a.sinfo_.webTierAuth=!!v;return v&&this.normalizeWebTierAuth?this.generateToken(a.sinfo_,null,{ssl:k.allSSL}).catch(()=>null).then(w=>{k.portalToken=w&&w.token;k.tokenExpiration=w&&w.expires;return k}):!v&&r&&4.4<=parseFloat(E)&&!this._findOAuthInfo(a.resUrl_)?this._generateOAuthInfo({portalUrl:a.sinfo_.server,customBaseUrl:D,owningTenant:a.sinfo_._selfReq.owningTenant}).catch(()=>
null).then(()=>k):k}).catch(()=>null).then(f=>{a.sinfo_._selfReq=null;f?d(f.username,f.allSSL,f.portalToken,f.tokenExpiration):d()}):d()};n._generateOAuthInfo=function(a){let b,c=a.portalUrl;const d=a.customBaseUrl,e=a.owningTenant;if(a=!this.defaultOAuthInfo&&this._createDefaultOAuthInfo&&!this._hasTestedIfAppIsOnPortal){b=window.location.href;let g=b.indexOf("?");-1<g&&(b=b.slice(0,g));g=b.search(/\/(apps|home)\//);b=-1<g?b.slice(0,g):null}a&&b?(this._hasTestedIfAppIsOnPortal=!0,a=G(b+"/sharing/rest",
{query:{f:"json"}}).then(()=>{this.defaultOAuthInfo=new ja({appId:"arcgisonline",popupCallbackUrl:b+"/home/oauth-callback.html"})})):a=Promise.resolve();return a.then(()=>{if(this.defaultOAuthInfo)return c=c.replace(/^http:/i,"https:"),G(c+"/sharing/rest/oauth2/validateRedirectUri",{query:{accountId:e,client_id:this.defaultOAuthInfo.appId,redirect_uri:C.makeAbsolute(this.defaultOAuthInfo.popupCallbackUrl),f:"json"}}).then(g=>{if(g.data.valid){const h=this.defaultOAuthInfo.clone();h.portalUrl=g.data.urlKey&&
d?"https://"+g.data.urlKey.toLowerCase()+"."+d:c;h.popup=window!==window.top||!(C.hasSameOrigin(c,this._appOrigin)||this._gwDomains.some(t=>t.regex.test(c)&&t.regex.test(this._appOrigin)));this.oAuthInfos.push(h)}})})};n._doOAuthSignIn=function(a,b,c){var d={portalUrl:c.portalUrl};!c.popup&&c.preserveUrlHash&&window.location.hash&&(d.hash=window.location.hash);d={client_id:c.appId,response_type:"token",state:JSON.stringify(d),expiration:c.expiration,locale:c.locale,redirect_uri:c.popup?C.makeAbsolute(c.popupCallbackUrl):
window.location.href.replace(/#.*$/,"")};c.forceLogin&&(d.force_login=!0);c.forceUserId&&c.userId&&(d.prepopulatedusername=c.userId);!c.popup&&this._doPortalSignIn(a)&&(d.redirectToUserOrgUrl=!0);const e=c.portalUrl.replace(/^http:/i,"https:")+"/sharing/oauth2/authorize",g=e+"?"+C.objectToQuery(d);if(c.popup){const h=window.open(g,"esriJSAPIOAuth",c.popupWindowFeatures);h?(h.focus(),this._oAuthDfd.oAuthWin_=h,this._oAuthIntervalId=setInterval(()=>{if(h.closed){clearInterval(this._oAuthIntervalId);
this._oAuthOnHashHandle.remove();const t=this._oAuthDfd;if(t){const f=new z("identity-manager:user-aborted","ABORTED");t.reject(f)}}},500),this._oAuthOnHashHandle=U.on(J,"arcgis:auth:hash",t=>{this.setOAuthResponseHash(t.detail)})):(a=new z("identity-manager:popup-blocked","ABORTED"),this._oAuthDfd.reject(a))}else this._rejectOnPersistedPageShow=!0,this._oAuthRedirectFunc?this._oAuthRedirectFunc({authorizeParams:d,authorizeUrl:e,resourceUrl:a,serverInfo:b,oAuthInfo:c}):window.location.href=g};return Q}(W);
X.prototype.declaredClass="esri.identity.IdentityManagerBase";y.Credential=function(P){function Q(a){var b=P.call(this,a)||this;b._oAuthCred=null;b.tokenRefreshBuffer=2;a&&a._oAuthCred&&(b._oAuthCred=a._oAuthCred);return b}u._inheritsLoose(Q,P);var n=Q.prototype;n.initialize=function(){this.resources=this.resources||[];null==this.creationTime&&(this.creationTime=Date.now())};n.refreshToken=function(){const a=q.id.findServerInfo(this.server),b=a&&a.owningSystemUrl,c=!!b&&"server"===this.scope,d=c&&
na(a,q.id._legacyFed);var e=a.webTierAuth;const g=e&&q.id.normalizeWebTierAuth;var h=aa[this.server];h=h&&h[this.userId];let t=this.resources&&this.resources[0],f=c&&q.id.findServerInfo(b),k={username:this.userId,password:h},v;if(!e||g)if(c&&!f&&q.id.serverInfos.some(r=>{q.id._isIdProvider(b,r.server)&&(f=r);return!!f}),e=f&&q.id.findCredential(f.server,this.userId),!c||e)if(d)e.refreshToken();else{if(c)v={serverUrl:t,token:e&&e.token,ssl:e&&e.ssl};else if(g)k=null,v={ssl:this.ssl};else if(h)this.isAdmin&&
(v={isAdmin:!0});else{let r;t&&(t=q.id._sanitizeUrl(t),this._enqueued=1,r=q.id._enqueue(t,a,null,null,this.isAdmin,this),r.then(()=>{this._enqueued=0;this.refreshServerTokens()}).catch(()=>{this._enqueued=0}));return r}return q.id.generateToken(c?f:a,c?null:k,v).then(r=>{this.token=r.token;this.expires=null!=r.expires?Number(r.expires):null;this.creationTime=Date.now();this.validity=r.validity;this.emitTokenChange();this.refreshServerTokens()}).catch(()=>{})}};n.refreshServerTokens=function(){"portal"===
this.scope&&q.id.credentials.forEach(a=>{const b=q.id.findServerInfo(a.server),c=b&&b.owningSystemUrl;a!==this&&a.userId===this.userId&&c&&"server"===a.scope&&(q.id._hasSameServerInstance(this.server,c)||q.id._isIdProvider(c,this.server))&&(na(b,q.id._legacyFed)?(a.token=this.token,a.expires=this.expires,a.creationTime=this.creationTime,a.validity=this.validity,a.emitTokenChange()):a.refreshToken())})};n.emitTokenChange=function(a){clearTimeout(this._refreshTimer);var b=this.server&&q.id.findServerInfo(this.server);
const c=(b=b&&b.owningSystemUrl)&&q.id.findServerInfo(b);!1===a||b&&"portal"!==this.scope&&(!c||!c.webTierAuth||q.id.normalizeWebTierAuth)||null==this.expires&&null==this.validity||this._startRefreshTimer();this.emit("token-change")};n.destroy=function(){this.userId=this.server=this.token=this.expires=this.validity=this.resources=this.creationTime=null;this._oAuthCred&&(this._oAuthCred.destroy(),this._oAuthCred=null);const a=q.id.credentials.indexOf(this);-1<a&&q.id.credentials.splice(a,1);this.emitTokenChange();
this.emit("destroy")};n.toJSON=function(){const a=T.fixJson({userId:this.userId,server:this.server,token:this.token,expires:this.expires,validity:this.validity,ssl:this.ssl,isAdmin:this.isAdmin,creationTime:this.creationTime,scope:this.scope}),b=this.resources;b&&0<b.length&&(a.resources=b.slice());return a};n._startRefreshTimer=function(){clearTimeout(this._refreshTimer);const a=6E4*this.tokenRefreshBuffer,b=2**31-1;let c=(this.validity?this.creationTime+6E4*this.validity:this.expires)-Date.now();
0>c?c=0:c>b&&(c=b);this._refreshTimer=setTimeout(this.refreshToken.bind(this),c>a?c-a:c)};return Q}(W.EventedAccessor);p.__decorate([N.property()],y.Credential.prototype,"creationTime",void 0);p.__decorate([N.property()],y.Credential.prototype,"expires",void 0);p.__decorate([N.property()],y.Credential.prototype,"isAdmin",void 0);p.__decorate([N.property()],y.Credential.prototype,"oAuthState",void 0);p.__decorate([N.property()],y.Credential.prototype,"resources",void 0);p.__decorate([N.property()],
y.Credential.prototype,"scope",void 0);p.__decorate([N.property()],y.Credential.prototype,"server",void 0);p.__decorate([N.property()],y.Credential.prototype,"ssl",void 0);p.__decorate([N.property()],y.Credential.prototype,"token",void 0);p.__decorate([N.property()],y.Credential.prototype,"tokenRefreshBuffer",void 0);p.__decorate([N.property()],y.Credential.prototype,"userId",void 0);p.__decorate([N.property()],y.Credential.prototype,"validity",void 0);y.Credential=p.__decorate([ha.subclass("esri.identity.Credential")],
y.Credential);y.IdentityManagerBase=X;Object.defineProperty(y,"__esModule",{value:!0})})},"esri/identity/IdentityForm":function(){define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/accessorSupport/decorators/property ../core/has ../core/accessorSupport/ensureType ../core/Logger ../core/jsonMap ../core/accessorSupport/decorators/subclass ../intl/substitute ../widgets/Widget ../widgets/support/widgetUtils ../widgets/support/decorators/messageBundle ../widgets/support/jsxFactory".split(" "),
function(y,u,p,m,q,G,z,W,U,J,T,A,x){m=function(C){function N(H,da){H=C.call(this,H,da)||this;H._usernameInputNode=null;H._passwordInputNode=null;H.messages=null;H.signingIn=!1;H.server=null;H.resource=null;H.error=null;H.oAuthPrompt=!1;return H}y._inheritsLoose(N,C);var X=N.prototype;X.render=function(){const {error:H,server:da,resource:ma,signingIn:ha,oAuthPrompt:ea,messages:S}=this,ia=x.tsx("div",{class:"esri-identity-form__group"},U.substitute(ea?S.oAuthInfo:S.info,{server:/\.arcgis\.com/i.test(da)?
"ArcGIS Online":da,resource:`(${ma||S.lblItem})`})),ja=ea?null:x.tsx("div",{class:"esri-identity-form__group",key:"username"},x.tsx("label",{class:"esri-identity-form__label"},S.lblUser,x.tsx("input",{value:"",required:!0,autocomplete:"off",spellcheck:!1,type:"text",bind:this,afterCreate:T.storeNode,"data-node-ref":"_usernameInputNode",class:"esri-input"}))),Z=ea?null:x.tsx("div",{class:"esri-identity-form__group",key:"password"},x.tsx("label",{class:"esri-identity-form__label"},S.lblPwd,x.tsx("input",
{value:"",required:!0,type:"password",bind:this,afterCreate:T.storeNode,"data-node-ref":"_passwordInputNode",class:"esri-input"}))),aa=x.tsx("div",{class:this.classes("esri-identity-form__group","esri-identity-form__footer")},x.tsx("input",{type:"submit",disabled:!!ha,value:ha?S.lblSigning:S.lblOk,class:"esri-button"}),x.tsx("input",{type:"button",value:S.lblCancel,bind:this,onclick:this._cancel,class:this.classes("esri-button","esri-button--secondary")})),ka=H?x.tsx("div",null,H.details&&H.details.httpStatus?
S.invalidUser:S.noAuthService):null;return x.tsx("form",{class:"esri-identity-form",bind:this,onsubmit:this._submit},ia,ka,ja,Z,aa)};X._cancel=function(){this._set("signingIn",!1);this._usernameInputNode&&(this._usernameInputNode.value="");this._passwordInputNode&&(this._passwordInputNode.value="");this.emit("cancel")};X._submit=function(H){H.preventDefault();this._set("signingIn",!0);this.emit("submit",this.oAuthPrompt?{}:{username:this._usernameInputNode&&this._usernameInputNode.value,password:this._passwordInputNode&&
this._passwordInputNode.value})};return N}(J);u.__decorate([p.property(),A.messageBundle("esri/identity/t9n/identity")],m.prototype,"messages",void 0);u.__decorate([p.property()],m.prototype,"signingIn",void 0);u.__decorate([p.property()],m.prototype,"server",void 0);u.__decorate([p.property()],m.prototype,"resource",void 0);u.__decorate([p.property()],m.prototype,"error",void 0);u.__decorate([p.property()],m.prototype,"oAuthPrompt",void 0);return m=u.__decorate([W.subclass("esri.identity.IdentityForm")],
m)})},"esri/identity/IdentityModal":function(){define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/handleUtils ../core/accessorSupport/decorators/property ../core/has ../core/accessorSupport/ensureType ../core/Logger ../core/jsonMap ../core/accessorSupport/decorators/subclass ../widgets/Widget ../widgets/support/widget ../widgets/support/jsxFactory ../widgets/support/decorators/messageBundle".split(" "),function(y,u,p,m,q,G,z,W,U,J,T,A,x){function C(b,c){var d=Object.keys(b);if(Object.getOwnPropertySymbols){var e=
Object.getOwnPropertySymbols(b);c&&(e=e.filter(function(g){return Object.getOwnPropertyDescriptor(b,g).enumerable}));d.push.apply(d,e)}return d}function N(b){for(var c=1;c<arguments.length;c++){var d=null!=arguments[c]?arguments[c]:{};c%2?C(Object(d),!0).forEach(function(e){var g=d[e];e in b?Object.defineProperty(b,e,{value:g,enumerable:!0,configurable:!0,writable:!0}):b[e]=g}):Object.getOwnPropertyDescriptors?Object.defineProperties(b,Object.getOwnPropertyDescriptors(d)):C(Object(d)).forEach(function(e){Object.defineProperty(b,
e,Object.getOwnPropertyDescriptor(d,e))})}return b}q='input select textarea a[href] button [tabindex] audio[controls] video[controls] [contenteditable]:not([contenteditable\x3d"false"]) details\x3esummary:first-of-type details'.split(" ");var X=q.join(","),H="undefined"===typeof Element?function(){}:Element.prototype.matches||Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector,da=function(b,c,d){var e=Array.prototype.slice.apply(b.querySelectorAll(X));c&&H.call(b,X)&&e.unshift(b);
return e=e.filter(d)},ma=function(b){var c=parseInt(b.getAttribute("tabindex"),10);return isNaN(c)?"true"===b.contentEditable||("AUDIO"===b.nodeName||"VIDEO"===b.nodeName||"DETAILS"===b.nodeName)&&null===b.getAttribute("tabindex")?0:b.tabIndex:c},ha=function(b,c){return b.tabIndex===c.tabIndex?b.documentOrder-c.documentOrder:b.tabIndex-c.tabIndex},ea=function(b){return"DETAILS"===b.tagName&&Array.prototype.slice.apply(b.children).some(function(c){return"SUMMARY"===c.tagName})},S=function(b,c){for(var d=
0;d<b.length;d++)if(b[d].checked&&b[d].form===c)return b[d]},ia=function(b){if(!b.name)return!0;var c=b.form||b.ownerDocument,d=function(g){return c.querySelectorAll('input[type\x3d"radio"][name\x3d"'+g+'"]')};if("undefined"!==typeof window&&"undefined"!==typeof window.CSS&&"function"===typeof window.CSS.escape)var e=d(window.CSS.escape(b.name));else try{e=d(b.name)}catch(g){return console.error("Looks like you have a radio button with a name attribute containing invalid CSS selector characters and need the CSS.escape polyfill: %s",
g.message),!1}d=S(e,b.form);return!d||d===b},ja=function(b,c){if("hidden"===getComputedStyle(b).visibility)return!0;var d=H.call(b,"details\x3esummary:first-of-type")?b.parentElement:b;if(H.call(d,"details:not([open]) *"))return!0;if(!c||"full"===c)for(;b;){if("none"===getComputedStyle(b).display)return!0;b=b.parentElement}else if("non-zero-area"===c)return b=b.getBoundingClientRect(),c=b.height,0===b.width&&0===c;return!1},Z=function(b,c){var d;(d=c.disabled)||(d="INPUT"===c.tagName&&"hidden"===
c.type);return d||ja(c,b.displayCheck)||ea(c)?!1:!0},aa=function(b,c){(b=!Z(b,c))||(b="INPUT"===c.tagName&&"radio"===c.type&&!ia(c));return b||0>ma(c)?!1:!0},ka=function(b,c){c=c||{};var d=[],e=[];da(b,c.includeContainer,aa.bind(null,c)).forEach(function(g,h){var t=ma(g);0===t?d.push(g):e.push({documentOrder:h,tabIndex:t,node:g})});return e.sort(ha).map(function(g){return g.node}).concat(d)},na=q.concat("iframe").join(","),la=function(b,c){c=c||{};if(!b)throw Error("No node provided");return!1===
H.call(b,na)?!1:Z(c,b)},fa,P=function(){var b=[];return{activateTrap:function(c){if(0<b.length){var d=b[b.length-1];d!==c&&d.pause()}d=b.indexOf(c);-1!==d&&b.splice(d,1);b.push(c)},deactivateTrap:function(c){c=b.indexOf(c);-1!==c&&b.splice(c,1);0<b.length&&b[b.length-1].unpause()}}}(),Q=function(b,c){var d=-1;b.every(function(e,g){return c(e)?(d=g,!1):!0});return d},n=function(b){for(var c=arguments.length,d=Array(1<c?c-1:0),e=1;e<c;e++)d[e-1]=arguments[e];return"function"===typeof b?b.apply(void 0,
d):b},a=function(b,c){var d=document,e=N({returnFocusOnDeactivate:!0,escapeDeactivates:!0,delayInitialFocus:!0},c),g=[],h=[],t=null,f=null,k=!1,v=!1,r=function(K,l,B){return K&&void 0!==K[l]?K[l]:e[B||l]},E=function(K){return g.some(function(l){return l.contains(K)})},D=function(K){var l=e[K];if(!l)return null;var B=l;if("string"===typeof l&&(B=d.querySelector(l),!B))throw Error("`".concat(K,"` refers to no known node"));if("function"===typeof l&&(B=l(),!B))throw Error("`".concat(K,"` did not return a node"));
return B},w=function(){var K=null!==D("initialFocus")?D("initialFocus"):E(d.activeElement)?d.activeElement:(K=h[0])&&K.firstTabbableNode||D("fallbackFocus");if(!K)throw Error("Your focus-trap needs to have at least one focusable element");return K},I=function(){h=g.map(function(K){var l=ka(K);if(0<l.length)return{container:K,firstTabbableNode:l[0],lastTabbableNode:l[l.length-1]}}).filter(function(K){return!!K});if(0>=h.length&&!D("fallbackFocus"))throw Error("Your focus-trap must have at least one container with at least one tabbable node in it at all times");
},O=function B(l){l!==d.activeElement&&(l&&l.focus?(l.focus({preventScroll:!!e.preventScroll}),f=l,l.tagName&&"input"===l.tagName.toLowerCase()&&"function"===typeof l.select&&l.select()):B(w()))},L=function(l){var B=D("setReturnFocus");return B?B:l},Y=function(l){E(l.target)||(n(e.clickOutsideDeactivates,l)?ba.deactivate({returnFocus:e.returnFocusOnDeactivate&&!la(l.target)}):n(e.allowOutsideClick,l)||l.preventDefault())},oa=function(l){var B=E(l.target);B||l.target instanceof Document?B&&(f=l.target):
(l.stopImmediatePropagation(),O(f||w()))},F=function(l){I();var B=null;if(0<h.length){var V=Q(h,function(ca){return ca.container.contains(l.target)});if(0>V)B=l.shiftKey?h[h.length-1].lastTabbableNode:h[0].firstTabbableNode;else if(l.shiftKey){var M=Q(h,function(ca){return l.target===ca.firstTabbableNode});0>M&&h[V].container===l.target&&(M=V);0<=M&&(B=h[0===M?h.length-1:M-1].lastTabbableNode)}else M=Q(h,function(ca){return l.target===ca.lastTabbableNode}),0>M&&h[V].container===l.target&&(M=V),0<=
M&&(B=h[M===h.length-1?0:M+1].firstTabbableNode)}else B=D("fallbackFocus");B&&(l.preventDefault(),O(B))},R=function(l){!1===e.escapeDeactivates||"Escape"!==l.key&&"Esc"!==l.key&&27!==l.keyCode?"Tab"!==l.key&&9!==l.keyCode||F(l):(l.preventDefault(),ba.deactivate())},pa=function(l){n(e.clickOutsideDeactivates,l)||E(l.target)||n(e.allowOutsideClick,l)||(l.preventDefault(),l.stopImmediatePropagation())},qa=function(){if(k)return P.activateTrap(ba),fa=e.delayInitialFocus?setTimeout(function(){O(w())},
0):O(w()),d.addEventListener("focusin",oa,!0),d.addEventListener("mousedown",Y,{capture:!0,passive:!1}),d.addEventListener("touchstart",Y,{capture:!0,passive:!1}),d.addEventListener("click",pa,{capture:!0,passive:!1}),d.addEventListener("keydown",R,{capture:!0,passive:!1}),ba},ra=function(){if(k)return d.removeEventListener("focusin",oa,!0),d.removeEventListener("mousedown",Y,!0),d.removeEventListener("touchstart",Y,!0),d.removeEventListener("click",pa,!0),d.removeEventListener("keydown",R,!0),ba};
var ba={activate:function(l){if(k)return this;var B=r(l,"onActivate"),V=r(l,"onPostActivate"),M=r(l,"checkCanFocusTrap");M||I();k=!0;v=!1;t=d.activeElement;B&&B();l=function(){M&&I();qa();V&&V()};if(M)return M(g.concat()).then(l,l),this;l();return this},deactivate:function(l){if(!k)return this;clearTimeout(fa);ra();v=k=!1;P.deactivateTrap(ba);var B=r(l,"onDeactivate"),V=r(l,"onPostDeactivate"),M=r(l,"checkCanReturnFocus");B&&B();var ca=r(l,"returnFocus","returnFocusOnDeactivate");l=function(){setTimeout(function(){ca&&
O(L(t));V&&V()},0)};if(ca&&M)return M(L(t)).then(l,l),this;l();return this},pause:function(){if(v||!k)return this;v=!0;ra();return this},unpause:function(){if(!v||!k)return this;v=!1;I();qa();return this},updateContainerElements:function(l){g=[].concat(l).filter(Boolean).map(function(B){return"string"===typeof B?d.querySelector(B):B});k&&I();return this}};ba.updateContainerElements(b);return ba};J=function(b){function c(e,g){var h=b.call(this,e,g)||this;h.container=document.createElement("div");h.content=
null;h.open=!1;h._close=()=>{h.open=!1};document.body.appendChild(h.container);h.own(h.watch("open",()=>h._toggleFocusTrap()));return h}y._inheritsLoose(c,b);var d=c.prototype;d.destroy=function(){this._destroyFocusTrap()};d.render=function(){var e=this.id;const {open:g,content:h,title:t,messages:f}=this;var k=g&&!!h;const v={["esri-identity-modal--open"]:k,["esri-identity-modal--closed"]:!k},r=A.tsx("button",{class:"esri-identity-modal__close-button","aria-label":f.close,title:f.close,bind:this,
onclick:this._close},A.tsx("span",{"aria-hidden":"true",class:"esri-icon-close"})),E=`${e}_title`;e=`${e}_content`;const D=t?A.tsx("h1",{id:E,class:"esri-identity-modal__title"},t):null;k=k?A.tsx("div",{bind:this,class:"esri-identity-modal__dialog",role:"dialog","aria-labelledby":E,"aria-describedby":e,afterCreate:this._createFocusTrap},r,D,this._renderContent(e)):null;return A.tsx("div",{tabIndex:-1,class:this.classes("esri-identity-modal",v)},k)};d._destroyFocusTrap=function(){var e;null==(e=this._focusTrap)?
void 0:e.deactivate({onDeactivate:null});this._focusTrap=null};d._toggleFocusTrap=function(){const {_focusTrap:e,open:g}=this;e&&(g?e.activate():e.deactivate())};d._createFocusTrap=function(e){this._destroyFocusTrap();const g=requestAnimationFrame(()=>{this._focusTrap=a(e,{initialFocus:"input",onDeactivate:this._close});this._toggleFocusTrap()});this.own(p.makeHandle(()=>cancelAnimationFrame(g)))};d._renderContent=function(e){const g=this.content;return"string"===typeof g?A.tsx("div",{class:"esri-identity-modal__content",
id:e,innerHTML:g}):T.isWidget(g)?A.tsx("div",{class:"esri-identity-modal__content",id:e},g.render()):g instanceof HTMLElement?A.tsx("div",{class:"esri-identity-modal__content",id:e,bind:g,afterCreate:this._attachToNode}):null};d._attachToNode=function(e){e.appendChild(this)};return c}(J);u.__decorate([m.property({readOnly:!0})],J.prototype,"container",void 0);u.__decorate([m.property()],J.prototype,"content",void 0);u.__decorate([m.property()],J.prototype,"open",void 0);u.__decorate([m.property(),
x.messageBundle("esri/t9n/common")],J.prototype,"messages",void 0);u.__decorate([m.property({aliasOf:"messages.auth.signIn"})],J.prototype,"title",void 0);return J=u.__decorate([U.subclass("esri.identity.IdentityModal")],J)})},"esri/identity/OAuthCredential":function(){define(function(){let y=function(){function u(m,q){this.userId=this.token=this.ssl=this.expires=this.appId=this.storage=this.oAuthInfo=null;this.oAuthInfo=m;this.storage=q;this._init()}var p=u.prototype;p.isValid=function(){let m=!1;
if(this.oAuthInfo&&this.token&&this.userId){const q=Date.now();this.expires>q&&(this.expires-q)/1E3>60*this.oAuthInfo.minTimeUntilExpiration&&(m=!0)}return m};p.save=function(){if(this.storage){var m=this._load(),q=this.oAuthInfo;if(q&&q.authNamespace&&q.portalUrl){let G=m[q.authNamespace];G||(G=m[q.authNamespace]={});G[q.portalUrl]={appId:this.appId=q.appId,expires:this.expires,ssl:this.ssl,token:this.token,userId:this.userId};try{this.storage.setItem("esriJSAPIOAuth",JSON.stringify(m))}catch(z){console.log(z)}}}};
p.destroy=function(){const m=this._load(),q=this.oAuthInfo;if(q&&q.appId&&q.portalUrl&&this.token&&this.expires>Date.now()){var G=q.portalUrl.replace(/^http:/i,"https:")+"/sharing/rest/oauth2/revokeToken";const z=new FormData;z.append("f","json");z.append("auth_token",this.token);z.append("client_id",q.appId);z.append("token_type_hint","access_token");if("function"===typeof navigator.sendBeacon)navigator.sendBeacon(G,z);else{const W=new XMLHttpRequest;W.open("POST",G);W.send(z)}}if(q&&q.authNamespace&&
q.portalUrl&&this.storage&&(G=m[q.authNamespace])){delete G[q.portalUrl];try{this.storage.setItem("esriJSAPIOAuth",JSON.stringify(m))}catch(z){console.log(z)}}q&&(this.oAuthInfo=q._oAuthCred=null)};p._init=function(){var m=this._load();const q=this.oAuthInfo;q&&q.authNamespace&&q.portalUrl&&(m=m[q.authNamespace])&&(m=m[q.portalUrl])&&(this.appId=m.appId,this.expires=m.expires,this.ssl=m.ssl,this.token=m.token,this.userId=m.userId)};p._load=function(){let m={};if(this.storage){const q=this.storage.getItem("esriJSAPIOAuth");
if(q)try{m=JSON.parse(q)}catch(G){console.log(G)}}return m};return u}();y.prototype.declaredClass="esri.identity.OAuthCredential";return y})},"esri/identity/OAuthInfo":function(){define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/JSONSupport ../core/accessorSupport/decorators/property ../core/has ../core/accessorSupport/ensureType ../core/Logger ../core/jsonMap ../core/accessorSupport/decorators/subclass".split(" "),function(y,u,p,m,q,G,z,W,U){var J;p=J=function(T){function A(x){x=
T.call(this,x)||this;x._oAuthCred=null;x.appId=null;x.authNamespace="/";x.expiration=20160;x.forceLogin=!1;x.forceUserId=!1;x.locale=null;x.minTimeUntilExpiration=30;x.popup=!1;x.popupCallbackUrl="oauth-callback.html";x.popupWindowFeatures="height\x3d490,width\x3d800,resizable,scrollbars,status";x.portalUrl="https://www.arcgis.com";x.preserveUrlHash=!1;x.userId=null;return x}y._inheritsLoose(A,T);A.prototype.clone=function(){return J.fromJSON(this.toJSON())};return A}(p.JSONSupport);u.__decorate([m.property({json:{write:!0}})],
p.prototype,"appId",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"authNamespace",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"expiration",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"forceLogin",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"forceUserId",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"locale",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"minTimeUntilExpiration",void 0);
u.__decorate([m.property({json:{write:!0}})],p.prototype,"popup",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"popupCallbackUrl",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"popupWindowFeatures",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"portalUrl",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"preserveUrlHash",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"userId",void 0);return p=J=u.__decorate([U.subclass("esri.identity.OAuthInfo")],
p)})},"esri/identity/ServerInfo":function(){define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/JSONSupport ../core/accessorSupport/decorators/property ../core/has ../core/accessorSupport/ensureType ../core/Logger ../core/jsonMap ../core/accessorSupport/decorators/subclass".split(" "),function(y,u,p,m,q,G,z,W,U){p=function(J){function T(A){A=J.call(this,A)||this;A.adminTokenServiceUrl=null;A.currentVersion=null;A.hasPortal=null;A.hasServer=null;A.owningSystemUrl=null;A.owningTenant=
null;A.server=null;A.shortLivedTokenValidity=null;A.tokenServiceUrl=null;A.webTierAuth=null;return A}y._inheritsLoose(T,J);return T}(p.JSONSupport);u.__decorate([m.property({json:{write:!0}})],p.prototype,"adminTokenServiceUrl",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"currentVersion",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"hasPortal",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"hasServer",void 0);u.__decorate([m.property({json:{write:!0}})],
p.prototype,"owningSystemUrl",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"owningTenant",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"server",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"shortLivedTokenValidity",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"tokenServiceUrl",void 0);u.__decorate([m.property({json:{write:!0}})],p.prototype,"webTierAuth",void 0);return p=u.__decorate([U.subclass("esri.identity.ServerInfo")],
p)})},"*noref":1}});define(["../chunks/_rollupPluginBabelHelpers","../kernel","./IdentityManagerBase"],function(y,u,p){p=function(m){function q(){return m.apply(this,arguments)||this}y._inheritsLoose(q,m);return q}(p.IdentityManagerBase);p.prototype.declaredClass="esri.identity.IdentityManager";p=new p;u.setId(p);return p});