// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ./DisjointTimerQuery ./DrawBuffers ./Instancing ./isWebGL2Context ./LoseContext ./VertexArrayObjects".split(" "),function(C,D,E,F,l,G,H){function m(a,n,c,t,e){if(t&&l(a))return!0;if(n[c])return!1;for(const f of e)if(a.getExtension(f))return!0;return!1}C.loadCapabilities=function(a,n){const c=n.disabledExtensions||{},t=n.debugWebGLExtensions||{};let e,f,p,q,r,u,g,h,k,v,w,x=null,y=null,z=null,A=null;return{get drawBuffers(){w||(w=E.load(a,c));return w},get instancing(){e||(e=F.load(a));
return e},get vao(){f||(f=H.load(a,c));return f},get compressedTextureETC(){if(!p)if(c.compressedTextureETC)p=null;else{var b=a.getExtension("WEBGL_compressed_texture_etc");p=b?{COMPRESSED_R11_EAC:b.COMPRESSED_R11_EAC,COMPRESSED_SIGNED_R11_EAC:b.COMPRESSED_SIGNED_R11_EAC,COMPRESSED_RG11_EAC:b.COMPRESSED_RG11_EAC,COMPRESSED_SIGNED_RG11_EAC:b.COMPRESSED_SIGNED_RG11_EAC,COMPRESSED_RGB8_ETC2:b.COMPRESSED_RGB8_ETC2,COMPRESSED_SRGB8_ETC2:b.COMPRESSED_SRGB8_ETC2,COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2:b.COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2,
COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2:b.COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,COMPRESSED_RGBA8_ETC2_EAC:b.COMPRESSED_RGBA8_ETC2_EAC,COMPRESSED_SRGB8_ALPHA8_ETC2_EAC:b.COMPRESSED_SRGB8_ALPHA8_ETC2_EAC}:null}return p},get compressedTextureS3TC(){if(!q)if(c.compressedTextureS3TC)q=null;else{var b=a.getExtension("WEBGL_compressed_texture_s3tc");q=b?{COMPRESSED_RGB_S3TC_DXT1:b.COMPRESSED_RGB_S3TC_DXT1_EXT,COMPRESSED_RGBA_S3TC_DXT1:b.COMPRESSED_RGBA_S3TC_DXT1_EXT,COMPRESSED_RGBA_S3TC_DXT3:b.COMPRESSED_RGBA_S3TC_DXT3_EXT,
COMPRESSED_RGBA_S3TC_DXT5:b.COMPRESSED_RGBA_S3TC_DXT5_EXT}:null}return q},get textureFilterAnisotropic(){if(!r)if(c.textureFilterAnisotropic)r=null;else{var b=a.getExtension("EXT_texture_filter_anisotropic")||a.getExtension("MOZ_EXT_texture_filter_anisotropic")||a.getExtension("WEBKIT_EXT_texture_filter_anisotropic");r=b?{MAX_TEXTURE_MAX_ANISOTROPY:b.MAX_TEXTURE_MAX_ANISOTROPY_EXT,TEXTURE_MAX_ANISOTROPY:b.TEXTURE_MAX_ANISOTROPY_EXT}:null}return r},get disjointTimerQuery(){u||(u=D.createDisjointTimerQuery(a,
c));return u},get textureFloat(){if(!g)if(l(a))g={textureFloat:!0,textureFloatLinear:!c.textureFloatLinear&&!!a.getExtension("OES_texture_float_linear"),textureHalfFloat:!0,textureHalfFloatLinear:!c.textureHalfFloatLinear&&!!a.getExtension("OES_texture_half_float_linear"),HALF_FLOAT:a.HALF_FLOAT};else if(a instanceof WebGLRenderingContext){const b=!c.textureHalfFloat&&a.getExtension("OES_texture_half_float");g={textureFloat:!c.textureFloat&&!!a.getExtension("OES_texture_float"),textureFloatLinear:!c.textureFloatLinear&&
!!a.getExtension("OES_texture_float_linear"),textureHalfFloat:!!b,textureHalfFloatLinear:!c.textureHalfFloatLinear&&!!a.getExtension("OES_texture_half_float_linear"),HALF_FLOAT:b?b.HALF_FLOAT_OES:void 0}}else g=null;return g},get colorBufferFloat(){if(!h)if(l(a)){var b=!c.colorBufferFloat&&a.getExtension("EXT_color_buffer_half_float"),d=!c.colorBufferFloat&&a.getExtension("EXT_color_buffer_float"),B=!c.colorBufferFloat&&a.getExtension("EXT_float_blend");h=b||d||B?{textureFloat:!!d,textureHalfFloat:!!b,
R16F:a.R16F,RG16F:a.RG16F,RGBA16F:a.RGBA16F,R32F:a.R32F,RG32F:a.RG32F,RGBA32F:a.RGBA32F,R11F_G11F_B10F:a.R11F_G11F_B10F,RGB16F:a.RGB16F}:null}else a instanceof WebGLRenderingContext?(b=!c.colorBufferFloat&&a.getExtension("EXT_color_buffer_half_float"),d=!c.colorBufferFloat&&a.getExtension("WEBGL_color_buffer_float"),B=!c.colorBufferFloat&&a.getExtension("EXT_float_blend"),h=b||d||B?{textureFloat:!!d,textureHalfFloat:!!b,RGBA16F:b?b.RGBA16F_EXT:void 0,RGB16F:b?b.RGB16F_EXT:void 0,RGBA32F:d?d.RGBA32F_EXT:
void 0}:null):h=null;return h},get blendMinMax(){if(!k)if(l(a))k={MIN:a.MIN,MAX:a.MAX};else if(c.blendMinMax)k=null;else{{const b=a.getExtension("EXT_blend_minmax");k=b?{MIN:b.MIN_EXT,MAX:b.MAX_EXT}:null}}return k},get depthTexture(){null===x&&(x=m(a,c,"depthTexture",!0,["WEBGL_depth_texture","MOZ_WEBGL_depth_texture","WEBKIT_WEBGL_depth_texture"]));return x},get standardDerivatives(){null===y&&(y=m(a,c,"standardDerivatives",!0,["OES_standard_derivatives"]));return y},get shaderTextureLOD(){null===
z&&(z=m(a,c,"shaderTextureLOD",!0,["EXT_shader_texture_lod"]));return z},get fragDepth(){null===A&&(A=m(a,c,"fragDepth",!0,["EXT_frag_depth"]));return A},get loseContext(){v||(v=G.load(a,t));return v},enable(b){return this[b]}}};Object.defineProperty(C,"__esModule",{value:!0})});