// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/maybe ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/sphere ../../support/mathUtils ./ContentObject ./GeometryRecord ./Object3DStateID ./Util ../materials/renderers/utils".split(" "),function(y,t,m,w,q,k,r,z,A,x,B,C,u,v){x=function(n){function p(a={}){var b=n.call(this)||this;b.type=1;b._geometryRecords=[];b._geometries=[];b._objectTransformation=
q.create();b._bvObjectSpace=new D;b._bvWorldSpace=new D;b._bvDirty=!0;b._hasVolatileTransformation=!1;b._visible=!0;b.castShadow=null!=a.castShadow?a.castShadow:!0;b.metadata=a.metadata;b.metadata&&b.metadata.isElevationSource&&(b.metadata.lastValidElevationBB=new E);b.transformation=q.create();const {geometries:c,materials:h,transformations:f,origins:g}=a;if(!Array.isArray(c))return t._assertThisInitialized(b);u.assert(h.length===c.length,"Object3D: materials don't match geometries");u.assert(f.length===
c.length,"Object3D: transformations don't match geometries");b._geometryRecords.length=c.length;b._geometries.length=c.length;for(a=0;a<c.length;a++)b._geometries[a]=c[a],b._geometryRecords[a]=B.GeometryRecord.pool.acquire(c[a],h[a],q.clone(f[a]),{highlights:null,occludees:null,visible:!0},g&&g[a]);return b}t._inheritsLoose(p,n);var d=p.prototype;d.dispose=function(){this._geometryRecords.length=0;this._geometries.length=0};d.getNumGeometryRecords=function(){return this._geometryRecords.length};d.getGeometryRecord=
function(a){u.assert(0<=a&&a<this._geometryRecords.length,"Object3d.getGeometryDataByIndex: index out of range");return this._geometryRecords[a]};d.addGeometry=function(a,b,c,h,f,g){c=c?c:q.IDENTITY;this._geometries.push(a);a=B.GeometryRecord.pool.acquire(a,b,c,h||{highlights:null,occludees:null,visible:!0},f,g);this._geometryRecords.push(a);this._hasVolatileTransformation=this._hasVolatileTransformation||m.isSome(a.shaderTransformation);this._emit("objectGeometryAdded",{object:this,record:a});this._invalidateBoundingVolume();
return a};d.removeGeometry=function(a){const b=this._geometryRecords.splice(a,1)[0];this._hasVolatileTransformation=m.isSome(b.shaderTransformation)?this._geometryRecords.some(c=>m.isSome(c.shaderTransformation)):this._hasVolatileTransformation;b.dispose();this._geometries.splice(a,1);this._emit("objectGeometryRemoved",{object:this,record:b});this._invalidateBoundingVolume();return b};d.removeAllGeometries=function(){for(;0<this.getNumGeometryRecords();)this.removeGeometry(0)};d.geometryVertexAttrsUpdated=
function(a){this._emit("vertexAttrsUpdated",{object:this,record:this._geometryRecords[a]});this._invalidateBoundingVolume()};d.setVisible=function(a){this._visible=a;for(const b of this._geometryRecords)b.instanceParameters.visible=this._visible;this._emit("visibilityChanged",this)};d.maskOccludee=function(){const a=new C.Object3DStateID(1);for(const b of this._geometryRecords)b.instanceParameters.occludees=v.addObject3DStateID(b.instanceParameters.occludees,a);this._emit("occlusionChanged",this);
return a};d.removeOcclude=function(a){for(const b of this._geometryRecords)b.instanceParameters.occludees=v.removeObject3DStateID(b.instanceParameters.occludees,a);this._emit("occlusionChanged",this)};d.highlight=function(){const a=new C.Object3DStateID(0);for(const b of this._geometryRecords)b.instanceParameters.highlights=v.addObject3DStateID(b.instanceParameters.highlights,a);this._emit("highlightChanged",this);return a};d.removeHighlight=function(a){for(const b of this._geometryRecords)b.instanceParameters.highlights=
v.removeObject3DStateID(b.instanceParameters.highlights,a);this._emit("highlightChanged",this)};d.getCombinedStaticTransformation=function(a,b){return w.multiply(m.unwrapOr(b,q.create()),this.transformation,a.getStaticTransformation())};d.getCombinedShaderTransformation=function(a,b){b=b||q.create();w.multiply(b,this.transformation,a.getShaderTransformation());return b};d.hasVolativeTransformation=function(){return this._hasVolatileTransformation};d._validateBoundingVolume=function(){if(this._bvDirty||
this._hasVolatileTransformation){this._bvObjectSpace.init();this._bvWorldSpace.init();for(var a=0;a<this._geometryRecords.length;++a){var b=this._geometryRecords[a],c=this._geometries[a].boundingInfo;m.isSome(c)&&(this._calculateTransformedBoundingVolume(c,this._bvObjectSpace,b.getShaderTransformation()),this._calculateTransformedBoundingVolume(c,this._bvWorldSpace,this.getCombinedShaderTransformation(b)))}k.lerp(this._bvObjectSpace.bounds,this._bvObjectSpace.min,this._bvObjectSpace.max,.5);k.lerp(this._bvWorldSpace.bounds,
this._bvWorldSpace.min,this._bvWorldSpace.max,.5);a=r.create();b=r.create();c=A.maxScale(this.transformation);for(let e=0;e<this._geometryRecords.length;++e){var h=this._geometries[e].boundingInfo;if(!m.isNone(h)){var f=this._geometryRecords[e].getShaderTransformation(),g=A.maxScale(f);k.transformMat4(a,h.getCenter(),f);f=k.distance(a,this._bvObjectSpace.bounds);h=h.getBSRadius()*g;this._bvObjectSpace.bounds[3]=Math.max(this._bvObjectSpace.bounds[3],f+h);k.transformMat4(b,a,this.transformation);g=
k.distance(b,this._bvWorldSpace.bounds);this._bvWorldSpace.bounds[3]=Math.max(this._bvWorldSpace.bounds[3],g+h*c)}}this._bvDirty=!1}};d._calculateTransformedBoundingVolume=function(a,b,c){const h=a.getBBMin();a=a.getBBMax();const f=r.clone(h),g=r.clone(a);k.transformMat4(f,f,c);k.transformMat4(g,g,c);for(var e=0;3>e;++e)b.min[e]=Math.min(b.min[e],f[e],g[e]),b.max[e]=Math.max(b.max[e],f[e],g[e]);for(e=0;3>e;++e){k.copy(f,h);k.copy(g,a);f[e]=a[e];g[e]=h[e];k.transformMat4(f,f,c);k.transformMat4(g,g,
c);for(let l=0;3>l;++l)b.min[l]=Math.min(b.min[l],f[l],g[l]),b.max[l]=Math.max(b.max[l],f[l],g[l])}};d._invalidateBoundingVolume=function(){this._bvDirty=!0;m.isSome(this._parentLayer)&&this._parentLayer.notifyObjectBBChanged(this,this._bvWorldSpace.bounds)};d._emit=function(a,b){m.isSome(this._parentLayer)&&this._parentLayer.events.emit(a,b)};t._createClass(p,[{key:"geometryRecords",get:function(){return this._geometryRecords}},{key:"geometries",get:function(){return this._geometries}},{key:"transformation",
get:function(){return this._objectTransformation},set:function(a){w.copy(this._objectTransformation,a);this._invalidateBoundingVolume();this._emit("objectTransformation",this)}},{key:"parentLayer",get:function(){return this._parentLayer},set:function(a){u.assert(null==this._parentLayer||null==a,"Object3D can only be added to a single Layer");this._parentLayer=a}},{key:"isVisible",get:function(){return this._visible}},{key:"boundingVolumeWorldSpace",get:function(){this._validateBoundingVolume();return this._bvWorldSpace}},
{key:"boundingVolumeObjectSpace",get:function(){this._validateBoundingVolume();return this._bvObjectSpace}},{key:"test",get:function(){const a=this;return{hasGeometry:b=>-1<a._geometries.indexOf(b),getGeometryIndex:b=>a._geometries.indexOf(b)}}}]);return p}(x.ContentObject);let E=function(){function n(){this.min=r.fromValues(Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE);this.max=r.fromValues(-Number.MAX_VALUE,-Number.MAX_VALUE,-Number.MAX_VALUE)}n.prototype.isEmpty=function(){return this.max[0]<
this.min[0]&&this.max[1]<this.min[1]&&this.max[2]<this.min[2]};return n}(),D=function(n){function p(){var d=n.apply(this,arguments)||this;d.bounds=z.create();return d}t._inheritsLoose(p,n);p.prototype.init=function(){k.set(this.min,Number.MAX_VALUE,Number.MAX_VALUE,Number.MAX_VALUE);k.set(this.max,-Number.MAX_VALUE,-Number.MAX_VALUE,-Number.MAX_VALUE);z.clear(this.bounds)};return p}(E);y.Object3D=x;Object.defineProperty(y,"__esModule",{value:!0})});