// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../geometry ../../core/Handles ../../core/maybe ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/Logger ../../core/jsonMap ../../core/accessorSupport/decorators/subclass ../3d/interactive/editingTools/draw/DrawTool ./DrawingMode ./DrawAction ./input/DrawEvents ../input/InputManager ../interactive/keybindings ../support/screenUtils ../../geometry/Point".split(" "),
function(h,r,l,B,t,c,p,C,D,E,F,w,x,u,y,g,f,k,q,z){h.PolylineDrawAction=function(m){function n(a){a=m.call(this,a)||this;a._panEnabled=!1;a._popVertexOnPointerMove=!1;a._addVertexOnPointerUp=!1;a._activePointerId=null;a._viewHandles=new t;a._undoRedoHandles=new t;a.mode=u.defaultDrawingMode;return a}r._inheritsLoose(n,m);var d=n.prototype;d.initialize=function(){"2d"===this.view.type?(this._addViewHandles(),this._addUndoRedoHandles()):this._addDrawTool(this.view)};d.destroy=function(){"2d"===this.view.type?
(this._removeViewHandles(),this._viewHandles.destroy(),this._removeUndoRedoHandles(),this._undoRedoHandles.destroy()):this._removeDrawTool();this.emit("destroy")};d.undo=function(){m.prototype.undo.call(this);this.notifyChange("vertices")};d.redo=function(){m.prototype.redo.call(this);this.notifyChange("vertices")};d.complete=function(){"2d"===this.view.type?this._completeDrawing():this._drawTool.completeCreateOperation()};d._addViewHandles=function(){this._removeViewHandles();this._viewHandles.add([this.view.on("click",
a=>{a.stopPropagation()},f.ViewEventPriorities.TOOL),this.view.on("pointer-down",a=>{this._shouldHandlePointerEvent(a)&&!this._panEnabled&&(this._snappingTask=c.abortMaybe(this._snappingTask),this._activePointerId=a.pointerId,this._addVertexOnPointerUp=!0,this._cursorScreenPoint=q.createScreenPointFromEvent(a),"touch"===a.pointerType&&this._updateCursor(a.native))},f.ViewEventPriorities.TOOL),this.view.on("pointer-move",a=>{this._popVertexOnPointerMove&&(this.undo(),this._popVertexOnPointerMove=!1);
this._snappingTask=c.abortMaybe(this._snappingTask);this._cursorScreenPoint=q.createScreenPointFromEvent(a);"touch"!==a.pointerType&&this._updateCursor(a.native)},f.ViewEventPriorities.TOOL),this.view.on("pointer-drag",a=>{this._shouldHandlePointerEvent(a)&&(this._snappingTask=c.abortMaybe(this._snappingTask),this._cursorScreenPoint=q.createScreenPointFromEvent(a),this._dragEnabled&&!this._panEnabled?this._vertexAddHandler(a):this._addVertexOnPointerUp=!1)},f.ViewEventPriorities.TOOL),this.view.on("pointer-up",
a=>{this._shouldHandlePointerEvent(a)&&(this._snappingTask=c.abortMaybe(this._snappingTask),this._activePointerId=null,this._addVertexOnPointerUp?this._clickEnabled?this._vertexAddHandler(a):(1===this.vertices.length&&this.vertices.pop(),this._drawCompleteHandler(a)):this._updateCursor(a.native,"touch"===a.pointerType))},f.ViewEventPriorities.TOOL),this.view.on("drag",a=>{this._dragEnabled&&c.isSome(this._activePointerId)&&!this._panEnabled&&a.stopPropagation()},f.ViewEventPriorities.TOOL),this.view.on("drag",
["Shift"],a=>{a.stopPropagation()},f.ViewEventPriorities.TOOL),this.view.on("double-click",a=>{a.stopPropagation();this._drawCompleteHandler(a)},f.ViewEventPriorities.TOOL),this.view.on("double-click",["Control"],a=>{a.stopPropagation();this._drawCompleteHandler(a)},f.ViewEventPriorities.TOOL),this.view.on("key-down",a=>{const {key:b,repeat:e}=a;b===k.SKETCH_KEYS.vertexAdd&&!e&&this._cursorScreenPoint?(a.stopPropagation(),this._snappingTask=c.abortMaybe(this._snappingTask),this._vertexAddHandler(a)):
b!==k.SKETCH_KEYS.complete||e?b!==k.SKETCH_KEYS.undo||this.interactiveUndoDisabled||e?b!==k.SKETCH_KEYS.redo||this.interactiveUndoDisabled||e?b!==k.SKETCH_KEYS.pan||e||(a.stopPropagation(),this._panEnabled=!0):(a.stopPropagation(),this.redo()):(a.stopPropagation(),this.undo()):(a.stopPropagation(),this._drawCompleteHandler(a))},f.ViewEventPriorities.TOOL),this.view.on("key-up",a=>{a.key===k.SKETCH_KEYS.pan&&(a.stopPropagation(),this._panEnabled=!1)},f.ViewEventPriorities.TOOL)])};d._addUndoRedoHandles=
function(){this._removeUndoRedoHandles();this._undoRedoHandles.add([this._editGeometry.on("vertex-remove",a=>{this.notifyChange("vertices");if("undo"===a.operation){const b=this._nativeEventHistory.undoStack.pop();this._nativeEventHistory.redoStack.push(b);const e=[...this._committedVertices];c.isSome(this._stagedVertex)&&e.push(this._coordinateHelper.pointToArray(this._stagedVertex));this.emit("undo",new g.VertexRemoveEvent(this.view,b,a.vertices[0].index,e))}}),this._editGeometry.on("vertex-add",
a=>{this.notifyChange("vertices");if("apply"===a.operation)a=new g.VertexAddEvent(this.view,this._nativeEventHistory.undoStack[this._nativeEventHistory.undoStack.length],this._committedVertices.length-1,this.vertices),this.emit("vertex-add",a),a.defaultPrevented&&(this._popVertexOnPointerMove=!0);else if("redo"===a.operation){const b=this._nativeEventHistory.redoStack.pop();this._nativeEventHistory.undoStack.push(b);const e=[...this._committedVertices];c.isSome(this._stagedVertex)&&e.push(this._coordinateHelper.pointToArray(this._stagedVertex));
this.emit("redo",new g.VertexAddEvent(this.view,b,a.vertices[0].index,e))}})])};d._removeViewHandles=function(){this._viewHandles.removeAll()};d._removeUndoRedoHandles=function(){this._undoRedoHandles.removeAll()};d._addDrawTool=function(a){this._drawTool=new x.DrawTool({view:a,elevationInfo:this.elevationInfo,hasZ:this.hasZ,geometryType:"polyline",mode:this.mode});this.view.toolViewManager.tools.push(this._drawTool);this.view.activeTool=this._drawTool;this._drawTool.on("vertex-add",b=>{1===b.vertices.length&&
this.emit("vertex-add",new g.VertexAddEvent(this.view,null,b.vertices[0].vertexIndex,this._drawTool.getVertexCoords()))});this._drawTool.on("cursor-update",b=>{1===b.vertices.length&&this.emit("cursor-update",new g.CursorUpdateEvent(this.view,null,b.vertices[0].vertexIndex,this._drawTool.getVertexCoords()))});this._drawTool.on("complete",b=>{this.emit("draw-complete",new g.DrawCompleteEvent(null,this._drawTool.getVertexCoords()));this._removeDrawTool()})};d._removeDrawTool=function(){c.isSome(this._drawTool)&&
(this.view.tools.remove(this._drawTool),this._drawTool=c.destroyMaybe(this._drawTool))};d._addVertex=function(a,b){a=this._coordinateHelper.fromArray(a);this._isDuplicateOfLastVertex(a)||(this._lastVertexUnsnapped=this._stagedVertexUnsnapped,this._popCursorVertex(),this._editGeometry.appendVertex(a),b=b||new Event("placeholder"),this._nativeEventHistory.undoStack.push(b))};d._updateCursor=function(a,b=!1){this._popCursorVertex();if(this._cursorScreenPoint){var e=this.getCoordsAndPointFromScreenPoint(this._cursorScreenPoint);
if(c.isSome(e)&&!b){this._pushCursorVertex(e.vertex);const v=()=>new g.CursorUpdateEvent(this.view,a,this._activeComponent.vertices.length,this.vertices,c.isSome(this._stagedVertex)?new z(this._stagedVertex):null);this.emit("cursor-update",v());c.isSome(this._snappingTask)&&this._snappingTask.promise.then(A=>{A.valid&&this.emit("cursor-update",v())},()=>{})}}};d._completeDrawing=function(a){this._activePointerId=null;this._popCursorVertex();2>this._committedVertices.length||(this._snappingTask=c.abortMaybe(this._snappingTask),
c.isSome(this._snappingManager)&&this._snappingManager.doneSnapping(),a=new g.DrawCompleteEvent(a,this.vertices),this.emit("draw-complete",a),a.defaultPrevented||this._removeViewHandles())};d._shouldHandlePointerEvent=function(a){return("mouse"!==a.pointerType||0===a.button)&&(c.isNone(this._activePointerId)||this._activePointerId===a.pointerId)};r._createClass(n,[{key:"_clickEnabled",get:function(){return"click"===this.mode||"hybrid"===this.mode}},{key:"_dragEnabled",get:function(){return"freehand"===
this.mode||"hybrid"===this.mode}}]);return n}(y);l.__decorate([p.property()],h.PolylineDrawAction.prototype,"_clickEnabled",null);l.__decorate([p.property()],h.PolylineDrawAction.prototype,"_dragEnabled",null);l.__decorate([p.property({type:u.drawingModes})],h.PolylineDrawAction.prototype,"mode",void 0);h.PolylineDrawAction=l.__decorate([w.subclass("esri.views.draw.PolylineDrawAction")],h.PolylineDrawAction);Object.defineProperty(h,"__esModule",{value:!0})});