// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../core/domUtils ../../core/maybe ../../core/watchUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/Logger ../../core/jsonMap ../../core/accessorSupport/decorators/subclass ../Widget ./widgetUtils ./jsxFactory".split(" "),function(ha,F,ia,M,ja,J,A,Ua,Va,Wa,Ba,Ca,Xa,ka){function N(a){a=a.getBoundingClientRect();return{width:a.width,height:a.height,top:a.top,right:a.right,
bottom:a.bottom,left:a.left,x:a.left,y:a.top}}function x(a){return null==a?window:"[object Window]"!==a.toString()?(a=a.ownerDocument)?a.defaultView||window:window:a}function Z(a){a=x(a);return{scrollLeft:a.pageXOffset,scrollTop:a.pageYOffset}}function P(a){var b=x(a).Element;return a instanceof b||a instanceof Element}function y(a){var b=x(a).HTMLElement;return a instanceof b||a instanceof HTMLElement}function la(a){if("undefined"===typeof ShadowRoot)return!1;var b=x(a).ShadowRoot;return a instanceof
b||a instanceof ShadowRoot}function B(a){return a?(a.nodeName||"").toLowerCase():null}function G(a){return((P(a)?a.ownerDocument:a.document)||window.document).documentElement}function aa(a){return N(G(a)).left+Z(a).scrollLeft}function E(a){return x(a).getComputedStyle(a)}function ba(a){a=E(a);return/auto|scroll|overlay|hidden/.test(a.overflow+a.overflowY+a.overflowX)}function Da(a,b,c){void 0===c&&(c=!1);var d=G(b);a=N(a);var f=y(b),e={scrollLeft:0,scrollTop:0},g={x:0,y:0};if(f||!f&&!c){if("body"!==
B(b)||ba(d))e=b!==x(b)&&y(b)?{scrollLeft:b.scrollLeft,scrollTop:b.scrollTop}:Z(b);y(b)?(g=N(b),g.x+=b.clientLeft,g.y+=b.clientTop):d&&(g.x=aa(d))}return{x:a.left+e.scrollLeft-g.x,y:a.top+e.scrollTop-g.y,width:a.width,height:a.height}}function ca(a){var b=N(a),c=a.offsetWidth,d=a.offsetHeight;1>=Math.abs(b.width-c)&&(c=b.width);1>=Math.abs(b.height-d)&&(d=b.height);return{x:a.offsetLeft,y:a.offsetTop,width:c,height:d}}function V(a){return"html"===B(a)?a:a.assignedSlot||a.parentNode||(la(a)?a.host:
null)||G(a)}function ma(a){return 0<=["html","body","#document"].indexOf(B(a))?a.ownerDocument.body:y(a)&&ba(a)?a:ma(V(a))}function Q(a,b){var c;void 0===b&&(b=[]);var d=ma(a);a=d===(null==(c=a.ownerDocument)?void 0:c.body);c=x(d);d=a?[c].concat(c.visualViewport||[],ba(d)?d:[]):d;b=b.concat(d);return a?b:b.concat(Q(V(d)))}function na(a){return y(a)&&"fixed"!==E(a).position?a.offsetParent:null}function R(a){for(var b=x(a),c=na(a);c&&0<=["table","td","th"].indexOf(B(c))&&"static"===E(c).position;)c=
na(c);if(c&&("html"===B(c)||"body"===B(c)&&"static"===E(c).position))return b;if(!c)a:{c=-1!==navigator.userAgent.toLowerCase().indexOf("firefox");if(-1===navigator.userAgent.indexOf("Trident")||!y(a)||"fixed"!==E(a).position)for(a=V(a);y(a)&&0>["html","body"].indexOf(B(a));){var d=E(a);if("none"!==d.transform||"none"!==d.perspective||"paint"===d.contain||-1!==["transform","perspective"].indexOf(d.willChange)||c&&"filter"===d.willChange||c&&d.filter&&"none"!==d.filter){c=a;break a}else a=a.parentNode}c=
null}return c||b}function Ea(a){function b(e){d.add(e.name);[].concat(e.requires||[],e.requiresIfExists||[]).forEach(function(g){d.has(g)||(g=c.get(g))&&b(g)});f.push(e)}var c=new Map,d=new Set,f=[];a.forEach(function(e){c.set(e.name,e)});a.forEach(function(e){d.has(e.name)||b(e)});return f}function Fa(a){var b=Ea(a);return Ga.reduce(function(c,d){return c.concat(b.filter(function(f){return f.phase===d}))},[])}function Ha(a){var b;return function(){b||(b=new Promise(function(c){Promise.resolve().then(function(){b=
void 0;c(a())})}));return b}}function C(a){return a.split("-")[0]}function Ia(a){var b=a.reduce(function(c,d){var f=c[d.name];c[d.name]=f?Object.assign({},f,d,{options:Object.assign({},f.options,d.options),data:Object.assign({},f.data,d.data)}):d;return c},{});return Object.keys(b).map(function(c){return b[c]})}function oa(a,b){var c=b.getRootNode&&b.getRootNode();if(a.contains(b))return!0;if(c&&la(c)){do{if(b&&a.isSameNode(b))return!0;b=b.parentNode||b.host}while(b)}return!1}function da(a){return Object.assign({},
a,{left:a.x,top:a.y,right:a.x+a.width,bottom:a.y+a.height})}function pa(a,b){if("viewport"===b){b=x(a);var c=G(a);b=b.visualViewport;var d=c.clientWidth;c=c.clientHeight;var f=0,e=0;b&&(d=b.width,c=b.height,/^((?!chrome|android).)*safari/i.test(navigator.userAgent)||(f=b.offsetLeft,e=b.offsetTop));a={width:d,height:c,x:f+aa(a),y:e};a=da(a)}else y(b)?(a=N(b),a.top+=b.clientTop,a.left+=b.clientLeft,a.bottom=a.top+b.clientHeight,a.right=a.left+b.clientWidth,a.width=b.clientWidth,a.height=b.clientHeight,
a.x=a.left,a.y=a.top):(e=G(a),a=G(e),d=Z(e),b=null==(c=e.ownerDocument)?void 0:c.body,c=z(a.scrollWidth,a.clientWidth,b?b.scrollWidth:0,b?b.clientWidth:0),f=z(a.scrollHeight,a.clientHeight,b?b.scrollHeight:0,b?b.clientHeight:0),e=-d.scrollLeft+aa(e),d=-d.scrollTop,"rtl"===E(b||a).direction&&(e+=z(a.clientWidth,b?b.clientWidth:0)-c),a=da({width:c,height:f,x:e,y:d}));return a}function Ja(a){var b=Q(V(a)),c=0<=["absolute","fixed"].indexOf(E(a).position)&&y(a)?R(a):a;return P(c)?b.filter(function(d){return P(d)&&
oa(d,c)&&"body"!==B(d)}):[]}function Ka(a,b,c){b="clippingParents"===b?Ja(a):[].concat(b);c=[].concat(b,[c]);c=c.reduce(function(d,f){f=pa(a,f);d.top=z(f.top,d.top);d.right=H(f.right,d.right);d.bottom=H(f.bottom,d.bottom);d.left=z(f.left,d.left);return d},pa(a,c[0]));c.width=c.right-c.left;c.height=c.bottom-c.top;c.x=c.left;c.y=c.top;return c}function ea(a){return 0<=["top","bottom"].indexOf(a)?"x":"y"}function qa(a){var b=a.reference,c=a.element,d=(a=a.placement)?C(a):null;a=a?a.split("-")[1]:null;
var f=b.x+b.width/2-c.width/2,e=b.y+b.height/2-c.height/2;switch(d){case "top":f={x:f,y:b.y-c.height};break;case "bottom":f={x:f,y:b.y+b.height};break;case "right":f={x:b.x+b.width,y:e};break;case "left":f={x:b.x-c.width,y:e};break;default:f={x:b.x,y:b.y}}d=d?ea(d):null;if(null!=d)switch(e="y"===d?"height":"width",a){case "start":f[d]-=b[e]/2-c[e]/2;break;case "end":f[d]+=b[e]/2-c[e]/2}return f}function ra(a){return Object.assign({},{top:0,right:0,bottom:0,left:0},a)}function sa(a,b){return b.reduce(function(c,
d){c[d]=a;return c},{})}function S(a,b){void 0===b&&(b={});var c=b;b=c.placement;b=void 0===b?a.placement:b;var d=c.boundary,f=void 0===d?"clippingParents":d;d=c.rootBoundary;var e=void 0===d?"viewport":d;d=c.elementContext;d=void 0===d?"popper":d;var g=c.altBoundary,k=void 0===g?!1:g;c=c.padding;c=void 0===c?0:c;c=ra("number"!==typeof c?c:sa(c,T));var p=a.elements.reference;g=a.rects.popper;k=a.elements[k?"popper"===d?"reference":"popper":d];f=Ka(P(k)?k:k.contextElement||G(a.elements.popper),f,e);
e=N(p);k=qa({reference:e,element:g,strategy:"absolute",placement:b});g=da(Object.assign({},g,k));e="popper"===d?g:e;var h={top:f.top-e.top+c.top,bottom:e.bottom-f.bottom+c.bottom,left:f.left-e.left+c.left,right:e.right-f.right+c.right};a=a.modifiersData.offset;if("popper"===d&&a){var n=a[b];Object.keys(h).forEach(function(m){var r=0<=["right","bottom"].indexOf(m)?1:-1,l=0<=["top","bottom"].indexOf(m)?"y":"x";h[m]+=n[l]*r})}return h}function ta(){for(var a=arguments.length,b=Array(a),c=0;c<a;c++)b[c]=
arguments[c];return!b.some(function(d){return!(d&&"function"===typeof d.getBoundingClientRect)})}function ua(a){var b,c=a.popper,d=a.popperRect,f=a.placement,e=a.offsets,g=a.position,k=a.gpuAcceleration,p=a.adaptive;a=a.roundOffsets;if(!0===a){a=e.y;var h=window.devicePixelRatio||1;a={x:W(W(e.x*h)/h)||0,y:W(W(a*h)/h)||0}}else a="function"===typeof a?a(e):e;h=a;a=h.x;a=void 0===a?0:a;h=h.y;h=void 0===h?0:h;var n=e.hasOwnProperty("x");e=e.hasOwnProperty("y");var m="left",r="top",l=window;if(p){var q=
R(c),t="clientHeight",v="clientWidth";q===x(c)&&(q=G(c),"static"!==E(q).position&&(t="scrollHeight",v="scrollWidth"));"top"===f&&(r="bottom",h-=q[t]-d.height,h*=k?1:-1);"left"===f&&(m="right",a-=q[v]-d.width,a*=k?1:-1)}c=Object.assign({position:g},p&&La);if(k){var u;return Object.assign({},c,(u={},u[r]=e?"0":"",u[m]=n?"0":"",u.transform=2>(l.devicePixelRatio||1)?"translate("+a+"px, "+h+"px)":"translate3d("+a+"px, "+h+"px, 0)",u))}return Object.assign({},c,(b={},b[r]=e?h+"px":"",b[m]=n?a+"px":"",b.transform=
"",b))}function X(a){return a.replace(/left|right|bottom|top/g,function(b){return Ma[b]})}function va(a){return a.replace(/start|end/g,function(b){return Na[b]})}function Oa(a,b){void 0===b&&(b={});var c=b.boundary,d=b.rootBoundary,f=b.padding,e=b.flipVariations,g=b.allowedAutoPlacements,k=void 0===g?wa:g,p=b.placement.split("-")[1];b=p?e?xa:xa.filter(function(n){return n.split("-")[1]===p}):T;e=b.filter(function(n){return 0<=k.indexOf(n)});0===e.length&&(e=b);var h=e.reduce(function(n,m){n[m]=S(a,
{placement:m,boundary:c,rootBoundary:d,padding:f})[C(m)];return n},{});return Object.keys(h).sort(function(n,m){return h[n]-h[m]})}function Pa(a){if("auto"===C(a))return[];var b=X(a);return[va(a),b,va(b)]}function ya(a,b,c){void 0===c&&(c={x:0,y:0});return{top:a.top-b.height-c.y,right:a.right-b.width+c.x,bottom:a.bottom-b.height+c.y,left:a.left-b.width-c.x}}function za(a){return["top","right","bottom","left"].some(function(b){return 0<=a[b]})}var T=["top","bottom","right","left"],xa=T.reduce(function(a,
b){return a.concat([b+"-start",b+"-end"])},[]),wa=[].concat(T,["auto"]).reduce(function(a,b){return a.concat([b,b+"-start",b+"-end"])},[]),Ga="beforeRead read afterRead beforeMain main afterMain beforeWrite write afterWrite".split(" "),z=Math.max,H=Math.min,W=Math.round,Aa={placement:"bottom",modifiers:[],strategy:"absolute"},Y={passive:!0},La={top:"auto",right:"auto",bottom:"auto",left:"auto"},Ma={left:"right",right:"left",bottom:"top",top:"bottom"},Na={start:"end",end:"start"},Ra=function(a){void 0===
a&&(a={});var b=a.defaultModifiers,c=void 0===b?[]:b;a=a.defaultOptions;var d=void 0===a?Aa:a;return function(f,e,g){function k(){h.orderedModifiers.forEach(function(l){var q=l.name,t=l.options;t=void 0===t?{}:t;l=l.effect;"function"===typeof l&&(q=l({state:h,name:q,instance:r,options:t}),n.push(q||function(){}))})}function p(){n.forEach(function(l){return l()});n=[]}void 0===g&&(g=d);var h={placement:"bottom",orderedModifiers:[],options:Object.assign({},Aa,d),modifiersData:{},elements:{reference:f,
popper:e},attributes:{},styles:{}},n=[],m=!1,r={state:h,setOptions:function(l){p();h.options=Object.assign({},d,h.options,l);h.scrollParents={reference:P(f)?Q(f):f.contextElement?Q(f.contextElement):[],popper:Q(e)};l=Fa(Ia([].concat(c,h.options.modifiers)));h.orderedModifiers=l.filter(function(q){return q.enabled});k();return r.update()},forceUpdate:function(){if(!m){var l=h.elements,q=l.reference;l=l.popper;if(ta(q,l))for(h.rects={reference:Da(q,R(l),"fixed"===h.options.strategy),popper:ca(l)},h.reset=
!1,h.placement=h.options.placement,h.orderedModifiers.forEach(function(u){return h.modifiersData[u.name]=Object.assign({},u.data)}),q=0;q<h.orderedModifiers.length;q++)if(!0===h.reset)h.reset=!1,q=-1;else{var t=h.orderedModifiers[q];l=t.fn;var v=t.options;v=void 0===v?{}:v;t=t.name;"function"===typeof l&&(h=l({state:h,options:v,name:t,instance:r})||h)}}},update:Ha(function(){return new Promise(function(l){r.forceUpdate();l(h)})}),destroy:function(){p();m=!0}};if(!ta(f,e))return r;r.setOptions(g).then(function(l){if(!m&&
g.onFirstUpdate)g.onFirstUpdate(l)});return r}}({defaultModifiers:[{name:"eventListeners",enabled:!0,phase:"write",fn:function(){},effect:function(a){var b=a.state,c=a.instance;a=a.options;var d=a.scroll,f=void 0===d?!0:d;a=a.resize;var e=void 0===a?!0:a,g=x(b.elements.popper),k=[].concat(b.scrollParents.reference,b.scrollParents.popper);f&&k.forEach(function(p){p.addEventListener("scroll",c.update,Y)});e&&g.addEventListener("resize",c.update,Y);return function(){f&&k.forEach(function(p){p.removeEventListener("scroll",
c.update,Y)});e&&g.removeEventListener("resize",c.update,Y)}},data:{}},{name:"popperOffsets",enabled:!0,phase:"read",fn:function(a){var b=a.state;b.modifiersData[a.name]=qa({reference:b.rects.reference,element:b.rects.popper,strategy:"absolute",placement:b.placement})},data:{}},{name:"computeStyles",enabled:!0,phase:"beforeWrite",fn:function(a){var b=a.state,c=a.options;a=c.gpuAcceleration;a=void 0===a?!0:a;var d=c.adaptive;d=void 0===d?!0:d;c=c.roundOffsets;c=void 0===c?!0:c;a={placement:C(b.placement),
popper:b.elements.popper,popperRect:b.rects.popper,gpuAcceleration:a};null!=b.modifiersData.popperOffsets&&(b.styles.popper=Object.assign({},b.styles.popper,ua(Object.assign({},a,{offsets:b.modifiersData.popperOffsets,position:b.options.strategy,adaptive:d,roundOffsets:c}))));null!=b.modifiersData.arrow&&(b.styles.arrow=Object.assign({},b.styles.arrow,ua(Object.assign({},a,{offsets:b.modifiersData.arrow,position:"absolute",adaptive:!1,roundOffsets:c}))));b.attributes.popper=Object.assign({},b.attributes.popper,
{"data-popper-placement":b.placement})},data:{}},{name:"applyStyles",enabled:!0,phase:"write",fn:function(a){var b=a.state;Object.keys(b.elements).forEach(function(c){var d=b.styles[c]||{},f=b.attributes[c]||{},e=b.elements[c];y(e)&&B(e)&&(Object.assign(e.style,d),Object.keys(f).forEach(function(g){var k=f[g];!1===k?e.removeAttribute(g):e.setAttribute(g,!0===k?"":k)}))})},effect:function(a){var b=a.state,c={popper:{position:b.options.strategy,left:"0",top:"0",margin:"0"},arrow:{position:"absolute"},
reference:{}};Object.assign(b.elements.popper.style,c.popper);b.styles=c;b.elements.arrow&&Object.assign(b.elements.arrow.style,c.arrow);return function(){Object.keys(b.elements).forEach(function(d){var f=b.elements[d],e=b.attributes[d]||{};d=Object.keys(b.styles.hasOwnProperty(d)?b.styles[d]:c[d]).reduce(function(g,k){g[k]="";return g},{});y(f)&&B(f)&&(Object.assign(f.style,d),Object.keys(e).forEach(function(g){f.removeAttribute(g)}))})}},requires:["computeStyles"]},{name:"offset",enabled:!0,phase:"main",
requires:["popperOffsets"],fn:function(a){var b=a.state,c=a.name;a=a.options.offset;var d=void 0===a?[0,0]:a;a=wa.reduce(function(g,k){var p=b.rects;var h=C(k);var n=0<=["left","top"].indexOf(h)?-1:1,m="function"===typeof d?d(Object.assign({},p,{placement:k})):d;p=m[0];m=m[1];p=p||0;m=(m||0)*n;h=0<=["left","right"].indexOf(h)?{x:m,y:p}:{x:p,y:m};g[k]=h;return g},{});var f=a[b.placement],e=f.x;f=f.y;null!=b.modifiersData.popperOffsets&&(b.modifiersData.popperOffsets.x+=e,b.modifiersData.popperOffsets.y+=
f);b.modifiersData[c]=a}},{name:"flip",enabled:!0,phase:"main",fn:function(a){var b=a.state,c=a.options;a=a.name;if(!b.modifiersData[a]._skip){var d=c.mainAxis;d=void 0===d?!0:d;var f=c.altAxis;f=void 0===f?!0:f;var e=c.fallbackPlacements,g=c.padding,k=c.boundary,p=c.rootBoundary,h=c.altBoundary,n=c.flipVariations,m=void 0===n?!0:n,r=c.allowedAutoPlacements;c=b.options.placement;n=C(c);e=e||(n!==c&&m?Pa(c):[X(c)]);var l=[c].concat(e).reduce(function(I,O){return I.concat("auto"===C(O)?Oa(b,{placement:O,
boundary:k,rootBoundary:p,padding:g,flipVariations:m,allowedAutoPlacements:r}):O)},[]);c=b.rects.reference;e=b.rects.popper;var q=new Map;n=!0;for(var t=l[0],v=0;v<l.length;v++){var u=l[v],U=C(u),D="start"===u.split("-")[1],w=0<=["top","bottom"].indexOf(U),K=w?"width":"height",L=S(b,{placement:u,boundary:k,rootBoundary:p,altBoundary:h,padding:g});D=w?D?"right":"left":D?"bottom":"top";c[K]>e[K]&&(D=X(D));K=X(D);w=[];d&&w.push(0>=L[U]);f&&w.push(0>=L[D],0>=L[K]);if(w.every(function(I){return I})){t=
u;n=!1;break}q.set(u,w)}if(n)for(d=function(I){var O=l.find(function(fa){if(fa=q.get(fa))return fa.slice(0,I).every(function(Qa){return Qa})});if(O)return t=O,"break"},f=m?3:1;0<f&&"break"!==d(f);f--);b.placement!==t&&(b.modifiersData[a]._skip=!0,b.placement=t,b.reset=!0)}},requiresIfExists:["offset"],data:{_skip:!1}},{name:"preventOverflow",enabled:!0,phase:"main",fn:function(a){var b=a.state,c=a.options;a=a.name;var d=c.mainAxis,f=void 0===d?!0:d;d=c.altAxis;var e=void 0===d?!1:d;d=c.tether;d=void 0===
d?!0:d;var g=c.tetherOffset,k=void 0===g?0:g,p=S(b,{boundary:c.boundary,rootBoundary:c.rootBoundary,padding:c.padding,altBoundary:c.altBoundary});c=C(b.placement);var h=b.placement.split("-")[1],n=!h,m=ea(c);c="x"===m?"y":"x";g=b.modifiersData.popperOffsets;var r=b.rects.reference,l=b.rects.popper,q="function"===typeof k?k(Object.assign({},b.rects,{placement:b.placement})):k;k={x:0,y:0};if(g){if(f||e){var t="y"===m?"top":"left",v="y"===m?"bottom":"right",u="y"===m?"height":"width",U=g[m],D=g[m]+p[t],
w=g[m]-p[v],K=d?-l[u]/2:0,L="start"===h?r[u]:l[u];h="start"===h?-l[u]:-r[u];l=b.elements.arrow;l=d&&l?ca(l):{width:0,height:0};var I=b.modifiersData["arrow#persistent"]?b.modifiersData["arrow#persistent"].padding:{top:0,right:0,bottom:0,left:0};t=I[t];v=I[v];l=z(0,H(r[u],l[u]));L=n?r[u]/2-K-l-t-q:L-l-t-q;r=n?-r[u]/2+K+l+v+q:h+l+v+q;n=b.elements.arrow&&R(b.elements.arrow);q=b.modifiersData.offset?b.modifiersData.offset[b.placement][m]:0;n=g[m]+L-q-(n?"y"===m?n.clientTop||0:n.clientLeft||0:0);r=g[m]+
r-q;f&&(f=d?H(D,n):D,w=d?z(w,r):w,f=z(f,H(U,w)),g[m]=f,k[m]=f-U);e&&(e=g[c],f=e+p["x"===m?"top":"left"],p=e-p["x"===m?"bottom":"right"],f=d?H(f,n):f,d=d?z(p,r):p,d=z(f,H(e,d)),g[c]=d,k[c]=d-e)}b.modifiersData[a]=k}},requiresIfExists:["offset"]},{name:"arrow",enabled:!0,phase:"main",fn:function(a){var b,c=a.state,d=a.name,f=a.options,e=c.elements.arrow,g=c.modifiersData.popperOffsets,k=C(c.placement);a=ea(k);k=0<=["left","right"].indexOf(k)?"height":"width";if(e&&g){f=f.padding;f="function"===typeof f?
f(Object.assign({},c.rects,{placement:c.placement})):f;f=ra("number"!==typeof f?f:sa(f,T));var p=ca(e),h="y"===a?"top":"left",n="y"===a?"bottom":"right",m=c.rects.reference[k]+c.rects.reference[a]-g[a]-c.rects.popper[k];g=g[a]-c.rects.reference[a];e=(e=R(e))?"y"===a?e.clientHeight||0:e.clientWidth||0:0;g=e/2-p[k]/2+(m/2-g/2);k=z(f[h],H(g,e-p[k]-f[n]));c.modifiersData[d]=(b={},b[a]=k,b.centerOffset=k-g,b)}},effect:function(a){var b=a.state;a=a.options.element;a=void 0===a?"[data-popper-arrow]":a;if(null!=
a){if("string"===typeof a&&(a=b.elements.popper.querySelector(a),!a))return;oa(b.elements.popper,a)&&(b.elements.arrow=a)}},requires:["popperOffsets"],requiresIfExists:["preventOverflow"]},{name:"hide",enabled:!0,phase:"main",requiresIfExists:["preventOverflow"],fn:function(a){var b=a.state;a=a.name;var c=b.rects.reference,d=b.rects.popper,f=b.modifiersData.preventOverflow,e=S(b,{elementContext:"reference"}),g=S(b,{altBoundary:!0});c=ya(e,c);d=ya(g,d,f);f=za(c);g=za(d);b.modifiersData[a]={referenceClippingOffsets:c,
popperEscapeOffsets:d,isReferenceHidden:f,hasPopperEscaped:g};b.attributes.popper=Object.assign({},b.attributes.popper,{"data-popper-reference-hidden":f,"data-popper-escaped":g})}}]});const Sa="bottom bottom-start bottom-end left left-start left-end right right-start right-end top top-start top-end".split(" "),Ta={position:"fixed","z-index":"1000"};A=function(a){function b(d,f){var e=a.call(this,d,f)||this;e._popper=null;e._contentNode=null;e._renderAttached=!1;e._rootNode=null;e.anchorElement=null;
e.offset=[0,0];e.open=!1;e.renderContentFunction=null;e._afterRootCreate=g=>{e._rootNode=g};e._afterContentCreate=g=>{e._contentNode=g};e._updatePosition=()=>{M.isSome(e._popper)&&e._popper.update()};return e}ha._inheritsLoose(b,a);var c=b.prototype;c.initialize=function(){this.when(()=>{this._projector.append(document.body,this.render);this._renderAttached=!0});this.own(ja.init(this,["open","anchorElement"],()=>this._buildPopper()),ja.init(this,["placement","offset"],()=>this._setPopperOptions()))};
c.destroy=function(){this.renderContentFunction=this.anchorElement=this.owner=null;this._renderAttached&&(this._projector.detach(this.render),this._renderAttached=!1);M.isSome(this._rootNode)&&(ia.remove(this._rootNode),this._rootNode=null);this._contentNode=null;M.isSome(this._popper)&&(this._popper.destroy(),this._popper=null)};c.render=function(){const {open:d,owner:f,renderContentFunction:e}=this;return ka.tsx("div",{afterCreate:this._afterRootCreate,class:this.classes("esri-popover",d?"esri-popover--open":
null),styles:Ta},ka.tsx("div",{afterCreate:this._afterContentCreate,afterUpdate:this._updatePosition},d&&(null==e?void 0:e.call(f))))};c._buildPopper=function(){M.isSome(this._popper)&&(this._popper.destroy(),this._popper=null);const d=this._contentNode;if(!M.isNone(d)&&this.open&&this.renderContentFunction){var f=this._getAnchor();f&&(this._popper=Ra(f,d),this._setPopperOptions())}};c._setPopperOptions=function(){const {placement:d,offset:f,_popper:e}=this;M.isNone(e)||(e.setOptions({placement:d,
modifiers:[{name:"offset",options:{offset:f}}]}),e.forceUpdate())};c._getAnchor=function(){const {anchorElement:d}=this;return ia.byId("function"===typeof d?d():d)};ha._createClass(b,[{key:"container",set:function(d){}},{key:"owner",set:function(d){this._set("owner",d)}},{key:"placement",get:function(){return"top"},set:function(d){-1===Sa.indexOf(d)?this._clearOverride("placement"):this._override("placement",d)}}]);return b}(Ca);F.__decorate([J.property()],A.prototype,"anchorElement",void 0);F.__decorate([J.property()],
A.prototype,"container",null);F.__decorate([J.property()],A.prototype,"offset",void 0);F.__decorate([J.property()],A.prototype,"open",void 0);F.__decorate([J.property()],A.prototype,"owner",null);F.__decorate([J.property()],A.prototype,"placement",null);F.__decorate([J.property()],A.prototype,"renderContentFunction",void 0);return A=F.__decorate([Ba.subclass("esri.widgets.support.Popover")],A)});