// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define(["../../../chunks/_rollupPluginBabelHelpers","../../../core/maybe","../../webgl/rasterUtils"],function(m,d,e){const l={bandCount:3,outMin:0,outMax:1,minCutOff:[0,0,0],maxCutOff:[255,255,255],factor:[1/255,1/255,1/255],useGamma:!1,gamma:[1,1,1],gammaCorrection:[1,1,1],colormap:null,colormapOffset:null,type:"stretch"};return function(){function h(a,b,c=null,g=null){this._interpolation=this._bandIds=this._symbolizerParameters=this._source=this._memoryUsed=null;this._dirty=!1;this._transformGrid=
null;this.isRendereredSource=!1;this.lij=this.rawPixelData=this.symbolizerRenderer=null;this.scale=1;this.offset=[0,0];this.opacity=1;this.lij=a;this.source=b;this.width=c||b.width;this.height=g||b.height}var f=h.prototype;f.bind=function(a){if(!(this.source&&this.source.pixels&&0<this.source.pixels.length))return!1;this._rasterTexture&&!this._dirty||this._updateRasterTexture(a,this.bandIds);this._rasterTexture&&(this._updateColormapTexture(a),this.transformGrid&&!this._transformGridTexture&&(this._transformGridTexture=
e.createTransformTexture(a,this.transformGrid)));return!0};f.getUniforms=function(){const a=e.getBasicGridUniforms(this.scale,this.offset),{symbolizerParameters:b,transformGrid:c,width:g,height:k,opacity:n}=this,p=e.getCommonUniforms(c,[g,k],[this.source.width,this.source.height],n),q=b.colormap?e.getColormapUniforms(b.colormap,b.colormapOffset):null,r="stretch"===this.symbolizerParameters.type?e.getStretchUniforms(this.symbolizerParameters):null,t="hillshade"===this.symbolizerParameters.type?e.getShadedReliefUniforms(this.symbolizerParameters):
null;return{basic:a,common:p,colormap:q,stretch:r,hillshade:t}};f.getTextures=function(){const a=[],b=[];this._rasterTexture&&(b.push(this._rasterTexture),a.push("u_image"),this._transformGridTexture&&(b.push(this._transformGridTexture),a.push("u_transformGrid")),this._colormapTexture&&(b.push(this._colormapTexture),a.push("u_colormap")));return{names:a,textures:b}};f.release=function(){this._rasterTexture=d.disposeMaybe(this._rasterTexture);this._transformGridTexture=d.disposeMaybe(this._transformGridTexture);
this._colormapTexture=d.disposeMaybe(this._colormapTexture);this.rawPixelData=this.transformGrid=this.source=null;return!0};f._updateRasterTexture=function(a,b){const c=this.source?this.source.extractBands(b):null;if(c&&c.pixels&&0<c.pixels.length){b=d.isNone(b)&&d.isNone(this.bandIds)||d.isSome(b)&&d.isSome(this.bandIds)&&b.join("")===this.bandIds.join("");if(this._rasterTexture){if(b)return;this._rasterTexture.dispose();this._rasterTexture=null}this._rasterTexture=e.createRasterTexture(a,c,this.interpolation||
"nearest",this.isRendereredSource)}else this._rasterTexture&&(this._rasterTexture.dispose(),this._rasterTexture=null)};f._updateColormapTexture=function(a){const b=this._colormap,c=this.symbolizerParameters.colormap;if(!c)this._colormapTexture&&(this._colormapTexture.dispose(),this._colormapTexture=null),this._colormap=null;else if(!b)this._colormapTexture=e.createColormapTexture(a,c),this._colormap=c;else if(c.length!==b.length||c.some((g,k)=>g!==b[k]))this._colormapTexture&&(this._colormapTexture.dispose(),
this._colormapTexture=null),this._colormapTexture=e.createColormapTexture(a,c),this._colormap=c};m._createClass(h,[{key:"source",get:function(){return this._source},set:function(a){this._source=a;this._rasterTexture&&(this._rasterTexture.dispose(),this._memoryUsed=this._rasterTexture=null)}},{key:"symbolizerParameters",get:function(){return this.isRendereredSource?{...l,maxCutOff:[1,1,1],factor:[1,1,1]}:this._symbolizerParameters||l},set:function(a){this._symbolizerParameters=a}},{key:"bandIds",get:function(){return this._bandIds},
set:function(a){d.isSome(a)&&0<a.length?this._bandIds&&a.every((b,c)=>this._bandIds[c]?b===this._bandIds[c]:!1)||(this._bandIds=a,this._dirty=!0):this._bandIds=null}},{key:"interpolation",get:function(){return this._interpolation},set:function(a){this._interpolation=a;this._rasterTexture&&this._rasterTexture.setSamplingMode("bilinear"===a?9729:9728)}},{key:"transformGrid",get:function(){return this._transformGrid},set:function(a){this._transformGrid=a;this._transformGridTexture&&(this._transformGridTexture.dispose(),
this._memoryUsed=this._transformGridTexture=null)}},{key:"memoryUsage",get:function(){if(d.isNone(this._memoryUsed)){const a=this.getTextures();if(null==a)return 0;this._memoryUsed=a.textures.map(b=>b.descriptor.width*b.descriptor.height*4).reduce((b,c)=>b+c,0)}return this._memoryUsed}}]);return h}()});