// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/Handles ../../../../core/maybe ../../../../chunks/mat4 ../../../../chunks/mat4f64 ../../../../chunks/vec3 ../../../../chunks/vec3f64 ../../../../chunks/vec4 ../../../../chunks/vec4f32 ../../../../geometry/support/vectorStacks ./Object3DVisualElement ../../webgl-engine/lib/Geometry ../../webgl-engine/lib/GeometryUtil ../../webgl-engine/materials/ColorMaterial ../../webgl-engine/materials/RibbonLineMaterial".split(" "),function(m,
n,u,v,h,w,d,k,p,q,r,l,x,y,z,A){l=function(t){function f(b){var a=t.call(this,b)||this;a._handles=new u;a._quadMaterial=null;a._outlineMaterial=null;a._maxSize=0;a._position=k.create();a._up=k.create();a._right=k.create();a._renderOccluded=4;a._color=q.fromValues(1,0,0,1);a._outlineColor=q.fromValues(0,0,0,1);a._outlineSize=0;a._size=32;a._outlineRenderOccluded=16;a.applyProps(b);return a}n._inheritsLoose(f,t);var c=f.prototype;c.createExternalResources=function(){this._quadMaterial=new z.ColorMaterial(this.quadMaterialParameters);
this._outlineMaterial=new A.RibbonLineMaterial(this.outlineMaterialParameters);this._handles.add(this.view.state.watch("camera",()=>this._updateTransform()))};c.destroyExternalResources=function(){this._outlineMaterial=this._quadMaterial=null;this._handles.removeAll()};c.forEachExternalMaterial=function(b){b(this._quadMaterial);b(this._outlineMaterial)};c.createGeometries=function(b){this._createQuadGeometry(b);this._createOutlineGeometry(b);this._updateTransform(b)};c._createQuadGeometry=function(b){const a=
this._quadGeometryData(this._up,this._right);b.addGeometry(a,this._quadMaterial)};c._createOutlineGeometry=function(b){if(0!==this._outlineSize){var a=d.add(r.sv3d.get(),this._up,this._right);a=y.createPolylineGeometry([this._up,a,this._right]);b.addGeometry(a,this._outlineMaterial)}};c._updateTransform=function(b=this.object){var a=this._size*this.view.state.camera.computeScreenPixelSizeAt(this._position);a=Math.min(this._maxSize,a);h.identity(e);h.translate(e,e,this._position);h.scale(e,e,[a,a,
a]);v.isSome(b)&&(b.transformation=e)};c._quadGeometryData=function(b,a){const g=d.add(r.sv3d.get(),b,a);return new x.Geometry([["position",{size:3,data:[0,0,0,...a,...b,...g],exclusive:!0}]],[["position",new Uint16Array([0,1,2,1,2,3])]])};c._updateQuadMaterial=function(){this._quadMaterial&&this._quadMaterial.setParameterValues(this.quadMaterialParameters)};c._updateOutlineMaterial=function(){this._outlineMaterial&&this._outlineMaterial.setParameterValues(this.outlineMaterialParameters)};n._createClass(f,
[{key:"renderOccluded",get:function(){return this._renderOccluded},set:function(b){b!==this._renderOccluded&&(this._renderOccluded=b,this._updateQuadMaterial())}},{key:"color",get:function(){return this._color},set:function(b){p.copy(this._color,b);this._updateQuadMaterial()}},{key:"outlineColor",get:function(){return this._outlineColor},set:function(b){p.copy(this._outlineColor,b);this._updateOutlineMaterial()}},{key:"outlineSize",get:function(){return this._outlineSize},set:function(b){const a=
0===this._outlineSize!==(0===b);this._outlineSize=b;a?this.recreateGeometry():this._updateOutlineMaterial()}},{key:"size",get:function(){return this._size},set:function(b){b!==this._size&&(this._size=b,this._updateTransform())}},{key:"outlineRenderOccluded",get:function(){return this._outlineRenderOccluded},set:function(b){this._outlineRenderOccluded=b;this._updateOutlineMaterial()}},{key:"geometry",set:function({previous:b,center:a,next:g}){this._maxSize=Math.min(d.distance(a,b),d.distance(a,g))/
3;d.normalize(this._up,d.subtract(this._up,b,a));d.normalize(this._right,d.subtract(this._right,g,a));d.copy(this._position,a);this.recreateGeometry()}},{key:"quadMaterialParameters",get:function(){return{color:this._color,transparent:!0,writeDepth:!1,polygonOffset:!0,renderOccluded:this._renderOccluded}}},{key:"outlineMaterialParameters",get:function(){return{color:this._outlineColor,width:this._outlineSize,renderOccluded:this._outlineRenderOccluded}}}]);return f}(l.Object3DVisualElement);const e=
w.create();m.RightAngleQuadVisualElement=l;Object.defineProperty(m,"__esModule",{value:!0})});