// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../core/screenUtils ../core/watchUtils ../core/accessorSupport/decorators/aliasOf ../core/has ../core/accessorSupport/decorators/cast ../core/Logger ../core/jsonMap ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/subclass ./Widget ./ScaleBar/ScaleBarViewModel ./support/widgetUtils ./support/decorators/messageBundle ./support/jsxFactory".split(" "),function(n,f,v,p,w,e,q,B,C,h,x,y,z,D,A,c){e=function(r){function k(a,
b){a=r.call(this,a,b)||this;a.label=void 0;a.messages=null;a.unit="non-metric";a.view=null;a.viewModel=new z;return a}n._inheritsLoose(k,r);var g=k.prototype;g.initialize=function(){this.own([p.whenTrue(this,"view.stationary",()=>this.scheduleRender()),p.watch(this,["view.center","view.scale","view.zoom"],()=>{this.view.stationary&&this.scheduleRender()})])};g.castStyle=function(a){return"line"===a?a:"ruler"};g.castUnit=function(a){return"metric"===a||"dual"===a?a:"non-metric"};g.render=function(){var a=
"disabled"===this.get("viewModel.state");const b={["esri-disabled"]:a};let d,t;if(!a){const {unit:l,style:u}=this;a="metric"===l||"dual"===l;if("non-metric"===l||"dual"===l){const m=this.viewModel.getScaleBarProperties(50,"non-metric");m&&(t="ruler"===u?this._renderRuler(m):this._renderLine(m,"bottom"))}a&&(a=this.viewModel.getScaleBarProperties(50,"metric"))&&(d="ruler"===u?this._renderRuler(a):this._renderLine(a,"top"))}return c.tsx("div",{afterCreate:this._handleRootCreateOrUpdate,afterUpdate:this._handleRootCreateOrUpdate,
bind:this,class:this.classes("esri-scale-bar esri-widget",b)},d,t)};g._renderRuler=function(a){const b=2*Math.round(a.length),{messages:d}=this;a=`${2*a.value} ${d[a.unit]||d.unknownUnit}`;return c.tsx("div",{class:this.classes("esri-scale-bar__bar-container","esri-scale-bar__bar-container--ruler"),key:"esri-scale-bar__ruler"},c.tsx("div",{class:"esri-scale-bar__ruler",styles:{width:`${b}px`}},c.tsx("div",{class:"esri-scale-bar__ruler-block"}),c.tsx("div",{class:"esri-scale-bar__ruler-block"}),c.tsx("div",
{class:"esri-scale-bar__ruler-block"}),c.tsx("div",{class:"esri-scale-bar__ruler-block"})),c.tsx("div",{class:this.classes("esri-scale-bar__label-container","esri-scale-bar__label-container--ruler")},c.tsx("div",{class:"esri-scale-bar__label"},"0"),c.tsx("div",{class:"esri-scale-bar__label"},a)))};g._renderLine=function(a,b){var {messages:d}=this;d=`${2*a.value} ${d[a.unit]||d.unknownUnit}`;d=c.tsx("div",{class:this.classes("esri-scale-bar__label-container","esri-scale-bar__label-container--line",
{["esri-scale-bar__label-container--top"]:"top"===b,["esri-scale-bar__label-container--bottom"]:"bottom"===b}),key:"esri-scale-bar__label"},c.tsx("div",{class:"esri-scale-bar__label"},d));a=2*Math.round(a.length);b=c.tsx("div",{class:this.classes("esri-scale-bar__line",{["esri-scale-bar__line--top"]:"top"===b,["esri-scale-bar__line--bottom"]:"bottom"===b}),key:"esri-scale-bar__line",styles:{width:`${a}px`}});return c.tsx("div",{class:this.classes("esri-scale-bar__bar-container","esri-scale-bar__bar-container--line"),
key:"esri-scale-bar__line-container"},[b,d])};g._handleRootCreateOrUpdate=function(a){const b=this.viewModel;b&&(a=a.getBoundingClientRect(),a=v.createScreenPoint(a.left+window.pageXOffset,a.top+window.pageYOffset),a.x!==b.scaleComputedFrom.x||a.y!==b.scaleComputedFrom.y)&&(b.scaleComputedFrom=a)};n._createClass(k,[{key:"style",set:function(a){this._set("style","dual"===this.unit?"line":a)}}]);return k}(y);f.__decorate([h.property({aliasOf:{source:"messages.widgetLabel",overridable:!0}})],e.prototype,
"label",void 0);f.__decorate([h.property(),A.messageBundle("esri/widgets/ScaleBar/t9n/ScaleBar")],e.prototype,"messages",void 0);f.__decorate([h.property()],e.prototype,"style",null);f.__decorate([q.cast("style")],e.prototype,"castStyle",null);f.__decorate([h.property()],e.prototype,"unit",void 0);f.__decorate([q.cast("unit")],e.prototype,"castUnit",null);f.__decorate([w.aliasOf("viewModel.view")],e.prototype,"view",void 0);f.__decorate([h.property()],e.prototype,"viewModel",void 0);return e=f.__decorate([x.subclass("esri.widgets.ScaleBar")],
e)});