// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../geometry ../../core/Accessor ../../core/maybe ../../core/screenUtils ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/Logger ../../core/jsonMap ../../core/accessorSupport/decorators/subclass ../../geometry/support/geodesicUtils ../../geometry/support/normalizeUtils ../../geometry/support/spatialReferenceUtils ../../geometry/support/webMercatorUtils ../../geometry/support/WKIDUnitConversion ../../geometry/SpatialReference ../../geometry/Polyline ../../geometry/Point".split(" "),
function(t,n,l,y,z,q,r,H,I,J,K,A,u,B,C,D,p,E,F,v){function w(m,k){const {x:g,y:a}="decimal-degrees"===m?D.webMercatorToGeographic(k,!0):k;return[g,a]}function x({state:{paddedViewState:m},spatialReference:k,width:g}){return k.isWrappable&&m.worldScreenWidth<g}l=function(m){function k(a){a=m.call(this,a)||this;a.scaleComputedFrom=q.createScreenPoint();a.view=null;return a}t._inheritsLoose(k,m);var g=k.prototype;g.getScaleBarProperties=function(a,b){if("disabled"===this.state||isNaN(a)||!b)return null;
const e=this._getDistanceInKm(this.view,this.scaleComputedFrom);return z.isNone(e)?null:"metric"===b?this._getScaleBarProps(a,e,"metric"):this._getScaleBarProps(a,e/1.609,"non-metric")};g._getLocationUnit=function(){const a=this.get("view.spatialReference"),{isWebMercator:b,wkid:e,wkt:d}=a;return b||d&&-1<d.indexOf("WGS_1984_Web_Mercator")?"decimal-degrees":null!=p[e]||d&&-1<d.indexOf("PROJCS")?"linear-unit":"unknown"};g._getDistanceInKm=function(a,b){const {state:e,spatialReference:d}=a;var c=this._getLocationUnit();
if("linear-unit"===c){var h=e.extent.width;({wkid:c}=d);null!=p[c]?c=p.values[p[c]]:({wkt:c}=d,a=c.lastIndexOf(",")+1,b=c.lastIndexOf("]]"),c=parseFloat(c.substring(a,b)));return h*c/1E3}const [f,G]=this._getScaleMeasuringPoints(a,b);a="decimal-degrees"===c||d.isGeographic&&!u.isSupported(d)?E.WGS84:d;c=new F({paths:[[w(c,f),w(c,G)]],spatialReference:a});c=B.straightLineDensify(c,10);try{[h]=u.geodesicLengths([c],"kilometers")}catch{return null}return h};g._getScaleMeasuringPoints=function(a,b){const {width:e,
height:d,position:c,spatialReference:h}=a;if(x(a))return{valid:b}=C.getInfo(h),a=new v(b[0],0,h),b=new v(b[1],0,h),[a,b];var f=b.y-c[1];f>d?f=d:0>f&&(f=0);b=q.createScreenPoint(0,f);f=q.createScreenPoint(e,f);b=a.toMap(b);a=a.toMap(f);return[b,a]};g._getScaleBarProps=function(a,b,e){var {view:d}=this;d=x(d)?d.state.paddedViewState.worldScreenWidth:d.width;b=a*b/d;e="metric"===e?"km":"mi";.1>b&&("mi"===e?(b*=5280,e="ft"):"km"===e&&(b*=1E3,e="m"));for(d=0;1<=b;)b/=10,d++;var c=this._getConstraints(b);
if(!c)return null;const {min:h,max:f}=c;c=f/b>=b/h?h:f;return{length:c/b*a,value:10**d*c,unit:e}};g._getConstraints=function(a){if(.5<a)return{min:.5,max:1};if(.3<a)return{min:.3,max:.5};if(.2<a)return{min:.2,max:.3};if(.15<a)return{min:.15,max:.2};if(.1<=a)return{min:.15,max:.1}};t._createClass(k,[{key:"state",get:function(){return this.get("view.ready")&&"2d"===this.get("view.type")?"ready":"disabled"}}]);return k}(y);n.__decorate([r.property()],l.prototype,"scaleComputedFrom",void 0);n.__decorate([r.property({readOnly:!0})],
l.prototype,"state",null);n.__decorate([r.property()],l.prototype,"view",void 0);return l=n.__decorate([A.subclass("esri.widgets.Scalebar.ScaleBarViewModel")],l)});