// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../chunks/_rollupPluginBabelHelpers ../../chunks/tslib.es6 ../../geometry ../../core/Handles ../../core/maybe ../../core/accessorSupport/decorators/property ../../core/has ../../core/accessorSupport/ensureType ../../core/Logger ../../core/jsonMap ../../core/accessorSupport/decorators/subclass ../3d/interactive/editingTools/draw/DrawTool ./DrawAction ./input/DrawEvents ./support/surfaceCoordinateSystems ../input/InputManager ../interactive/keybindings ../interactive/editGeometry/EditGeometry ../interactive/editGeometry/EditGeometryHelper ../support/screenUtils ../../geometry/Point".split(" "),
function(h,r,m,C,t,b,u,D,E,F,G,v,w,x,f,y,e,k,n,z,g,A){h.SegmentDrawAction=function(p){function l(a){a=p.call(this,a)||this;a._isDragging=!1;a._panEnabled=!1;a._viewHandles=new t;a._activePointerId=null;a._addVertexOnPointerUp=!1;a.viewAlignedCoordinateSystem=null;a.mode="freehand";return a}r._inheritsLoose(l,p);var c=l.prototype;c.initialize=function(){"2d"===this.view.type?this._addViewHandles():this._addDrawTool(this.view)};c.destroy=function(){"2d"===this.view.type?(this._removeViewHandles(),this._viewHandles.destroy()):
this._removeDrawTool();this.emit("destroy")};c.complete=function(){"2d"===this.view.type?this._completeDrawing():this._drawTool.completeCreateOperation()};c.getGeometryZValue=function(){return 0<this.vertices.length&&2<this.vertices[0].length?this.vertices[0][2]:this._get("defaultZ")};c._addViewHandles=function(){this._removeViewHandles();"click"===this.mode?this._viewHandles.add(this._getClickModeViewHandles()):this._viewHandles.add(this._getDragModeViewHandles())};c._getDragModeViewHandles=function(){return[this.view.on("immediate-click",
a=>{a.stopPropagation();if(a.mapPoint&&!this._panEnabled){const d=this.getCoordsFromScreenPoint(g.createScreenPointFromEvent(a));b.isSome(d)&&(this._vertexAddHandler(a),this._drawCompleteHandler(a))}},e.ViewEventPriorities.TOOL),this.view.on("pointer-down",a=>{this._shouldHandlePointerEvent(a)&&(this._snappingTask=b.abortMaybe(this._snappingTask),this._panEnabled||(this._resetGeometry(),this._addVertexOnPointerUp=!0,this._cursorScreenPoint=g.createScreenPointFromEvent(a),this._activePointerId=a.pointerId,
this._vertexAddHandler(a),this._isDragging=!1,"touch"===a.pointerType&&this._updateCursor(a.native)))},e.ViewEventPriorities.TOOL),this.view.on("pointer-move",a=>{this._snappingTask=b.abortMaybe(this._snappingTask);b.isNone(this._activePointerId)&&"touch"!==a.pointerType&&(this._cursorScreenPoint=g.createScreenPointFromEvent(a),this._updateCursor(a.native))},e.ViewEventPriorities.TOOL),this.view.on("pointer-drag",a=>{this._shouldHandlePointerEvent(a)&&(this._snappingTask=b.abortMaybe(this._snappingTask),
this._isDragging=!0,this._cursorScreenPoint=g.createScreenPointFromEvent(a),this._updateCursor(a.native))},e.ViewEventPriorities.TOOL),this.view.on("pointer-up",a=>{this._shouldHandlePointerEvent(a)&&this._addVertexOnPointerUp&&(this._snappingTask=b.abortMaybe(this._snappingTask),this._activePointerId=null,this._isDragging&&this._vertexAddHandler(a),2===this._committedVertices.length&&this._drawCompleteHandler(a),this._isDragging=!1)},e.ViewEventPriorities.TOOL),this.view.on("key-down",a=>{a.key===
k.SKETCH_KEYS.complete&&this._cursorScreenPoint?(this._snappingTask=b.abortMaybe(this._snappingTask),this._vertexAddHandler(a),this._drawCompleteHandler(a)):a.key===k.SKETCH_KEYS.pan&&(this._panEnabled=!0)},e.ViewEventPriorities.TOOL),this.view.on("key-up",a=>{a.key===k.SKETCH_KEYS.pan&&(this._panEnabled=!1)},e.ViewEventPriorities.TOOL),this.view.on("drag",a=>{b.isSome(this._activePointerId)&&a.stopPropagation()},e.ViewEventPriorities.TOOL),this.view.on("drag",["Shift"],a=>{a.stopPropagation()},e.ViewEventPriorities.TOOL)]};
c._getClickModeViewHandles=function(){return[this.view.on("pointer-down",a=>{this._snappingTask=b.abortMaybe(this._snappingTask);this._cursorScreenPoint=g.createScreenPointFromEvent(a);this._activePointerId=a.pointerId;this._isDragging=!1;"touch"===a.pointerType&&this._updateCursor(a.native)},e.ViewEventPriorities.TOOL),this.view.on("pointer-move",a=>{this._snappingTask=b.abortMaybe(this._snappingTask);this._cursorScreenPoint=g.createScreenPointFromEvent(a);b.isNone(this._activePointerId)&&"touch"!==
a.pointerType&&this._updateCursor(a.native)},e.ViewEventPriorities.TOOL),this.view.on("pointer-drag",a=>{this._shouldHandlePointerEvent(a)&&(this._snappingTask=b.abortMaybe(this._snappingTask),this._isDragging=!0)},e.ViewEventPriorities.TOOL),this.view.on("pointer-up",a=>{this._shouldHandlePointerEvent(a)&&(this._snappingTask=b.abortMaybe(this._snappingTask),this._activePointerId=null,a.stopPropagation(),this._isDragging||this._vertexAddHandler(a),2!==this.vertices.length||this._isDragging||this._drawCompleteHandler(a),
this._isDragging=!1)},e.ViewEventPriorities.TOOL),this.view.on("key-down",a=>{a.key===k.SKETCH_KEYS.vertexAdd&&this._cursorScreenPoint&&(this._vertexAddHandler(a),2===this.vertices.length&&this._drawCompleteHandler(a));a.key===k.SKETCH_KEYS.complete&&this._cursorScreenPoint&&2===this.vertices.length&&(this._vertexAddHandler(a),this._drawCompleteHandler(a))},e.ViewEventPriorities.TOOL)]};c._removeViewHandles=function(){this._viewHandles.removeAll()};c._addDrawTool=function(a){this._drawTool=new w.DrawTool({view:a,
elevationInfo:this.elevationInfo,hasZ:this.hasZ,geometryType:"segment",mode:this.mode});this.view.toolViewManager.tools.push(this._drawTool);this.view.activeTool=this._drawTool;this._drawTool.on("vertex-add",d=>{1===d.vertices.length&&this.emit("vertex-add",new f.VertexAddEvent(this.view,null,d.vertices[0].vertexIndex,this._drawTool.getVertexCoords()))});this._drawTool.on("cursor-update",d=>{1===d.vertices.length&&this.emit("cursor-update",new f.CursorUpdateEvent(this.view,null,d.vertices[0].vertexIndex,
this._drawTool.getVertexCoords()))});this._drawTool.on("complete",d=>{this.emit("draw-complete",new f.DrawCompleteEvent(null,this._drawTool.getVertexCoords()));this._removeDrawTool()})};c._removeDrawTool=function(){b.isSome(this._drawTool)&&(this.view.tools.remove(this._drawTool),this._drawTool.destroy(),this._drawTool=null)};c._addVertex=function(a,d){a=this._coordinateHelper.fromArray(a);this._isDuplicateOfLastVertex(a)||(this._lastVertexUnsnapped=this._stagedVertexUnsnapped,this._popCursorVertex(),
this._editGeometry.appendVertex(a),1===this._committedVertices.length&&(this.viewAlignedCoordinateSystem=y.createViewAlignedCoordinateSystem(this.view,this._committedVertices[0])),d=new f.VertexAddEvent(this.view,d,this._committedVertices.length-1,this.vertices),this.emit("vertex-add",d))};c._updateCursor=function(a){this._popCursorVertex();if(this._cursorScreenPoint){var d=this.getCoordsAndPointFromScreenPoint(this._cursorScreenPoint);if(b.isSome(d)){this._pushCursorVertex(d.vertex);const q=()=>
new f.CursorUpdateEvent(this.view,a,this._activeComponent.vertices.length,this.vertices,b.isSome(this._stagedVertex)?new A(this._stagedVertex):null);this.emit("cursor-update",q());b.isSome(this._snappingTask)&&this._snappingTask.promise.then(B=>{B.valid&&this.emit("cursor-update",q())},()=>{})}}};c._completeDrawing=function(a){this._activePointerId=null;this._popCursorVertex();this._cursorScreenPoint=null;this._isDragging=!1;this._snappingTask=b.abortMaybe(this._snappingTask);b.isSome(this._snappingManager)&&
this._snappingManager.doneSnapping();1>this.vertices.length||(a=new f.DrawCompleteEvent(a,this.vertices),this.emit("draw-complete",a),a.defaultPrevented||this._removeViewHandles())};c._resetGeometry=function(){this._editGeometry.destroy();this._editGeometry=new z.EditGeometryHelper(new n.EditGeometry(this._coordinateHelper),"polygon");this._activeComponent=new n.Component(this._editGeometry.editGeometry);this._editGeometry.editGeometry.components.push(this._activeComponent)};c._shouldHandlePointerEvent=
function(a){return("mouse"!==a.pointerType||0===a.button)&&(b.isNone(this._activePointerId)||this._activePointerId===a.pointerId)};return l}(x);m.__decorate([u.property({type:["freehand","click"]})],h.SegmentDrawAction.prototype,"mode",void 0);h.SegmentDrawAction=m.__decorate([v.subclass("esri/views/2d/engine/markup/SegmentDrawAction")],h.SegmentDrawAction);Object.defineProperty(h,"__esModule",{value:!0})});