// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../Color ../../../core/JSONSupport ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/decorators/subclass".split(" "),function(h,k,c,l,a,d,m){let e=function(f){function g(){var b=f.apply(this,arguments)||this;b.enabled=!0;return b}k._inheritsLoose(g,f);return g}(a.JSONSupport);c.__decorate([d.property({type:Boolean})],e.prototype,"enabled",void 0);e=c.__decorate([m.subclass("esri.views.interactive.snapping.Settings.DefaultSnappingAlgorithm")],
e);a=function(f){function g(b){b=f.call(this,b)||this;b.lineSnapper=new e;b.parallelLineSnapper=new e;b.rightAngleSnapper=new e;b.rightAngleTriangleSnapper=new e;b.shortLineThreshold=15;b.distance=5;b.pointThreshold=1E-6;b.intersectionParallelLineThreshold=1E-6;b.parallelLineThreshold=1E-6;b.touchSensitivityMultiplier=1.5;b.pointOnLineThreshold=1E-6;b.orange=new l([255,127,0]);b.lineHintWidthReference=3;b.lineHintWidthTarget=3;b.lineHintFadedExtensions=.3;b.parallelLineHintWidth=2;b.parallelLineHintLength=
24;b.parallelLineHintOffset=1.5;b.rightAngleHintSize=24;b.rightAngleHintOutlineSize=1.5;return b}k._inheritsLoose(g,f);return g}(a.JSONSupport);c.__decorate([d.property({type:e,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"lineSnapper",void 0);c.__decorate([d.property({type:e,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"parallelLineSnapper",void 0);c.__decorate([d.property({type:e,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"rightAngleSnapper",
void 0);c.__decorate([d.property({type:e,constructOnly:!0,nonNullable:!0,json:{write:!0}})],a.prototype,"rightAngleTriangleSnapper",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:-1,max:50,step:1},json:{write:!0}})],a.prototype,"shortLineThreshold",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:-1,max:50,step:1},json:{write:!0}})],a.prototype,"distance",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:1E-5},json:{write:!0}})],
a.prototype,"pointThreshold",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:1E-5},json:{write:!0}})],a.prototype,"intersectionParallelLineThreshold",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:1E-5},json:{write:!0}})],a.prototype,"parallelLineThreshold",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:10},json:{write:!0}})],a.prototype,"touchSensitivityMultiplier",void 0);c.__decorate([d.property({type:Number,
nonNullable:!0,range:{min:0,max:1E-5},json:{write:!0}})],a.prototype,"pointOnLineThreshold",void 0);c.__decorate([d.property({type:l,nonNullable:!0})],a.prototype,"orange",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:10},json:{write:!0}})],a.prototype,"lineHintWidthReference",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:10},json:{write:!0}})],a.prototype,"lineHintWidthTarget",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,
range:{min:0,max:1},json:{write:!0}})],a.prototype,"lineHintFadedExtensions",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:10},json:{write:!0}})],a.prototype,"parallelLineHintWidth",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:50},json:{write:!0}})],a.prototype,"parallelLineHintLength",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:5},json:{write:!0}})],a.prototype,"parallelLineHintOffset",void 0);c.__decorate([d.property({type:Number,
nonNullable:!0,range:{min:0,max:46},json:{write:!0}})],a.prototype,"rightAngleHintSize",void 0);c.__decorate([d.property({type:Number,nonNullable:!0,range:{min:0,max:6},json:{write:!0}})],a.prototype,"rightAngleHintOutlineSize",void 0);a=c.__decorate([m.subclass("esri.views.interactive.snapping.Settings.Defaults")],a);c=new a;h.defaults=c;Object.defineProperty(h,"__esModule",{value:!0})});