// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("../chunks/_rollupPluginBabelHelpers ../chunks/tslib.es6 ../intl ../core/Collection ../core/deprecate ../core/events ../core/Logger ../core/maybe ../core/accessorSupport/decorators/aliasOf ../core/has ../core/accessorSupport/decorators/cast ../core/jsonMap ../core/accessorSupport/decorators/property ../core/accessorSupport/decorators/subclass ../chunks/ResizeObserver ./Widget ./Slider/SliderViewModel ./support/widgetUtils ./support/decorators/messageBundle ./support/jsxFactory ../intl/substitute".split(" "),
function(y,m,l,D,K,G,Q,u,C,X,R,Y,q,S,T,U,V,Z,W,v,L){const w={showInput:"Enter",hideInput1:"Enter",hideInput2:"Escape",hideInput3:"Tab",moveAnchorUp:"ArrowUp",moveAnchorDown:"ArrowDown",moveAnchorLeft:"ArrowLeft",moveAnchorRight:"ArrowRight",moveAnchorToMax:"End",moveAnchorToMin:"Home"},M=Q.getLogger("esri.widgets.Slider"),N={labels:!1,rangeLabels:!1};l=function(O){function H(a,b){var c=O.call(this,a,b)||this;c._activeLabelInputIndex=null;c._anchorElements=[];c._baseNode=null;c._dragged=!1;c._dragStartInfo=
null;c._focusedAnchorIndex=null;c._isMinInputActive=!1;c._isMaxInputActive=!1;c._lastMovedHandleIndex=null;c._observer=null;c._positionPrecision=5;c._segmentDragStartInfo=null;c._trackHeight=null;c._trackWidth=null;c._zIndices=null;c._zIndexOffset=3;c.disabled=!1;c.extraNodes=[];c.draggableSegmentsEnabled=!0;c.inputCreatedFunction=null;c.inputFormatFunction=null;c.inputParseFunction=null;c.label=void 0;c.labelElements=new D;c.labelInputsEnabled=!1;c.labelFormatFunction=null;c.labels=null;c.max=null;
c.maxLabelElement=null;c.messages=null;c.min=null;c.minLabelElement=null;c.precision=4;c.rangeLabelInputsEnabled=!1;c.segmentElements=new D;c.snapOnClickEnabled=!0;c.steps=null;c.syncedSegmentsEnabled=!1;c.thumbsConstrained=!0;c.thumbCreatedFunction=null;c.thumbElements=new D;c.tickElements=new D;c.trackElement=null;c.values=null;c.viewModel=new V;c.visibleElements={...N};c._observer=new T.ResizeObserver(()=>c.scheduleRender());c._onAnchorPointerDown=c._onAnchorPointerDown.bind(y._assertThisInitialized(c));
c._onAnchorPointerMove=c._onAnchorPointerMove.bind(y._assertThisInitialized(c));c._onAnchorPointerUp=c._onAnchorPointerUp.bind(y._assertThisInitialized(c));c._onLabelPointerDown=c._onLabelPointerDown.bind(y._assertThisInitialized(c));c._onLabelPointerUp=c._onLabelPointerUp.bind(y._assertThisInitialized(c));c._onSegmentPointerDown=c._onSegmentPointerDown.bind(y._assertThisInitialized(c));c._onSegmentPointerMove=c._onSegmentPointerMove.bind(y._assertThisInitialized(c));c._onSegmentPointerUp=c._onSegmentPointerUp.bind(y._assertThisInitialized(c));
c._onTrackPointerDown=c._onTrackPointerDown.bind(y._assertThisInitialized(c));c._onTrackPointerMove=c._onTrackPointerMove.bind(y._assertThisInitialized(c));c._onTrackPointerUp=c._onTrackPointerUp.bind(y._assertThisInitialized(c));return c}y._inheritsLoose(H,O);var d=H.prototype;d.destroy=function(){document.removeEventListener("pointerup",this._onLabelPointerUp);document.removeEventListener("pointermove",this._onLabelPointerMove);document.removeEventListener("pointerup",this._onAnchorPointerUp);document.removeEventListener("pointermove",
this._onAnchorPointerMove);this.labelElements.removeAll();this.labelElements.destroy();this.segmentElements.removeAll();this.segmentElements.destroy();this.thumbElements.removeAll();this.thumbElements.destroy();this.tickElements.removeAll();this.tickElements.destroy()};d.castVisibleElements=function(a){return{...N,...a}};d.render=function(){const {label:a}=this,b=this.classes("esri-slider","esri-widget",this._isHorizontalLayout()?"esri-slider--horizontal":"esri-slider--vertical",this._isReversedLayout()?
"esri-slider--reversed":null,this._isDisabled()?"esri-disabled":null);this._storeTrackDimensions();return v.tsx("div",{afterCreate:this._afterBaseNodeCreate,bind:this,"aria-label":a,class:b,"touch-action":"none"},this.renderContent())};d.toNextStep=function(a){this._toStep(a,1)};d.toPreviousStep=function(a){this._toStep(a,-1)};d.renderContent=function(){const {max:a,min:b}=this;if(u.isSome(b)&&u.isSome(a)&&!(b>=a))return[this.renderMin(),this.renderSliderContainer(),this.renderMax()]};d.renderSliderContainer=
function(){return v.tsx("div",{key:"slider-container",bind:this,class:"esri-slider__content"},this.renderTrackElement(),this.renderTicksContainer(),this.renderExtraContentElements())};d.renderTrackElement=function(){return v.tsx("div",{afterCreate:this._afterTrackCreate,afterRemoved:this._afterTrackRemoved,bind:this,class:"esri-slider__track","data-node-ref":"trackElement","touch-action":"none"},this.renderSegmentElements(),this.renderAnchorElements())};d.renderSegmentElements=function(){if(this.trackElement&&
this.values&&this.values.length){var a=this.values.length+1,b=[];for(let c=0;c<a;c++)b.push(this.renderSegmentElement(c));return b}};d.renderSegmentElement=function(a){const {_trackHeight:b,_trackWidth:c,draggableSegmentsEnabled:f,id:e,state:g,values:h}=this;var k=this._isHorizontalLayout(),n=k?c:b;const r=a===h.length?null:a,p=0===a?null:a-1;var x=u.isSome(r);const B=u.isSome(p);let t,z;var A=[...h].sort((I,J)=>I-J);this._isReversedLayout()?(t=B?this._positionFromValue(A[p]):k?n:0,z=x?this._positionFromValue(A[r]):
k?0:n):(t=x?this._positionFromValue(A[r]):k?n:0,z=B?this._positionFromValue(A[p]):k?0:n);A=this._applyPrecisionToPosition(100*z/n);n=(t-z)/n;k=k?`transform: translate(${A}%, 0px) scale(${n}, 1);`:`transform: translate(0px, ${A}%) scale(1, ${n});`;x=this.classes("esri-slider__segment","esri-slider__segment-"+a,f&&x&&B&&"disabled"!==g?"esri-slider__segment--interactive":null);return v.tsx("div",{afterCreate:this._afterSegmentCreate,afterRemoved:this._afterSegmentRemoved,bind:this,class:x,"data-max-thumb-index":r,
"data-min-thumb-index":p,"data-segment-index":a,key:`${e}-segment-${a}`,style:k,"touch-action":"none"})};d.renderAnchorElements=function(){const {trackElement:a,values:b}=this;if(b&&b.length)return this._zIndices=b.map((c,f)=>{c=this._positionFromValue(c);c=this._positionToPercent(c);c=this._isHorizontalLayout()?50<c:50>c;return this._zIndexOffset+(b.length+(c?-1:1)*f)}),a&&b&&b.length?b.map((c,f)=>this.renderAnchorElement(c,f)):null};d.renderAnchorElement=function(a,b){var c=this._positionFromValue(a);
c=this._valueFromPosition(c);if(u.isSome(c)&&!isNaN(c)){var {_dragStartInfo:f,_lastMovedHandleIndex:e,id:g,layout:h,values:k,visibleElements:{labels:n}}=this,r=f&&f.index===b,p=e===b;c=this.classes("esri-slider__anchor","esri-slider__anchor-"+b,r?"esri-slider__anchor--moving":null,p?"esri-slider__anchor--moved":null);var x=this.labels.values[b];r=this._getStyleForAnchor(a,b,r||p);var {min:B,max:t}=this.viewModel.getBoundsForValueAtIndex(b);({messages:p}=this);x=2===k.length?0===b?L.substitute(p.rangeMinimum,
{value:a}):L.substitute(p.rangeMaximum,{value:a}):x;return v.tsx("div",{afterCreate:this._afterAnchorCreate,afterUpdate:this._afterAnchorUpdate,afterRemoved:this._afterAnchorRemoved,"aria-controls":1===k.length?null:0===b?`${g}-handle-${b+1}`:b===k.length-1?`${g}-handle-${b-1}`:`${g}-handle-${b-1} ${g}-handle-${b+1}`,"aria-label":p.sliderValue,"aria-labelledby":n?`${g}-label-${b}`:null,"aria-orientation":h,"aria-valuemax":t.toString(),"aria-valuemin":B.toString(),"aria-valuenow":a.toString(),"aria-valuetext":x,
bind:this,class:c,"data-thumb-index":b,"data-value":a,id:`${g}-handle-${b}`,key:`${g}-handle-${b}`,onkeydown:this._onAnchorKeyDown,"touch-action":"none",role:"slider",style:r,tabIndex:0},v.tsx("span",{afterCreate:this._afterThumbCreate,afterRemoved:this._afterThumbRemoved,bind:this,class:"esri-slider__thumb","data-thumb-index":b,"touch-action":"none"}),this.renderThumbLabel(b))}};d.renderThumbLabel=function(a){const {id:b,labels:c,labelInputsEnabled:f,state:e}=this,g=this.visibleElements.labels,h=
c.values[a],k=this.classes("esri-slider__label",g?null:"esri-hidden",f&&"disabled"!==e?"esri-slider__label--interactive":null);return v.tsx("span",{afterCreate:this._afterLabelCreate,afterRemoved:this._afterLabelRemoved,"aria-hidden":(!g).toString(),bind:this,class:k,"data-thumb-index":a,key:`${b}-label-${a}`,id:`${b}-label-${a}`,role:f?"button":null,"touch-action":"none"},this._activeLabelInputIndex===a?this.renderValueInput(a):h)};d.renderValueInput=function(a){return v.tsx("input",{afterCreate:this._afterInputCreate,
"aria-label":this.messages.sliderValue,bind:this,class:"esri-slider__label-input","data-input-type":"thumb","data-input-index":a,required:!0,tabIndex:0,type:"text",value:this._formatInputValue(this.values[a],"value",a),onblur:this._onLabelInputBlur,onkeydown:this._onInputKeyDown})};d.renderMax=function(){const {_isMaxInputActive:a,labels:b,rangeLabelInputsEnabled:c,state:f}=this,e=this.visibleElements.rangeLabels,g=this.classes("esri-slider__max",e?null:"esri-hidden",c&&"disabled"!==f?"esri-slider__max--interactive":
null);return v.tsx("div",{"aria-hidden":(!e).toString(),afterCreate:this._afterMaxLabelCreate,bind:this,class:g,onclick:this._onMaxLabelClick,onkeydown:this._onMaxLabelKeyDown,role:c?"button":null,tabIndex:c?0:null},a?this.renderMaxInput():b.max)};d.renderMin=function(){const {_isMinInputActive:a,labels:b,rangeLabelInputsEnabled:c,state:f}=this,e=this.visibleElements.rangeLabels,g=this.classes("esri-slider__min",e?null:"esri-hidden",c&&"disabled"!==f?"esri-slider__min--interactive":null);return v.tsx("div",
{"aria-hidden":(!e).toString(),afterCreate:this._afterMinLabelCreate,bind:this,class:g,onclick:this._onMinLabelClick,onkeydown:this._onMinLabelKeyDown,role:c?"button":null,tabIndex:c?0:null},a?this.renderMinInput():b.min)};d.renderMaxInput=function(){return v.tsx("input",{afterCreate:this._afterInputCreate,"aria-label":this.messages.maximumValue,bind:this,class:"esri-slider__range-input","data-input-type":"max",required:!0,tabIndex:0,type:"text",value:this._formatInputValue(this.max,"max"),onblur:this._onMaxInputBlur,
onkeydown:this._onInputKeyDown})};d.renderMinInput=function(){return v.tsx("input",{afterCreate:this._afterInputCreate,"aria-label":this.messages.minimumValue,bind:this,class:"esri-slider__range-input","data-input-type":"min",required:!0,tabIndex:0,type:"text",value:this._formatInputValue(this.min,"min"),onblur:this._onMinInputBlur,onkeydown:this._onInputKeyDown})};d.renderExtraContentElements=function(){return v.tsx("div",{bind:this,class:"esri-slider__extra-content"},this.extraNodes)};d.renderTicksContainer=
function(){if(this.tickConfigs&&this.trackElement&&(0!==this._trackHeight||0!==this._trackWidth))return this.tickConfigs.map((a,b)=>v.tsx("div",{key:"ticks-container",class:this.classes("esri-slider__ticks")},this.renderTicks(a,b)))};d.renderTicks=function(a,b){const {mode:c,values:f}=a;this.tickElements.getItemAt(b)||this.tickElements.add(new D,b);if("position"===c){var e=Array.isArray(f)?f:[f];return this._calculateTickPositions(e).map((g,h)=>this.renderTickGroup(a,h,b,g))}if("percent"===c&&Array.isArray(f)){const {max:g,
min:h}=this,k=g-h;e=f.map(n=>this._applyPrecisionToPosition(n/100*k+h));return this._calculateTickPositions(e).map((n,r)=>this.renderTickGroup(a,r,b,n))}e=Array.isArray(f)&&f.length?f[0]:isNaN(f)?null:f;e=this._getTickCounts(e,a);return this._calculateEquidistantTickPositions(e).map((g,h)=>this.renderTickGroup(a,h,b,g))};d.renderTickGroup=function(a,b,c,f){const e="position"===a.mode?Array.isArray(a.values)?a.values[b]:a.values:this._valueFromPosition(f);if(u.isSome(e)&&!isNaN(e))return v.tsx("div",
{afterCreate:this._afterTickGroupCreate,afterRemoved:this._afterTickGroupRemoved,bind:this,"data-config":a,"data-position":f,"data-tick-config-index":c,"data-tick-group-index":b,"data-value":e,onclick:this._onTickGroupClick,key:`tick-group-${b}`},this.renderTickLine(a,b,c,e),a.labelsVisible?this.renderTickLabel(a,b,c,e):null)};d.renderTickLine=function(a,b,c,f){return v.tsx("div",{afterCreate:this._afterTickLineCreate,"aria-valuenow":f.toString(),bind:this,class:"esri-slider__tick","data-config":a,
"data-tick-config-index":c,"data-tick-group-index":b,"data-value":f,key:`tick-label-${b}`,style:this._getPositionStyleForElement(f)})};d.renderTickLabel=function(a,b,c,f){const e=a.labelFormatFunction?a.labelFormatFunction(f,"tick",b):this.viewModel.getLabelForValue(f,"tick",b);return v.tsx("div",{afterCreate:this._afterTickLabelCreate,"aria-label":e,"aria-valuenow":f.toString(),"aria-valuetext":e,bind:this,class:"esri-slider__tick-label","data-config":a,"data-tick-config-index":c,"data-tick-group-index":b,
"data-value":f,key:`tick-label-${b}`,style:`transform: translate(-50%); ${this._getPositionStyleForElement(f)}`},e)};d._afterBaseNodeCreate=function(a){this._baseNode&&this._observer.unobserve(this._baseNode);this._baseNode=a;this._observer.observe(this._baseNode)};d._afterTrackCreate=function(a){this._set("trackElement",a);a.addEventListener("pointerdown",this._onTrackPointerDown);this.scheduleRender()};d._afterTrackRemoved=function(a){a.removeEventListener("pointerdown",this._onTrackPointerDown);
document.removeEventListener("pointermove",this._onTrackPointerMove);document.removeEventListener("pointerup",this._onTrackPointerUp)};d._afterSegmentCreate=function(a){this.segmentElements.add(a);a.addEventListener("pointerdown",this._onSegmentPointerDown)};d._afterSegmentRemoved=function(a){this.segmentElements.remove(a);a.removeEventListener("pointerdown",this._onSegmentPointerDown)};d._afterAnchorCreate=function(a){this._anchorElements.push(a);a.addEventListener("pointerdown",this._onAnchorPointerDown);
if(this.thumbCreatedFunction){const b=a["data-thumb-index"];a=a["data-value"];const c=this.thumbElements.getItemAt(b)||null,f=this.labelElements.getItemAt(b)||null;this.thumbCreatedFunction(b,a,c,f)}};d._afterAnchorUpdate=function(a){u.isSome(this._focusedAnchorIndex)&&a["data-thumb-index"]===this._focusedAnchorIndex&&(a.focus(),this._focusedAnchorIndex=null)};d._afterAnchorRemoved=function(a){const b=this._anchorElements.indexOf(a,0);-1<b&&this._anchorElements.splice(b,1);a.removeEventListener("pointerdown",
this._onAnchorPointerDown)};d._afterThumbCreate=function(a){this.thumbElements.add(a)};d._afterThumbRemoved=function(a){this.thumbElements.remove(a)};d._afterLabelCreate=function(a){this.labelElements.add(a);a.addEventListener("pointerdown",this._onLabelPointerDown);a.addEventListener("pointerup",this._onLabelPointerUp)};d._afterLabelRemoved=function(a){this.labelElements.remove(a);a.removeEventListener("pointerdown",this._onLabelPointerDown);a.removeEventListener("pointerup",this._onLabelPointerUp)};
d._afterInputCreate=function(a){a.focus();a.select();if(this.inputCreatedFunction){const b=a.getAttribute("data-input-type");this.inputCreatedFunction(a,b,"thumb"===b?a["data-input-index"]:null)}};d._afterTickLineCreate=function(a){const b=a["data-tick-group-index"],c=this.tickElements.getItemAt(a["data-tick-config-index"]);c.getItemAt(b)?c.getItemAt(b).tickElement=a:c.add({groupElement:null,tickElement:a,labelElement:null},b)};d._afterTickLabelCreate=function(a){const b=a["data-tick-group-index"],
c=this.tickElements.getItemAt(a["data-tick-config-index"]);c.getItemAt(b)?c.getItemAt(b).labelElement=a:c.add({groupElement:null,labelElement:a,tickElement:null},b)};d._afterTickGroupRemoved=function(a){const b=this.tickElements.items[a["data-tick-config-index"]],c=null==b?void 0:b.find(f=>f.groupElement===a);c&&b.remove(c)};d._afterTickGroupCreate=function(a){const b=a["data-config"];if(b&&b.tickCreatedFunction){var c,f,e=a["data-tick-config-index"];const g=a["data-tick-group-index"],h=a["data-value"];
if(e=null==(c=this.tickElements)?void 0:null==(f=c.getItemAt(e))?void 0:f.getItemAt(g))e.groupElement=a,b.tickCreatedFunction(h,e.tickElement||null,e.labelElement||null)}};d._afterMaxLabelCreate=function(a){this._set("maxLabelElement",a)};d._afterMinLabelCreate=function(a){this._set("minLabelElement",a)};d._onAnchorKeyDown=function(a){if(!this._isDisabled()&&"editing"!==this.state){var {target:b}=a,c=G.eventKey(a),{_anchorElements:f,values:e}=this;b=b["data-thumb-index"];var g=f[b],h=e[b],k=this._isHorizontalLayout(),
n=[w.moveAnchorUp,w.moveAnchorDown,w.moveAnchorLeft,w.moveAnchorRight];if(c===w.showInput&&this.labelInputsEnabled)this._activeLabelInputIndex=b,this.notifyChange("state");else if(-1<n.indexOf(c))a.preventDefault(),{steps:a}=this,c=c===w.moveAnchorUp||c===w.moveAnchorRight?1:-1,u.isSome(a)?this._toStep(b,this._isReversedLayout()?-1*c:c):({precision:a}=this,g=this._getPositionOfElement(g),k=this._valueFromPosition(g),c=this._isHorizontalLayout()?c:-1*c,g=0===a?this._positionFromValue(k+c):1===a?this._positionFromValue(k+
.1*c):g+c,this._toPosition(b,g)),g=this.values[b],h!==g&&this._emitThumbChangeEvent({index:b,oldValue:h,value:g});else if(c===w.moveAnchorToMax||c===w.moveAnchorToMin){a.preventDefault();const {min:r,max:p}=this._getAnchorBoundsInPixels(b);this._toPosition(b,k?c===w.moveAnchorToMax?p:r:c===w.moveAnchorToMin?p:r);g=this.values[b];h!==g&&this._emitThumbChangeEvent({index:b,oldValue:h,value:g})}}};d._onAnchorPointerDown=function(a){if(!this._isDisabled()){var {target:b,clientX:c,clientY:f}=a,e=b["data-thumb-index"];
void 0!==e&&(a.preventDefault(),this._anchorElements[e]&&this._anchorElements[e].focus(),this._storeTrackDimensions(),this._dragStartInfo={clientX:c,clientY:f,index:e,position:this._getPositionOfElement(this._anchorElements[e])},this.notifyChange("state"),document.addEventListener("pointerup",this._onAnchorPointerUp),document.addEventListener("pointermove",this._onAnchorPointerMove))}};d._onAnchorPointerMove=function(a){if("editing"!==this.state&&this._dragStartInfo){a.preventDefault();var {values:b,
_anchorElements:c,_dragged:f,_dragStartInfo:e,_dragStartInfo:{index:g,position:h}}=this,{clientX:k,clientY:n}=a;a=f?"drag":"start";var r=this._getPositionOfElement(c[g]),p=this._applyPrecisionToPosition(this._isHorizontalLayout()?h+k-e.clientX:h+n-e.clientY);r!==p&&(r=b[g],this._dragged=!0,this._toPosition(g,p),p=this.values[g],f?r!==p&&this._emitThumbDragEvent({index:g,state:a,value:p}):this._emitThumbDragEvent({index:g,state:a,value:r}))}};d._onAnchorPointerUp=function(a){document.removeEventListener("pointerup",
this._onAnchorPointerUp);document.removeEventListener("pointermove",this._onAnchorPointerMove);if(this._dragStartInfo){a.preventDefault();({index:a}=this._dragStartInfo);var b=this._dragged,c=this.values[a];this._dragged=!1;this._dragStartInfo=null;this._lastMovedHandleIndex=a;this.notifyChange("state");b?this._emitThumbDragEvent({index:a,state:"stop",value:c}):(this.scheduleRender(),"editing"!==this.state&&this._emitThumbClickEvent({index:a,value:c}))}};d._onTrackPointerDown=function(a){const {_dragStartInfo:b,
snapOnClickEnabled:c,state:f,values:e}=this;if(!this._isDisabled()&&"editing"!==f&&!b&&(document.addEventListener("pointermove",this._onTrackPointerMove),document.addEventListener("pointerup",this._onTrackPointerUp),c&&e.length)){var {steps:g}=this,{clientX:h,clientY:k}=a,n=this._getCursorPositionFromEvent(a);a=this._valueFromPosition(n);var r=this._getIndexOfNearestValue(a),p=e[r];a=e.some((B,t)=>B===p&&t!==r)&&a>p?this.values.lastIndexOf(p):r;if(u.isSome(a)){var x=e[a];g=u.isSome(g)?this._calculateNearestStepPosition(n):
n;this._toPosition(a,g);this._dragged=!0;this._dragStartInfo={clientX:h,clientY:k,index:a,position:g};this._focusedAnchorIndex=a;this.notifyChange("state");this._emitThumbDragEvent({index:a,state:"start",value:x});g=this.values[a];x!==g&&this._emitThumbDragEvent({index:a,state:"drag",value:g});document.addEventListener("pointerup",this._onAnchorPointerUp);document.addEventListener("pointermove",this._onAnchorPointerMove)}}};d._onTrackPointerMove=function(a){a.preventDefault();this._dragged=!0};d._onTrackPointerUp=
function(a){a.preventDefault();document.removeEventListener("pointermove",this._onTrackPointerMove);document.removeEventListener("pointerup",this._onTrackPointerUp);this.snapOnClickEnabled||(this._dragged=!1);this._dragged||(a=this._getCursorPositionFromEvent(a),a=this._valueFromPosition(a),this._emitTrackClickEvent({value:a}))};d._onSegmentPointerDown=function(a){a.preventDefault();var b=a.target;const c=b["data-segment-index"],f=b["data-min-thumb-index"];b=b["data-max-thumb-index"];if(!this._isDisabled()&&
u.isSome(f)&&u.isSome(b)){a.stopPropagation();this._storeTrackDimensions();document.addEventListener("pointerup",this._onSegmentPointerUp);var e=this._getAnchorDetails(f),g=this._getAnchorDetails(b);if(this.syncedSegmentsEnabled)this.segmentElements.forEach(n=>n.classList.add("esri-slider__segment--active")),this._anchorElements.forEach(n=>n.classList.add("esri-slider__anchor--active"));else{var h,k;this.segmentElements.getItemAt(c).classList.add("esri-slider__segment--active");null==(h=this._anchorElements[e.index])?
void 0:h.classList.add("esri-slider__anchor--active");null==(k=this._anchorElements[g.index])?void 0:k.classList.add("esri-slider__anchor--active")}this._segmentDragStartInfo={cursorPosition:this._getCursorPositionFromEvent(a),index:c,details:this._normalizeSegmentDetails({min:e,max:g})};this.draggableSegmentsEnabled&&(document.addEventListener("pointermove",this._onSegmentPointerMove),this.notifyChange("state"),this._emitSegmentDragEvent({index:c,state:"start",thumbIndices:[f,b]}))}};d._onSegmentPointerMove=
function(a){if(this._segmentDragStartInfo){a.preventDefault();var {_trackHeight:b,_trackWidth:c,_segmentDragStartInfo:{index:f,cursorPosition:e,details:{min:g,max:h}}}=this,{index:k,position:n,value:r}=g,{index:p,position:x,value:B}=h;this._dragged=!0;a=this._getCursorPositionFromEvent(a);if(a!==e){var t=this._positionToPercent(e);t=this._positionToPercent(a)-t;a=this._positionToPercent(n)+t;t=this._positionToPercent(x)+t;var {min:z}=this._getAnchorBoundsAsPercents(k),{max:A}=this._getAnchorBoundsAsPercents(p),
I=!1,J=!1;a<z?I=!0:t>A&&(J=!0);if(I){const {min:E,max:F}=this.viewModel.getBoundsForValueAtIndex(k);a=this._isPositionInverted()?F:E;t=B+(a-r);z=t-this.values[p];this.syncedSegmentsEnabled?this._updateAnchorValuesByDifference(z):this._updateAnchorValues([k,p],[a,t])}else if(J){const {min:E,max:F}=this.viewModel.getBoundsForValueAtIndex(p);a=this._isPositionInverted()?E:F;t=r+(a-B);z=t-this.values[k];this.syncedSegmentsEnabled?this._updateAnchorValuesByDifference(z):this._updateAnchorValues([k,p],
[t,a])}else{z=this._isHorizontalLayout()?c:b;t=t/100*z;A=this.values;var P=[A[k],A[p]];a=this._getValueForAnchorAtPosition(k,a/100*z);t=this._getValueForAnchorAtPosition(p,t);this.syncedSegmentsEnabled?this._updateAnchorValuesByDifference(a-P[0]):this._updateAnchorValues([k,p],[a,t]);[this.values[k],this.values[p]].every((E,F)=>E===P[F])||this._emitSegmentDragEvent({index:f,state:"drag",thumbIndices:[k,p]})}}}};d._onSegmentPointerUp=function(a){a.preventDefault();document.removeEventListener("pointerup",
this._onSegmentPointerUp);document.removeEventListener("pointermove",this._onSegmentPointerMove);if(this._segmentDragStartInfo){var {_dragged:b,max:c,min:f,values:e}=this,{index:g,details:{min:{index:h},max:{index:k}}}=this._segmentDragStartInfo;this.segmentElements.forEach(n=>n.classList.remove("esri-slider__segment--active"));this._anchorElements.forEach(n=>n.classList.remove("esri-slider__anchor--active"));if(this.draggableSegmentsEnabled){const n=e[h];this._lastMovedHandleIndex=n===e[k]?n>(c-
f)/2?h:k:null;this._dragged=!1;this._segmentDragStartInfo=null;this.notifyChange("state");this._emitSegmentDragEvent({index:g,state:"stop",thumbIndices:[h,k]})}b||(a=this._getCursorPositionFromEvent(a),a=this._valueFromPosition(a),this._emitSegmentClickEvent({index:g,value:a,thumbIndices:[h,k]}))}};d._onTickGroupClick=function(a){a=a.target;a["data-config"]&&this._emitTickClickEvent({configIndex:a["data-tick-config-index"],groupIndex:a["data-tick-group-index"],value:a["data-value"]})};d._storeTrackDimensions=
function(){if(this.trackElement){const a=this._getDimensions(this.trackElement);this._trackHeight=a.height;this._trackWidth=a.width}};d._onLabelPointerDown=function(){this._isDisabled()||(this._dragged=!1,document.addEventListener("pointerup",this._onAnchorPointerUp),document.addEventListener("pointermove",this._onAnchorPointerMove))};d._onLabelPointerMove=function(){this._isDisabled()||(this._dragged=!0)};d._onLabelPointerUp=function(a){this._isDisabled()||(a=a.target["data-thumb-index"],this.labelInputsEnabled&&
!this._dragged&&u.isSome(a)&&(this._activeLabelInputIndex=a),this._dragged=!1,this.notifyChange("state"),document.removeEventListener("pointerup",this._onLabelPointerUp),document.removeEventListener("pointermove",this._onLabelPointerMove))};d._onLabelInputBlur=function(a){const {_activeLabelInputIndex:b,values:c,viewModel:f}=this;a=a.target.value;this._activeLabelInputIndex=null;this.notifyChange("state");if(a){var e=this._parseInputValue(a,"value",b);a=c[b];var {min:g,max:h}=this.viewModel.getBoundsForValueAtIndex(b);
e<g||e>h||(f.setValue(b,e),e=this.values[b],a!==e&&this._emitThumbChangeEvent({index:b,oldValue:a,value:e}))}};d._onInputKeyDown=function(a){if(!this._isDisabled()){var {target:b}=a,c=G.eventKey(a),{hideInput1:f,hideInput2:e,hideInput3:g}=w,{_activeLabelInputIndex:h,_anchorElements:k}=this;if(c===f||c===e||c===g)a.stopPropagation(),b.blur(),u.isSome(h)?k[h].focus():b.parentElement.focus()}};d._onMaxLabelClick=function(){this._isDisabled()||(this._emitRangeLabelClickEvent({type:"max-click",value:this.max}),
this.rangeLabelInputsEnabled&&(this._isMaxInputActive=!0,this.notifyChange("state")))};d._onMaxLabelKeyDown=function(a){this._isDisabled()||G.eventKey(a)!==w.showInput||(this._isMaxInputActive=!0,this.notifyChange("state"))};d._onMaxInputBlur=function(a){var b=a.target.value;this._isMaxInputActive=!1;this.notifyChange("state");b&&(a=this.max,b=this._parseInputValue(b,"max"),b<=this.min||(this.viewModel.set("max",b),this.max!==a&&this._emitMaxChangeEvent({oldValue:a,value:this.max})))};d._onMinLabelClick=
function(){this._isDisabled()||(this._emitRangeLabelClickEvent({type:"min-click",value:this.min}),this.rangeLabelInputsEnabled&&(this._isMinInputActive=!0,this.notifyChange("state")))};d._onMinLabelKeyDown=function(a){this._isDisabled()||G.eventKey(a)!==w.showInput||(this._isMinInputActive=!0,this.notifyChange("state"))};d._onMinInputBlur=function(){var a=event.target.value;this._isMinInputActive=!1;this.notifyChange("state");if(a){var b=this.min;a=this._parseInputValue(a,"min");a>=this.max||(this.viewModel.set("min",
a),this.min!==b&&this._emitMinChangeEvent({oldValue:b,value:this.min}))}};d._isDisabled=function(){return this.disabled||"disabled"===this.state};d._positionFromValue=function(a){const {max:b,min:c}=this,f=b-c;if(0===f)return 0;const {_trackHeight:e,_trackWidth:g}=this,h=this._isHorizontalLayout();a=h?parseFloat((g*(a-c)/f).toFixed(2)):parseFloat((e*(b-a)/f).toFixed(2));this._isReversedLayout()&&(a=h?g-a:e-a);return a};d._valueFromPosition=function(a){const {_trackHeight:b,_trackWidth:c,max:f,min:e,
precision:g}=this,h=f-e;a=this._isHorizontalLayout()?a*h/c+e:h*(1E3-a/b*1E3)/1E3+e;this._isReversedLayout()&&(a=f+e-a);return parseFloat(a.toFixed(g))};d._positionToPercent=function(a){const {_trackHeight:b,_trackWidth:c}=this,f=this._isHorizontalLayout()?c:b;return this._applyPrecisionToPosition(100*a/f)};d._applyPrecisionToPosition=function(a){return parseFloat(a.toFixed(this._positionPrecision))};d._isPositionInverted=function(){const {layout:a}=this;return"horizontal-reversed"===a||"vertical"===
a};d._isHorizontalLayout=function(){return-1<this.layout.indexOf("horizontal")};d._isReversedLayout=function(){return-1<this.layout.indexOf("reversed")};d._normalizeSegmentDetails=function(a){if(this._isPositionInverted()){const {min:b,max:c}=a;return{min:c,max:b}}return a};d._parseInputValue=function(a,b,c){return this.inputParseFunction?this.inputParseFunction(a,b,c):this.viewModel.defaultInputParseFunction(a)};d._formatInputValue=function(a,b,c){return this.inputFormatFunction?this.inputFormatFunction(a,
b,c):this.viewModel.defaultInputFormatFunction(a)};d._getAnchorDetails=function(a){a=[...this.values].sort((f,e)=>f-e)[a];const b=this.values.indexOf(a),c=this._getPositionOfElement(this._anchorElements[b]);return{index:b,position:c,value:a}};d._updateAnchorStyle=function(a,b){if(a=this._anchorElements[a])this._isHorizontalLayout()?a.style.left=`${b}`:a.style.top=`${b}`};d._getStyleForAnchor=function(a,b,c){a=this._getPositionStyleForElement(a);if(1===this.values.length)return`${a}`;b=this._zIndices[b];
return`${a}; z-index: ${c?this._zIndexOffset+b:b}`};d._getPositionStyleForElement=function(a){a=this._positionFromValue(a);a=this._positionToPercent(a);return`${this._isHorizontalLayout()?"left":"top"}: ${a+"%"}`};d._getPositionOfElement=function(a){const b=this._getDimensions(a.offsetParent);a=this._getDimensions(a);return this._isHorizontalLayout()?this._applyPrecisionToPosition(a.left-b.left):this._applyPrecisionToPosition(a.top-b.top)};d._updateAnchorValues=function(a,b){a.forEach((c,f)=>this._toValue(c,
b[f]))};d._updateAnchorValuesByDifference=function(a){const {min:b,max:c,values:f}=this;f.forEach((e,g)=>this._toValue(g,Math.max(Math.min(e+a,c),b)))};d._toValue=function(a,b){if(u.isSome(this.steps)){const c=this._getStepValues();b=this._getIndexOfNearestStepValue(b);b=c[b]}this._updateAnchorStyle(a,this._getPositionStyleForElement(b));this.viewModel.setValue(a,b)};d._toPosition=function(a,b){b=u.isSome(this.steps)?this._getStepValueForAnchorAtPosition(a,b):this._getValueForAnchorAtPosition(a,b);
this._updateAnchorStyle(a,this._getPositionStyleForElement(b));this.viewModel.setValue(a,b)};d._getValueForAnchorAtPosition=function(a,b){const {min:c,max:f}=this._getAnchorBoundsInPixels(a),{min:e,max:g}=this.viewModel.getBoundsForValueAtIndex(a);a=null;let h;this._isPositionInverted()?(a=e,h=g):(a=g,h=e);a=b>f?a:b<c?h:this._valueFromPosition(b);a>g?a=g:a<e&&(a=e);return a};d._getStepValueForAnchorAtPosition=function(a,b){const c=this._getStepValues();b=this._calculateNearestStepPosition(b);a=this._getValueForAnchorAtPosition(a,
b);a=this._getIndexOfNearestStepValue(a);return c[a]};d._getAnchorBoundsAsPercents=function(a){const {min:b,max:c}=this._getAnchorBoundsInPixels(a);return{min:this._positionToPercent(b),max:this._positionToPercent(c)}};d._getAnchorBoundsInPixels=function(a){const {_anchorElements:b,_trackHeight:c,_trackWidth:f,thumbsConstrained:e}=this,g=b[a-1];a=b[a+1];const h=this._isHorizontalLayout()?f:c;return e?this._isPositionInverted()?{max:g?this._getPositionOfElement(g):h,min:a?this._getPositionOfElement(a):
0}:{max:a?this._getPositionOfElement(a):h,min:g?this._getPositionOfElement(g):0}:{max:h,min:0}};d._getIndexOfNearestValue=function(a){return this.values.indexOf(this.values.reduce((b,c)=>Math.abs(c-a)<Math.abs(b-a)?c:b))};d._getCursorPositionFromEvent=function(a){const b=this._getDimensions(this.trackElement);return this._isHorizontalLayout()?a.clientX-b.left:a.clientY-b.top};d._getStepValues=function(){const {steps:a}=this;if(Array.isArray(a))return a;const {max:b,min:c}=this,f=Math.ceil((b-c)/a),
e=[];for(let g=0;g<=f;g++){const h=c+a*g;e.push(h>b?b:h)}return e};d._toStep=function(a,b){const {values:c,viewModel:f}=this;var e=c[a];const g=this._getStepValues(),h=g.indexOf(e);let k=null;-1<h?(b=this._positionFromValue(g[h+b]),k=this._getStepValueForAnchorAtPosition(a,b)):(e=this._getIndexOfNearestStepValue(e),k=g[e+b]);f.setValue(a,k)};d._getIndexOfNearestStepValue=function(a){var {steps:b}=this;if(!u.isSome(b))return null;b=this._getStepValues();const c=b.reduce((f,e)=>Math.abs(e-a)<Math.abs(f-
a)?e:f);return b.indexOf(c)};d._calculateNearestStepPosition=function(a){a=this._valueFromPosition(a);a=this._getIndexOfNearestStepValue(a);const b=this._getStepValues();return this._positionFromValue(b[a])};d._getTickCounts=function(a,b){({mode:b}=b);return"count"===b||"position"===b?a||0:"percent"===b?100/a||0:0};d._calculateTickPositions=function(a){return a.map(b=>this._positionFromValue(b))};d._calculateEquidistantTickPositions=function(a){const {_trackWidth:b,_trackHeight:c}=this,f=this._isHorizontalLayout()?
b:c,e=f/(a-1),g=[];if(1===a)return[f/2];for(let h=0;h<a;h++){const k=h*e;k<=f&&g.push(k)}return g};d._getDimensions=function(a){try{return a.getBoundingClientRect()}catch(b){if("object"===typeof b&&null!==b)return{top:0,bottom:0,left:0,width:0,height:0,right:0};throw b;}};d._emitTrackClickEvent=function(a){this.emit("track-click",{...a,type:"track-click"})};d._emitTickClickEvent=function(a){this.emit("tick-click",{...a,type:"tick-click"})};d._emitMaxChangeEvent=function(a){this.emit("max-change",
{...a,type:"max-change"})};d._emitMinChangeEvent=function(a){this.emit("min-change",{...a,type:"min-change"})};d._emitThumbChangeEvent=function(a){this.emit("thumb-change",{...a,type:"thumb-change"})};d._emitThumbClickEvent=function(a){this.emit("thumb-click",{...a,type:"thumb-click"})};d._emitThumbDragEvent=function(a){this.emit("thumb-drag",{...a,type:"thumb-drag"})};d._emitSegmentClickEvent=function(a){this.emit("segment-click",{...a,type:"segment-click"})};d._emitSegmentDragEvent=function(a){this.emit("segment-drag",
{...a,type:"segment-drag"})};d._emitRangeLabelClickEvent=function(a){this.emit(a.type,{...a})};y._createClass(H,[{key:"labelsVisible",set:function(a){K.deprecatedProperty(M,"labelsVisible",{replacement:"visibleElements.labels",version:"4.15"});this.visibleElements={...this.visibleElements,labels:a}}},{key:"layout",set:function(a){-1===["vertical","vertical-reversed","horizontal","horizontal-reversed"].indexOf(a)&&(a="horizontal");this._set("layout",a)}},{key:"rangeLabelsVisible",set:function(a){K.deprecatedProperty(M,
"rangeLabelsVisible",{replacement:"visibleElements.rangeLabels",version:"4.15"});this.visibleElements={...this.visibleElements,rangeLabels:a}}},{key:"state",get:function(){const {_activeLabelInputIndex:a,_isMaxInputActive:b,_isMinInputActive:c,_dragStartInfo:f,_segmentDragStartInfo:e,disabled:g,viewModel:h}=this,k=u.isSome(f)||u.isSome(e);return g?"disabled":null!==a||b||c?"editing":k?"dragging":h.state}},{key:"tickConfigs",set:function(a){this._set("tickConfigs",a);this.scheduleRender()}}]);return H}(U);
m.__decorate([q.property()],l.prototype,"disabled",void 0);m.__decorate([q.property()],l.prototype,"extraNodes",void 0);m.__decorate([q.property()],l.prototype,"draggableSegmentsEnabled",void 0);m.__decorate([q.property()],l.prototype,"inputCreatedFunction",void 0);m.__decorate([C.aliasOf("viewModel.inputFormatFunction")],l.prototype,"inputFormatFunction",void 0);m.__decorate([C.aliasOf("viewModel.inputParseFunction")],l.prototype,"inputParseFunction",void 0);m.__decorate([q.property({aliasOf:{source:"messages.widgetLabel",
overridable:!0}})],l.prototype,"label",void 0);m.__decorate([q.property({readOnly:!0})],l.prototype,"labelElements",void 0);m.__decorate([q.property()],l.prototype,"labelInputsEnabled",void 0);m.__decorate([C.aliasOf("viewModel.labelFormatFunction")],l.prototype,"labelFormatFunction",void 0);m.__decorate([C.aliasOf("viewModel.labels")],l.prototype,"labels",void 0);m.__decorate([q.property()],l.prototype,"labelsVisible",null);m.__decorate([q.property({value:"horizontal"})],l.prototype,"layout",null);
m.__decorate([C.aliasOf("viewModel.max")],l.prototype,"max",void 0);m.__decorate([q.property({readOnly:!0})],l.prototype,"maxLabelElement",void 0);m.__decorate([q.property(),W.messageBundle("esri/widgets/Slider/t9n/Slider")],l.prototype,"messages",void 0);m.__decorate([C.aliasOf("viewModel.min")],l.prototype,"min",void 0);m.__decorate([q.property({readOnly:!0})],l.prototype,"minLabelElement",void 0);m.__decorate([C.aliasOf("viewModel.precision")],l.prototype,"precision",void 0);m.__decorate([q.property()],
l.prototype,"rangeLabelInputsEnabled",void 0);m.__decorate([q.property()],l.prototype,"rangeLabelsVisible",null);m.__decorate([q.property({readOnly:!0})],l.prototype,"segmentElements",void 0);m.__decorate([q.property()],l.prototype,"snapOnClickEnabled",void 0);m.__decorate([q.property({readOnly:!0})],l.prototype,"state",null);m.__decorate([q.property()],l.prototype,"steps",void 0);m.__decorate([q.property()],l.prototype,"syncedSegmentsEnabled",void 0);m.__decorate([C.aliasOf("viewModel.thumbsConstrained")],
l.prototype,"thumbsConstrained",void 0);m.__decorate([q.property()],l.prototype,"thumbCreatedFunction",void 0);m.__decorate([q.property({readOnly:!0})],l.prototype,"thumbElements",void 0);m.__decorate([q.property()],l.prototype,"tickConfigs",null);m.__decorate([q.property({readOnly:!0})],l.prototype,"tickElements",void 0);m.__decorate([q.property({readOnly:!0})],l.prototype,"trackElement",void 0);m.__decorate([C.aliasOf("viewModel.values")],l.prototype,"values",void 0);m.__decorate([q.property()],
l.prototype,"viewModel",void 0);m.__decorate([q.property()],l.prototype,"visibleElements",void 0);m.__decorate([R.cast("visibleElements")],l.prototype,"castVisibleElements",null);return l=m.__decorate([S.subclass("esri.widgets.Slider")],l)});