// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../../chunks/_rollupPluginBabelHelpers ../../../chunks/tslib.es6 ../../../request ../../../core/Accessor ../../../core/arrayUtils ../../../core/Error ../../../core/lang ../../../core/maybe ../../../core/promiseUtils ../../../core/accessorSupport/decorators/property ../../../core/accessorSupport/ensureType ../../../core/has ../../../core/Logger ../../../core/jsonMap ../../../core/accessorSupport/decorators/subclass ./AsyncWorkerQueue ./StreamDataLoaderTask ../webgl-engine/lib/Util ../../support/Scheduler".split(" "),
function(l,t,q,u,A,B,C,D,v,m,E,L,M,N,O,F,G,H,I,J){function K(f){if(2>f.byteLength)return"unknown";f=new Uint8Array(f,0,f.byteLength);return 137===f[0]&&80===f[1]?"image/png":71===f[0]&&73===f[1]?"image/gif":66===f[0]&&77===f[1]?"image/bmp":255===f[0]&&216===f[1]?"image/jpeg":"unknown"}l.StreamDataLoader=function(f){function p(){var a=f.apply(this,arguments)||this;a.tasks=new Map;a.onLoadQueue=[];a.doneQueue=[];a.updating=!1;return a}t._inheritsLoose(p,f);var g=p.prototype;g.setup=function(a,b,e){this.loadQueue=
new G.AsyncWorkerQueue((c,d)=>this.startLoading(c,d),(c,d)=>this.doneLoadingCallback(c,d),a,b);e&&(this.taskHandle=e.registerTask(J.TaskPriority.STREAM_DATA_LOADER,this))};g.destroy=function(){this.taskHandle=v.removeMaybe(this.taskHandle);this.tasks.forEach(a=>{a.abortController&&a.abortController.abort()});this.loadQueue.destroy();this.tasks=this.doneQueue=this.onLoadQueue=this.loadQueue=null};g.hasDownloadSlots=function(a){return this.loadQueue.hasQuota(a)};g.request=function(a,b,e,c={}){const d=
m.createResolver();d.__signal=v.isSome(c)?c.signal:null;const k=this.createOrUpdateTask(a,b,e,c,d);m.onAbort(c,()=>this.cancelRequest(k,d));return d.promise};g.createTask=function(a,b,e,c,d,k){a=new H(a,b,e,c,d);this.updateTask(a,k);this.tasks.set(d,a);1===this.tasks.size&&this._set("updating",!0);this.loadQueue.push(a);return a};g.cancelRequest=function(a,b){B.removeUnordered(a.resolvers,b);b.reject(m.createAbortError());0===a.resolvers.length&&(2===a.status&&(a.status=4,this.loadQueue.cancel(a),
a.abortController.abort(),a.request=null,a.abortController=null),a.status=4,this.tasks.delete(a.key),0===this.tasks.size&&this._set("updating",!1))};g.taskKey=function(a,b,e){return`${a}:${b}:${e}`};g.updateTask=function(a,b){a.resolvers.push(b)};g.createOrUpdateTask=function(a,b,e,c,d){var k=v.isSome(c)&&c.uid||a;k=this.taskKey(k,b,e);const n=this.tasks.get(k);return n?(this.updateTask(n,d),n):this.createTask(a,c,b,e,k,d)};g.doneLoadingCallback=function(a,b){this.loadQueue&&(I.assert(2===a.status),
a.status=3,this.taskHandle?this.doneQueue.push({task:a,err:b}):this.doneLoading(a,b))};g.runTask=function(a){for(;!a.done&&0<this.onLoadQueue.length;){var b=this.onLoadQueue.shift();m.throwIfAborted(b.task.abortController);b.task.abortController=null;b.callback(b.task);a.madeProgress()}for(;!a.done&&0<this.doneQueue.length;)b=this.doneQueue.shift(),3!==b.task.status&&(b.err=b.err||m.createAbortError()),this.doneLoading(b.task,b.err),a.madeProgress()};g.doneLoading=function(a,b){let e=a.result instanceof
HTMLImageElement?0:a.resolvers.length;for(const c of a.resolvers)if(b)m.isAbortError(b)?c.reject(b):c.reject(new C("stream-data-loader:request-error",`Failed to request resource at '${a.url}'. ${b}`,{url:a.url,error:b}));else{--e;const d=0>=e?a.result:D.clone(a.result);c.resolve(d)}this.tasks.delete(a.key);0===this.tasks.size&&this._set("updating",!1)};g.startLoading=function(a,b){if(4===a.status)return!1;a.startTime=performance.now();a.status=2;let e,c;switch(a.docType){case "binary":c="array-buffer";
e=0;break;case "image":c="image";break;case "image+type":c="array-buffer";break;default:c="json"}a.abortController=m.createAbortController();const d=a.abortController.signal;a.request=u(a.url,{...a.options,responseType:c,timeout:e,signal:d});let k=()=>{};const n=h=>{a.duration=performance.now()-a.startTime;a.size=h instanceof ArrayBuffer?h.byteLength:a.size||0;a.result=h;this.taskHandle?this.onLoadQueue.push({callback:b,task:a}):(a.abortController=null,b(a))},r=h=>{2===a.status&&b(a,h);k()};if("image+type"!==
a.docType)return a.request.then(h=>n(h.data),r),!0;a.request.then(h=>{h=h.data;const w=K(h);c="image";a.size=h.byteLength;if("unknown"===w)a.request=u(a.url,{responseType:c,timeout:e,signal:d}),a.request.then(x=>n(x.data),r);else{h=new Blob([h],{type:w});var y=window.URL.createObjectURL(h);k=()=>window.URL.revokeObjectURL(y);a.request=u(y,{responseType:c,timeout:e,signal:d});a.request.then(x=>n(new z(x.data,w,k)),r)}},r);return!0};t._createClass(p,[{key:"running",get:function(){return 0<this.doneQueue.length||
0<this.onLoadQueue.length}},{key:"test",get:function(){return{loadQueue:this.loadQueue}}}]);return p}(A);q.__decorate([E.property({readOnly:!0})],l.StreamDataLoader.prototype,"updating",void 0);l.StreamDataLoader=q.__decorate([F.subclass("esri.views.3d.support.StreamDataLoader")],l.StreamDataLoader);let z=function(){function f(p,g,a){this.image=p;this.type=g;this.release=a}t._createClass(f,[{key:"isOpaque",get:function(){return"image/jpeg"===this.type}}]);return f}();q=l.StreamDataLoader;l.ImageWithType=
z;l.default=q;Object.defineProperty(l,"__esModule",{value:!0})});