// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
require({cache:{"esri/views/2d/engine/webgl/FeatureTile":function(){define("exports ../../../../chunks/_rollupPluginBabelHelpers ../../../../core/CircularArray ../../../../core/has ../../../../core/maybe ../../../../chunks/mat2d ../../../../chunks/mat2df32 ../../../../chunks/vec2 ../../../../chunks/vec2f32 ./enums ./Utils ./WGLTile ./collisions/MetricReader ./cpuMapped/Geometry".split(" "),function(v,t,q,m,k,h,d,a,f,c,n,u,p,w){let y=0;m=function(x){function r(b,g,l){b=x.call(this,b,g)||this;b.instanceId=
y++;b.patchCount=0;b._renderState={current:{geometry:new Map,metrics:null},next:null,swap:!1,swapFrames:0,locked:!1};b._patches=new q(100);b._lastCommitTime=0;b._lastMessageWasClear=!1;b.transforms.labelMat2d=d.create();b._store=l;return b}t._inheritsLoose(r,x);var e=r.prototype;e.destroy=function(){x.prototype.destroy.call(this);this._renderState.current.geometry.forEach(b=>b.destroy())};e.getGeometry=function(b){return this._renderState.current.geometry.get(b)};e.setTransform=function(b,g){x.prototype.setTransform.call(this,
b,g);const l=this.transforms.labelMat2d;g=b.getScreenTransform(l,g);const z=f.create();a.transformMat2d(z,this.coords,g);h.identity(l);h.translate(l,l,z);h.multiply(l,b.viewMat2d,l)};e.patch=function(b){this.patchCount++;b.clear&&this._lastMessageWasClear||((this._lastMessageWasClear=b.clear)&&50<=this._patches.size&&this._dropPatches(),this._patches.enqueue(b),this.requestRender())};e.commit=function(b){if(this._lastCommitTime!==b.time){this._lastCommitTime=b.time;for(b=0;4>b;b++)this._updateMesh();
this._renderState.swap&&(this._swapRenderStates(),this.requestRender())}};e.lock=function(){this._renderState.locked=!0};e.unlock=function(){this._renderState.locked=!1;this._flushUpdates();this._swap()};e._swapRenderStates=function(){this._renderState.next&&(this._renderState.locked?(this._renderState.swap=!0,this.requestRender()):(this._renderState.swap=!0,0===this._renderState.swapFrames?(this._renderState.swapFrames=8,this.requestRender()):1!==this._renderState.swapFrames--?this.requestRender():
this._swap()))};e._swap=function(){this._renderState.swap&&(this._renderState.swap=!1,k.isSome(this._renderState.next)&&(this._renderState.current.geometry.forEach(b=>b.destroy()),this._renderState.current=this._renderState.next,this._renderState.next=null))};e._flushUpdates=function(){let b=this._patches.maxSize;for(;this._patches.size&&b--;)this._updateMesh(),this._swap()};e._updateMesh=function(){var b=this._patches.peek();k.isSome(b)&&b.clear&&null!==this._renderState.next||(b=this._patches.dequeue(),
k.isSome(b)&&(!0===b.clear?this.isReady&&(this._renderState.next={geometry:new Map,metrics:null}):(this.requestRender(),this._patch(b),b.end&&(this.ready(),this._swapRenderStates()))))};e._patch=function(b){n.forEachGeometryType(g=>{this._remove(g,b.remove);this._insert(b.type,g,b.addOrUpdate,b.clear)})};e._insert=function(b,g,l,z){try{const C=k.unwrapOr(this._renderState.next,this._renderState.current),A=null==l?void 0:l.data[g],B=C.geometry;k.isNone(A)||(B.has(g)||B.set(g,new w.Geometry(g,this.stage)),
B.get(g).insert(b,A),g===c.WGLGeometryType.LABEL&&this._insertLabelMetrics(b,A.metrics,z))}catch(C){}};e._insertLabelMetrics=function(b,g,l){l=k.unwrapOr(this._renderState.next,this._renderState.current);if(!k.isNone(g))if(g=p.MetricReader.from(g),k.isNone(l.metrics))l.metrics=g;else{if("update"===b)for(b=g.getCursor();b.next();)l.metrics.delete(b.id);l.metrics.link(g)}};e._remove=function(b,g){b=k.unwrapOr(this._renderState.next,this._renderState.current).geometry.get(b);g&&g.length&&b&&(b.remove(g),
this._removeLabelMetrics(g))};e._removeLabelMetrics=function(b){const {metrics:g}=k.unwrapOr(this._renderState.next,this._renderState.current);if(!k.isNone(g)&&b.length)for(const l of b)for(;g.delete(l););};e._dropPatches=function(){const b=[];let g=!1;for(;this._patches.size;){const l=this._patches.dequeue();if(k.isNone(l))break;if(l.clear){if(g)break;g=!0}b.push(l)}this._patches.clear();b.forEach(l=>this._patches.enqueue(l))};t._createClass(r,[{key:"labelMetrics",get:function(){return this._renderState.current.metrics}},
{key:"hasData",get:function(){return!!this._renderState.current.geometry.size}}]);return r}(u.WGLTile);v.FeatureTile=m;Object.defineProperty(v,"__esModule",{value:!0})})},"esri/views/2d/engine/webgl/collisions/MetricReader":function(){define(["exports","../../../../../chunks/_rollupPluginBabelHelpers","../../../../../core/maybe"],function(v,t,q){let m=function(){function h(a){this._cursor=this._head=a}h.from=function(a){a=k.from(new Float32Array(a));return new h(a)};var d=h.prototype;d.computedMinZoom=
function(){return this._cursor.computedMinZoom()};d.setComputedMinZoom=function(a){return this._cursor.setComputedMinZoom(a)};d.boundsComputedAnchorX=function(a){return this._cursor.boundsComputedAnchorX(a)};d.boundsComputedAnchorY=function(a){return this._cursor.boundsComputedAnchorY(a)};d.setBoundsComputedAnchorX=function(a,f){return this._cursor.setBoundsComputedAnchorX(a,f)};d.setBoundsComputedAnchorY=function(a,f){return this._cursor.setBoundsComputedAnchorY(a,f)};d.boundsCenterX=function(a){return this._cursor.boundsCenterX(a)};
d.boundsCenterY=function(a){return this._cursor.boundsCenterY(a)};d.boundsWidth=function(a){return this._cursor.boundsWidth(a)};d.boundsHeight=function(a){return this._cursor.boundsHeight(a)};d.link=function(a){if(q.isSome(a._head))return this._cursor.link(a._head)};d.getCursor=function(){return this.copy()};d.copy=function(){var a;const f=new h(null==(a=this._head)?void 0:a.copy());if(!f._head)return f;a=f._head;let c=f._head._link;for(;c;)a._link=c.copy(),a=c,c=a._link;return f};d.peekId=function(){var a;
return null!=(a=this._cursor.peekId())?a:this._cursor._link.peekId()};d.nextId=function(){const a=this.id;for(;a===this.id;)if(!this.next())return!1;return!0};d.save=function(){this._savedCursor=this._cursor;this._savedOffset=this._cursor._offset};d.restore=function(){this._cursor=this._savedCursor;this._cursor._offset=this._savedOffset};d.next=function(){if(!this._cursor)return!1;if(!this._cursor.next()){if(!this._cursor._link)return!1;this._cursor=this._cursor._link;this._cursor._offset=0}return!0};
d.lookup=function(a){for(this._cursor=this._head;this._cursor&&!this._cursor.lookup(a);){if(!this._cursor._link)return!1;this._cursor=this._cursor._link}return!!this._cursor};d.delete=function(a){let f=this._head,c=null;for(;f;){if(f.delete(a))return f.isEmpty()&&q.isSome(c)&&(c._link=f._link),!0;c=f;f=f._link}return!1};t._createClass(h,[{key:"id",get:function(){return this._cursor.id}},{key:"baseZoom",get:function(){return this._cursor.baseZoom}},{key:"anchorX",get:function(){return this._cursor.anchorX}},
{key:"anchorY",get:function(){return this._cursor.anchorY}},{key:"directionX",get:function(){return this._cursor.directionX}},{key:"directionY",get:function(){return this._cursor.directionY}},{key:"size",get:function(){return this._cursor.size}},{key:"materialKey",get:function(){return this._cursor.materialKey}},{key:"boundsCount",get:function(){return this._cursor.boundsCount}}]);return h}(),k=function(){function h(a){this._offset=-1;this._link=null;this._deletedCount=this._count=0;this._offsets=
{instance:null};this._buffer=a}h.from=function(a){return new h(new Float32Array(a))};var d=h.prototype;d.isEmpty=function(){return this._deletedCount===this.count};d.computedMinZoom=function(){return this._buffer[this._offset+8]};d.setComputedMinZoom=function(a){this._buffer[this._offset+8]=a};d.boundsComputedAnchorX=function(a){return this._buffer[this._offset+10+6*a+0]};d.boundsComputedAnchorY=function(a){return this._buffer[this._offset+10+6*a+1]};d.setBoundsComputedAnchorX=function(a,f){this._buffer[this._offset+
10+6*a+0]=f};d.setBoundsComputedAnchorY=function(a,f){this._buffer[this._offset+10+6*a+1]=f};d.boundsCenterX=function(a){return this._buffer[this._offset+10+6*a+2]};d.boundsCenterY=function(a){return this._buffer[this._offset+10+6*a+3]};d.boundsWidth=function(a){return this._buffer[this._offset+10+6*a+4]};d.boundsHeight=function(a){return this._buffer[this._offset+10+6*a+5]};d.link=function(a){let f=this;for(;f._link;)f=f._link;f._link=a};d.getCursor=function(){return this.copy()};d.copy=function(){const a=
new h(this._buffer);a._link=this._link;a._offset=this._offset;a._deletedCount=this._deletedCount;a._offsets=this._offsets;a._count=this._count;return a};d.peekId=function(){const a=this._offset+10+6*this.boundsCount+0;return a>=this._buffer.length?0:this._buffer[a]};d.next=function(){let a=0;for(;this._offset<this._buffer.length&&100>a++&&(this._offset=-1===this._offset?0:this._offset+(10+6*this.boundsCount),4294967296===this.id););return 4294967296!==this.id&&this._offset<this._buffer.length};d.delete=
function(a){const f=this._offset,c=this.lookup(a);if(c)for(this.id=4294967295,++this._deletedCount;this.next()&&this.id===a;)this.id=4294967295,++this._deletedCount;this._offset=f;return c};d.lookup=function(a){const f=this._offset;if(q.isNone(this._offsets.instance)){this._offsets.instance=new Map;const c=this.copy();c._offset=-1;let n=0;for(;c.next();)c.id!==n&&(this._offsets.instance.set(c.id,c._offset),n=c.id)}if(!this._offsets.instance.has(a))return!1;this._offset=this._offsets.instance.get(a);
return 4294967296===this.id?(this._offset=f,!1):!0};d._computeCount=function(){const a=this._offset;let f=0;for(this._offset=-1;this.next();)f++;this._offset=a;return f};t._createClass(h,[{key:"count",get:function(){this._count||(this._count=this._computeCount());return this._count}},{key:"id",get:function(){return this._buffer[this._offset+0]},set:function(a){this._buffer[this._offset+0]=a}},{key:"baseZoom",get:function(){return this._buffer[this._offset+1]}},{key:"anchorX",get:function(){return this._buffer[this._offset+
2]}},{key:"anchorY",get:function(){return this._buffer[this._offset+3]}},{key:"directionX",get:function(){return this._buffer[this._offset+4]}},{key:"directionY",get:function(){return this._buffer[this._offset+5]}},{key:"size",get:function(){return this._buffer[this._offset+6]}},{key:"materialKey",get:function(){return this._buffer[this._offset+7]}},{key:"boundsCount",get:function(){return this._buffer[this._offset+9]}}]);return h}();v.MetricReader=m;v.MetricReaderNode=k;Object.defineProperty(v,"__esModule",
{value:!0})})},"esri/views/2d/engine/webgl/cpuMapped/Geometry":function(){define(["exports","../../../../../core/has"],function(v,t){t=function(){function q(k,h){this._buffers=[];this.geometryType=k;this._stage=h}var m=q.prototype;m.destroy=function(){this._buffers.forEach(k=>k.release())};m.insert=function(k,h){if(h.records.byteLength){"update"===k&&this._buffers.forEach(a=>a.free(h));var d={done:!1,offset:0,vertexData:h};this._buffers.forEach(a=>a.insert(d));for(k=1E3;!d.done&&--k;){const a=this._stage.pools.bufferData.acquire(h,
this.geometryType,d.offset);a.insert(d);this._buffers.push(a)}}};m.remove=function(k){this._buffers.forEach(h=>h.freeIds(k))};m.upload=function(k){this._buffers.forEach(h=>h.upload(k))};m.forEachCommand=function(k){this._buffers.forEach(h=>h.displayList.forEach(k))};return q}();v.Geometry=t;Object.defineProperty(v,"__esModule",{value:!0})})},"esri/views/2d/layers/features/tileRenderers/BaseTileRenderer":function(){define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/HandleOwner ../../../../../core/accessorSupport/decorators/property ../../../../../core/has ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/jsonMap ../../../../../core/accessorSupport/decorators/subclass".split(" "),
function(v,t,q,m,k,h,d,a,f){q=function(c){function n(p){p=c.call(this,p)||this;p.tiles=new Map;return p}v._inheritsLoose(n,c);var u=n.prototype;u.destroy=function(){this.tiles.clear();this.layer=this.layerView=this.tileInfoView=this.tiles=null};u.acquireTile=function(p){const w=this.createTile(p);w.once("isReady",()=>this.notifyChange("updating"));this.tiles.set(p.id,w);return w};u.forceAttributeTextureUpload=function(){};u.forEachTile=function(p){this.tiles.forEach(p)};u.releaseTile=function(p){this.tiles.delete(p.key.id);
this.disposeTile(p)};u.isUpdating=function(){let p=!0;this.tiles.forEach(w=>{p=p&&w.isReady});return!p};u.setHighlight=function(){};u.invalidateLabels=function(){};u.requestUpdate=function(){this.layerView.requestUpdate()};v._createClass(n,[{key:"updating",get:function(){return this.isUpdating()}}]);return n}(q.HandleOwner);t.__decorate([m.property()],q.prototype,"layer",void 0);t.__decorate([m.property()],q.prototype,"layerView",void 0);t.__decorate([m.property()],q.prototype,"tileInfoView",void 0);
t.__decorate([m.property()],q.prototype,"updating",null);return q=t.__decorate([f.subclass("esri.views.2d.layers.features.tileRenderers.BaseTileRenderer")],q)})},"esri/views/2d/layers/features/tileRenderers/support/WGLFeatureView":function(){define("exports ../../../../../../chunks/_rollupPluginBabelHelpers ../../../../../../core/promiseUtils ../../../../engine/brushes ../../../../engine/FeatureContainer ../../../../engine/webgl/enums".split(" "),function(v,t,q,m,k,h){k=function(d){function a(c,n,
u,p){c=d.call(this,c)||this;c._pointToCallbacks=new Map;c._layer=u;c._layerView=n;c._onUpdate=p;return c}t._inheritsLoose(a,d);var f=a.prototype;f.renderChildren=function(c){this.attributeView.update();this.hasAnimation&&c.painter.effects.integrate.draw(c,c.attributeView);d.prototype.renderChildren.call(this,c)};f.isUpdating=function(){return this.attributeView.isUpdating()};f.hitTest=function(c,n){c=[c,n];n=q.createResolver();this._pointToCallbacks.set(c,n);this.requestRender();return n.promise};
f.onTileData=function(c,n){c.patch(n);this.contains(c)||this.addChild(c);this.requestRender()};f.onTileError=function(c){this.contains(c)||this.addChild(c)};f.doRender=function(c){const {minScale:n,maxScale:u}=this._layer,p=c.state.scale;p<=(n||Infinity)&&p>=u&&d.prototype.doRender.call(this,c)};f.onAttributeStoreUpdate=function(){this.hasLabels&&this._layerView.view.labelManager.requestUpdate();this._onUpdate()};f.prepareRenderPasses=function(c){const n=c.registerRenderPass({name:"label",brushes:[m.brushes.label],
target:()=>this.hasLabels?this.children:null,drawPhase:h.WGLDrawPhase.LABEL|h.WGLDrawPhase.LABEL_ALPHA}),u=c.registerRenderPass({name:"geometry",brushes:[m.brushes.fill,m.brushes.line,m.brushes.marker,m.brushes.text],target:()=>this.children,enableDefaultDraw:()=>!this._layerView.hasEffects,effects:[{apply:c.effects.outsideEffect,enable:()=>this._layerView.hasEffects,args:()=>this._layerView.effectLists.excluded},{apply:c.effects.insideEffect,enable:()=>this._layerView.hasEffects,args:()=>this._layerView.effectLists.included},
{apply:c.effects.hittest,enable:()=>!!this._pointToCallbacks.size,args:()=>this._pointToCallbacks}]}),p=c.registerRenderPass({name:"highlight",brushes:[m.brushes.fill,m.brushes.line,m.brushes.marker,m.brushes.text],target:()=>this.children,drawPhase:h.WGLDrawPhase.HIGHLIGHT,enableDefaultDraw:()=>!1,effects:[{apply:c.effects.highlight,enable:()=>!!this._layerView.hasHighlight()}]});return[...d.prototype.prepareRenderPasses.call(this,c),u,p,n]};t._createClass(a,[{key:"hasAnimation",get:function(){return this.hasLabels}},
{key:"hasLabels",get:function(){if("sublayers"in this._layer)return this._layer.sublayers.some(n=>n.labelingInfo&&n.labelingInfo.length&&n.labelsVisible);var c=this._layer.featureReduction;c=c&&"cluster"===c.type&&c.labelsVisible&&c.labelingInfo&&c.labelingInfo.length;return this._layer.labelingInfo&&this._layer.labelingInfo.length&&this._layer.labelsVisible||!!c}}]);return a}(k.FeatureContainer);v.WGLFeatureView=k;Object.defineProperty(v,"__esModule",{value:!0})})},"*noref":1}});
define("../../../../../chunks/_rollupPluginBabelHelpers ../../../../../chunks/tslib.es6 ../../../../../core/has ../../../../../core/accessorSupport/decorators/property ../../../../../core/accessorSupport/ensureType ../../../../../core/Logger ../../../../../core/jsonMap ../../../../../core/accessorSupport/decorators/subclass ../../../../../geometry/support/aaBoundingRect ../../../engine/webgl/FeatureTile ../support/rendererUtils ./BaseTileRenderer ./support/visualVariablesUtils ./support/WGLFeatureView".split(" "),function(v,
t,q,m,k,h,d,a,f,c,n,u,p,w){m=function(y){function x(){return y.apply(this,arguments)||this}v._inheritsLoose(x,y);var r=x.prototype;r.install=function(e){const b=new w.WGLFeatureView(this.tileInfoView,this.layerView,this.layer,()=>this.notifyChange("updating"));this.featuresView=b;e.addChild(b)};r.uninstall=function(e){e.removeChild(this.featuresView);this.featuresView.destroy()};r.isUpdating=function(){const e=y.prototype.isUpdating.call(this),b=!this.featuresView||this.featuresView.isUpdating(),
g=e||b;q("esri-2d-log-updating")&&console.log(`Updating SymbolTileRenderer ${g}
  -> updatingTiles ${e}
  -> updatingFeaturesView ${b}`);return g};r.hitTest=function(e,b){return this.featuresView.hitTest(e,b)};r.supportsRenderer=function(e){return null!=e&&-1!==["simple","class-breaks","unique-value","dot-density","dictionary"].indexOf(e.type)};r.onConfigUpdate=function(e){var b=null;"visualVariables"in e&&(b=(n.simplifyVVRenderer(e).visualVariables||[]).map(g=>{const l=g.clone();"normalizationField"in g&&(l.normalizationField=null);g.valueExpression&&"$view.scale"!==g.valueExpression&&(l.valueExpression=
null,l.field="nop");return l}),b=p.convertVisualVariables(b));this.featuresView.setRendererInfo(e,b,this.layerView.effects)};r.onTileData=function(e){const b=this.tiles.get(e.tileKey);if(b&&e.data)this.featuresView.onTileData(b,e.data);this.layerView.view.labelManager.requestUpdate()};r.onTileError=function(e){if(e=this.tiles.get(e.tileKey))this.featuresView.onTileError(e)};r.forceAttributeTextureUpload=function(){this.featuresView.attributeView.forceTextureUpload()};r.lockGPUUploads=function(){this.featuresView.attributeView.lockTextureUpload();
this.tiles.forEach(e=>e.lock())};r.unlockGPUUploads=function(){this.featuresView.attributeView.unlockTextureUpload();this.tiles.forEach(e=>e.unlock())};r.getMaterialItems=function(){var e=v._asyncToGenerator(function*(b){return this.featuresView.getMaterialItems(b)});return function(b){return e.apply(this,arguments)}}();r.invalidateLabels=function(){this.featuresView.hasLabels&&this.layerView.view.labelManager.requestUpdate()};r.createTile=function(e){const b=this.tileInfoView.getTileBounds(f.create(),
e);return new c.FeatureTile(e,b,this.featuresView.attributeView)};r.disposeTile=function(e){this.featuresView.removeChild(e);e.destroy();this.layerView.view.labelManager.requestUpdate()};return x}(u);return m=t.__decorate([a.subclass("esri.views.2d.layers.features.tileRenderers.SymbolTileRenderer")],m)});