// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See https://js.arcgis.com/4.20/esri/copyright.txt for details.
//>>built
define("exports ../../../core/maybe ../../2d/engine/vectorTiles/VectorTile ../support/StreamDataLoader ./RasterTile ../../../chunks/terrainUtilsPlanar ../../../chunks/terrainUtilsSpherical ./TileTexture".split(" "),function(c,h,x,y,z,A,B,C){function n(a){return"vector-tile"===(null==a?void 0:a.type)}function k(a){return"imagery-tile"===(null==a?void 0:a.type)||"wcs"===(null==a?void 0:a.type)}function l(a){return"imagery-tile-3d"===(null==a?void 0:a.type)}function p(a){return"tile-3d"===(null==a?void 0:
a.type)}function q(a){return"vector-tile-3d"===(null==a?void 0:a.type)}function r(a){return"wmts-3d"===(null==a?void 0:a.type)}function t(a){return"elevation-3d"===(null==a?void 0:a.type)}function m(a,b,g,e){return u[e].checkIfTileInfoSupportedForViewSR(a,g,b)}const u={[1]:B.terrainUtilsSpherical,[2]:A.terrainUtilsPlanar},D=80/180*Math.PI,E=110/180*Math.PI,v={force512VTL:!1};c.checkIfTileInfoSupportedForView=m;c.computeSkirtScale=function(a,b,g){const e=u[a.viewingMode];if(e.isInsideExtent(a,b))var d=
h.unwrapOr(a.getElevation(b[0],b[1],b[1],a.spatialReference),0);else{if(!e.isInsideExtent(a,b,1.2))return 0;var f=a.getTileWithElevation(b[0],b[1],b[1],a.spatialReference);d=h.isSome(f)?f.elevationBounds[0]:a.elevationBounds.min;f=h.isSome(f)?f.elevationBounds[1]:a.elevationBounds.max;d=.5*(d+f);a=e.tiltToExtentEdge(a,b,d);if(a>D&&a<E)return 0}b=b[2]-d;return Math.abs(b)<g?0:0>b?-1:1};c.getLayerWithExtentRange=function(a){return l(a)?{fullExtent:a.fullExtent,minScale:a.layer.minScale,maxScale:a.layer.maxScale,
tilemapCache:null}:a.layer};c.getTiledLayerInfo=function(a,b,g){let e,d;if("wmts"===a.type){if(a=a.activeLayer){const f=a.tileMatrixSet;if(f)e=f.tileInfo,d=f.fullExtent;else if(a=a.tileMatrixSets)if(a=a.find(w=>null==m(w.tileInfo,w.fullExtent,b,g)))return{tileInfo:a.tileInfo,fullExtent:a.fullExtent}}}else d=k(a)?a.getCompatibleFullExtent(b):a.fullExtent,e=n(a)&&!v.force512VTL?a.compatibleTileInfo256:k(a)?a.getCompatibleTileInfo(b,d,2===g):a.tileInfo;return e&&d&&null==m(e,d,b,g)?{tileInfo:e,fullExtent:d}:
{tileInfo:null,fullExtent:null}};c.isElevationLayerView=t;c.isImageryTileLayerView=l;c.isImageryTileRenderInfo=function(a){var b;return(null==a?void 0:null==(b=a.sourceLayerInfo)?void 0:b.data)instanceof z};c.isProjectableRasterLayer=k;c.isRasterTileRenderInfo=function(a){var b;a=null==a?void 0:null==(b=a.sourceLayerInfo)?void 0:b.data;return a instanceof HTMLImageElement||a instanceof y.ImageWithType||a instanceof HTMLCanvasElement||a instanceof ImageData};c.isSurfaceLayerView=function(a){return a&&
(p(a)||l(a)||t(a)||q(a)||r(a))};c.isTextureTileRenderInfo=function(a){var b;return(null==a?void 0:null==(b=a.sourceLayerInfo)?void 0:b.data)instanceof C};c.isTileLayerView=p;c.isVectorTileLayer=n;c.isVectorTileLayerView=q;c.isVectorTileRenderInfo=function(a){var b;return(null==a?void 0:null==(b=a.sourceLayerInfo)?void 0:b.data)instanceof x.VectorTile};c.isWMTSLayerView=r;c.releaseTileData=function(a){h.isSome(a)&&"release"in a&&a.release();return null};c.test=v;c.useFetchTileForLayer=function(a){return a.fetchTile&&
!1!==a.hasOverriddenFetchTile};c.weakAssert=function(a,b){a||console.warn("Terrain: "+b)};Object.defineProperty(c,"__esModule",{value:!0})});